### ISSUE TITLE
Russian UI crashes when clicking "New Game"

### ISSUE THREAD

**Issue by Agetian** [magarena/magarena#1007]
Trying to play Magarena in Russian crashes the game upon clicking "New Game". Judging by the exception it seems like the game is trying to find a deck type constant spelled in Russian ("Случайная" for "Random") within the magic.data.DeckType enum.

Crash report:

CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
CREATED ON 2016/12/17 12:21:45
MAGARENA VERSION 1.79, JRE 1.8.0_111, OS Linux_4.4.0-53-generic amd64
================================
Used Memory: 172M
Free Memory: 83M
Total Memory: 255M
Max Memory: 455M
================================
-Xms256M
-Xmx512M
-Xverify:none

Exception from controller.runGame: java.lang.IllegalArgumentException: No enum constant magic.data.DeckType.Случайная
java.lang.RuntimeException: java.lang.IllegalArgumentException: No enum constant magic.data.DeckType.Случайная
	at magic.ui.ScreenController.showScreen(ScreenController.java:182)
	at magic.ui.ScreenController.showNewDuelSettingsScreen(ScreenController.java:282)
	at magic.ui.screen.menu.main.MainMenuContentPanel.doNewDuel(MainMenuContentPanel.java:61)
	at magic.ui.screen.menu.MenuScreenContentPanel$3.actionPerformed(MenuScreenContentPanel.java:55)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: No enum constant magic.data.DeckType.Случайная
	at java.lang.Enum.valueOf(Enum.java:238)
	at magic.data.DeckType.valueOf(DeckType.java:16)
	at magic.model.DuelPlayerConfig.setDeckProfile(DuelPlayerConfig.java:48)
	at magic.data.DuelConfig.loadPlayerConfigs(DuelConfig.java:106)
	at magic.data.DuelConfig.load(DuelConfig.java:99)
	at magic.data.DuelConfig.load(DuelConfig.java:120)
	at magic.ui.screen.duel.setup.NewDuelSettingsScreen.<init>(NewDuelSettingsScreen.java:44)
	at magic.ui.ScreenController.lambda$showNewDuelSettingsScreen$22(ScreenController.java:282)
	at magic.ui.ScreenController.showScreen(ScreenController.java:180)
	... 40 more

**Comment by lodici** [comment]
Confirmed. To replicate - clean install, select russian language and click New Duel to get (slightly different exception)...
```
Exception from controller.runGame: java.lang.IllegalArgumentException: No enum constant magic.data.DeckType.?????????
java.lang.RuntimeException: java.lang.IllegalArgumentException: No enum constant magic.data.DeckType.?????????
	at magic.ui.ScreenController.showScreen(ScreenController.java:182)
	at magic.ui.ScreenController.showNewDuelSettingsScreen(ScreenController.java:282)
	at magic.ui.screen.menu.main.MainMenuContentPanel.doNewDuel(MainMenuContentPanel.java:61)
	at magic.ui.screen.menu.MenuScreenContentPanel$3.actionPerformed(MenuScreenContentPanel.java:55)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No enum constant magic.data.DeckType.?????????
	at java.lang.Enum.valueOf(Unknown Source)
	at magic.data.DeckType.valueOf(DeckType.java:16)
	at magic.model.DuelPlayerConfig.setDeckProfile(DuelPlayerConfig.java:48)
	at magic.data.DuelConfig.loadPlayerConfigs(DuelConfig.java:106)
	at magic.data.DuelConfig.load(DuelConfig.java:99)
	at magic.data.DuelConfig.load(DuelConfig.java:120)
	at magic.ui.screen.duel.setup.NewDuelSettingsScreen.<init>(NewDuelSettingsScreen.java:44)
	at magic.ui.ScreenController.lambda$showNewDuelSettingsScreen$356(ScreenController.java:282)
	at magic.ui.ScreenController.showScreen(ScreenController.java:180)
	... 40 more
```
