### ISSUE TITLE
Exception on opening Deck Editor ("Unable to determine deck type...")

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1023]
```
CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
CREATED ON 2017/01/10 15:17:27
MAGARENA VERSION 1.81, JRE 1.8.0_101, OS Windows 7_6.1 x86
================================
Used Memory: 105M
Free Memory: 142M
Total Memory: 247M
Max Memory: 494M
================================
-Xms256m
-Xmx512m
-Xverify:none


Exception from controller.runGame: java.lang.RuntimeException: Unable to determine deck type from D:\MTG-Dev\magarena\Magarena-1.80\Magarena\decks\156981.dec
java.lang.RuntimeException: java.lang.RuntimeException: Unable to determine deck type from D:\MTG-Dev\magarena\Magarena-1.80\Magarena\decks\156981.dec
	at magic.ui.ScreenController.showScreen(ScreenController.java:178)
	at magic.ui.ScreenController.showDeckEditor(ScreenController.java:235)
	at magic.ui.screen.menu.main.MainMenuContentPanel.showDeckEditor(MainMenuContentPanel.java:69)
	at magic.ui.screen.menu.MenuScreenContentPanel$3.actionPerformed(MenuScreenContentPanel.java:55)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Unable to determine deck type from D:\MTG-Dev\magarena\Magarena-1.80\Magarena\decks\156981.dec
	at magic.utility.DeckUtils.getDeckType(DeckUtils.java:278)
	at magic.utility.DeckUtils.loadDeckFromFile(DeckUtils.java:292)
	at magic.ui.screen.deck.editor.DeckEditorScreen.tryLoadDeck(DeckEditorScreen.java:140)
	at magic.ui.screen.deck.editor.DeckEditorScreen.getMostRecentEditedDeck(DeckEditorScreen.java:130)
	at magic.ui.screen.deck.editor.DeckEditorScreen.<init>(DeckEditorScreen.java:69)
	at magic.ui.ScreenController.showScreen(ScreenController.java:176)
	... 40 more
```

**Comment by lodici** [comment]
Caused when opening Deck Editor for the first time after a new install and having imported settings from a previous version which has a non-null ``MostRecentDeckFilename`` property value in ``general.cfg``. The problem is that the fully qualified path to the deck file is stored. For example, running 1.81 and importing settings from 1.80 the ``MostRecentDeckFilename`` value in 1.81 is set to ``D\:\\MTG-Dev\\magarena\\Magarena-1.80\\Magarena\\decks\\156981.dec`` which is obviously pointing to the 1.80 version of the deck file. At the very least it should only be storing the relative path, but ideally it should just be the deck name and type from which Magarena can determine where to save/load the deck file.
