### ISSUE TITLE
CardViewer.setCard() NPE

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1082]
Getting the following exception every now and then when clicking on Select in DecksScreen and returning to the deck editor screen. Possibly something I have introduced with recent updates.

```
CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
CREATED ON 2017/02/24 02:58:25
MAGARENA VERSION 1.82, JRE 1.8.0_121, OS Windows 7_6.1 x86
================================
Used Memory: 85M
Free Memory: 53M
Total Memory: 139M
Max Memory: 494M
================================
-Dfile.encoding=UTF-8
-DjarFile=dist\magarena-github.jar
-DdevMode=true
-Dmagarena.dir=release
-ea
-Xmx512m


Exception from controller.runGame: null
java.lang.NullPointerException
	at magic.ui.widget.duel.viewer.CardViewer.setCard(CardViewer.java:136)
	at magic.ui.screen.deck.editor.DeckSideBar.setCard(DeckSideBar.java:61)
	at magic.ui.screen.deck.editor.ContentPanel.setCard(ContentPanel.java:59)
	at magic.ui.screen.deck.editor.ContentPanel.cardSelected(ContentPanel.java:106)
	at magic.ui.screen.deck.editor.MainViewsPanel.lambda$addPropertyChangeListeners$2(MainViewsPanel.java:164)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
	at java.awt.Component.firePropertyChange(Component.java:8448)
	at javax.swing.JComponent.firePropertyChange(JComponent.java:4491)
	at magic.ui.screen.deck.editor.DeckPanel$2.propertyChange(DeckPanel.java:88)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
	at java.awt.Component.firePropertyChange(Component.java:8448)
	at javax.swing.JComponent.firePropertyChange(JComponent.java:4491)
	at magic.ui.widget.cards.table.DeckTablePanel.lambda$getTableListSelectionListener$0(DeckTablePanel.java:58)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:154)
	at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:685)
	at javax.swing.JTable.clearSelectionAndLeadAnchor(JTable.java:2132)
	at javax.swing.JTable.tableChanged(JTable.java:4445)
	at magic.ui.widget.cards.table.DeckTablePanel.setDeck(DeckTablePanel.java:112)
	at magic.ui.screen.deck.editor.DeckPanel.doRefreshView(DeckPanel.java:139)
	at magic.ui.screen.deck.editor.MainViewsPanel.doRefreshViews(MainViewsPanel.java:235)
	at magic.ui.screen.deck.editor.ContentPanel.doRefreshView(ContentPanel.java:64)
	at magic.ui.screen.deck.editor.DeckEditorScreen.doRefreshViews(DeckEditorScreen.java:287)
	at magic.ui.screen.deck.editor.DeckEditorController.setDeck(DeckEditorController.java:27)
	at magic.ui.screen.deck.editor.DeckEditorScreen.setDeck(DeckEditorScreen.java:293)
	at magic.ui.screen.deck.editor.DeckEditorScreen.setDeck(DeckEditorScreen.java:309)
	at magic.ui.screen.decks.DecksScreen.doSelectDeck(DecksScreen.java:57)
	at magic.ui.screen.widget.MenuButton$5.actionPerformed(MenuButton.java:232)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by lodici** [comment]
To replicate: Open deck editor. Select PWL tab. Open decks screen. Click Select.
