### ISSUE TITLE
No enum constant magic.data.MagicSets.﻿AKH

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1152]
Introduced in bd74d64879742f6479ee1bfad228bc60413ff951. Open decks selection screen, select "2012Affinity" and click Select. Or maybe not, seems to occur most often when clicking on the Legality tab -
```
CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
CREATED ON 2017/06/18 16:34:48
MAGARENA VERSION 1.86, JRE 1.8.0_121, OS Windows 7_6.1 x86
================================
Used Memory: 88M
Free Memory: 57M
Total Memory: 145M
Max Memory: 494M
================================
-Dfile.encoding=UTF-8
-DjarFile=dist\magarena-github.jar
-Dmagarena.dir=release
-Xmx512m


Exception from controller.runGame: No enum constant magic.data.MagicSets.﻿AKH
java.lang.IllegalArgumentException: No enum constant magic.data.MagicSets.﻿AKH
	at java.lang.Enum.valueOf(Enum.java:238)
	at magic.data.MagicSets.valueOf(MagicSets.java:3)
	at magic.data.MagicPredefinedFormat.loadMagicFormatFile(MagicPredefinedFormat.java:126)
	at magic.data.MagicPredefinedFormat.getCardLegality(MagicPredefinedFormat.java:139)
	at magic.data.MagicFormat.isCardLegal(MagicFormat.java:22)
	at magic.data.MagicPredefinedFormat.isDeckLegal(MagicPredefinedFormat.java:167)
	at magic.ui.widget.deck.legality.FormatsLegalityPanel.getDeckFormatsLegality(FormatsLegalityPanel.java:105)
	at magic.ui.widget.deck.legality.FormatsLegalityPanel.setDeck(FormatsLegalityPanel.java:88)
	at magic.ui.widget.deck.legality.LegalityPanel.notifyShowing(LegalityPanel.java:121)
	at magic.ui.screen.deck.editor.MainViewsPanel.doRefreshViews(MainViewsPanel.java:259)
	at magic.ui.screen.deck.editor.ContentPanel.doRefreshView(ContentPanel.java:64)
	at magic.ui.screen.deck.editor.DeckEditorScreen.doRefreshViews(DeckEditorScreen.java:285)
	at magic.ui.screen.deck.editor.DeckEditorController.setDeck(DeckEditorController.java:27)
	at magic.ui.screen.deck.editor.DeckEditorScreen.setDeck(DeckEditorScreen.java:291)
	at magic.ui.screen.deck.editor.DeckEditorScreen.setDeck(DeckEditorScreen.java:307)
	at magic.ui.screen.decks.DecksScreen.doSelectDeck(DecksScreen.java:57)
	at magic.ui.screen.widget.MenuButton$5.actionPerformed(MenuButton.java:232)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by lodici** [comment]
It is due to a change in encoding introduced in bd74d64 where it went from ANSI to UTF-8. If UTF-8 it needs to be _UTF-8 without BOM_ but I am still not sure why it should get so upset with UTF-8 (with BOM).

**Comment by ShawnieBoy** [comment]
Thanks for catching that - my bad. I think notepad has changed how it displays with and without BOM (My excuse anyway!)

**Comment by lodici** [comment]
Yeah, I use notepad++ too. I find that even if I encode as ``utf8 without bom`` and save the file, when I next open it says it is ANSI which I am assuming is because there are no unicode characters. Magarena has no problem reading this but wish I knew why java has problems reading UTF-8 though.

**Comment by ShawnieBoy** [comment]
The latest version seems to not display `without BOM` if it doesn't have it, and only shows `with BOM`. I'm so used to seeing it refered in the negative, that I saw `BOM` and thought it was the `without BOM`. Ugh, confusing.

**Comment by melvinzhang** [comment]
I added BOM removal to one of the file normalization steps, so that it will be caught automatically.

**Comment by lodici** [comment]
@melvinzhang's solution is a more fool-proof solution I think but fyi (see https://stackoverflow.com/a/7390288/1385238), the Apache Commons IO library which Magarena is already using has a ``BOMInputStream`` that can read UTF-8 files, for example -
```java
public static InputStream getStream(final MagicPredefinedFormat magicFormat) {
    return new BOMInputStream(getJarResourceStream("/magic/data/formats/" + magicFormat.getFilename() + ".fmt"));
}
```
