### ISSUE TITLE
Throbber Crash?

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#1169]
On a first launch and going into Card Explorer, I'm usually getting this crash. Launching again doesn't crash.
```
Exception occurred in updating field 'angle' of object magic.ui.widget.throbber.ImageThrobber at timeline position 0.88249993
java.lang.RuntimeException: Unable to set the value of the field 'angle'
        at org.pushingpixels.trident.TimelinePropertyBuilder$DefaultPropertySetter.set(TimelinePropertyBuilder.java:75)
        at org.pushingpixels.trident.TimelinePropertyBuilder$GenericFieldInfo.updateFieldValue(TimelinePropertyBuilder.java:368)
        at org.pushingpixels.trident.Timeline$Setter.onTimelinePulse(Timeline.java:158)
        at org.pushingpixels.trident.Timeline$Chain.onTimelinePulse(Timeline.java:252)
        at org.pushingpixels.trident.TimelineEngine$2.run(TimelineEngine.java:559)
        at org.pushingpixels.trident.TimelineEngine$TimelineCallbackThread.run(TimelineEngine.java:215)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.pushingpixels.trident.TimelinePropertyBuilder$DefaultPropertySetter.set(TimelinePropertyBuilder.java:73)
        ... 5 more
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.awt.image.DataBufferInt.<init>(Unknown Source)
        at java.awt.image.Raster.createPackedRaster(Unknown Source)
        at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
        at java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
        at magic.ui.helpers.ImageHelper.getCompatibleBufferedImage(ImageHelper.java:161)
        at magic.ui.widget.throbber.AbstractThrobber.getNextFrameImage(AbstractThrobber.java:145)
        at magic.ui.widget.throbber.AbstractThrobber.paintNextFrame(AbstractThrobber.java:125)
        at magic.ui.widget.throbber.AbstractThrobber.setAngle(AbstractThrobber.java:116)
        ... 9 more
Exception occurred in updating field 'angle' of object magic.ui.widget.throbber.ImageThrobber at timeline position 0.9214999
java.lang.RuntimeException: Unable to set the value of the field 'angle'
        at org.pushingpixels.trident.TimelinePropertyBuilder$DefaultPropertySetter.set(TimelinePropertyBuilder.java:75)
        at org.pushingpixels.trident.TimelinePropertyBuilder$GenericFieldInfo.updateFieldValue(TimelinePropertyBuilder.java:368)
        at org.pushingpixels.trident.Timeline$Setter.onTimelinePulse(Timeline.java:158)
        at org.pushingpixels.trident.Timeline$Chain.onTimelinePulse(Timeline.java:252)
        at org.pushingpixels.trident.TimelineEngine$2.run(TimelineEngine.java:559)
        at org.pushingpixels.trident.TimelineEngine$TimelineCallbackThread.run(TimelineEngine.java:215)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.pushingpixels.trident.TimelinePropertyBuilder$DefaultPropertySetter.set(TimelinePropertyBuilder.java:73)
        ... 5 more
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.awt.image.DataBufferInt.<init>(Unknown Source)
        at java.awt.image.Raster.createPackedRaster(Unknown Source)
        at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
        at java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
        at magic.ui.helpers.ImageHelper.getCompatibleBufferedImage(ImageHelper.java:161)
        at magic.ui.widget.throbber.AbstractThrobber.getNextFrameImage(AbstractThrobber.java:145)
        at magic.ui.widget.throbber.AbstractThrobber.paintNextFrame(AbstractThrobber.java:125)
        at magic.ui.widget.throbber.AbstractThrobber.setAngle(AbstractThrobber.java:116)
        ... 9 more
```

**Comment by lodici** [comment]
Thanks, I have had this a couple of times over the last year or so but keep forgetting to log it. Hard to replicate unfortunately.

**Comment by ShawnieBoy** [comment]
No probs. If it makes any difference, it's normally not the active window when it freezes. It takes a while for the errors to start occuring.

**Comment by melvinzhang** [comment]
The main issue seems to be an OOM, this causes setAngle to throw OOM and the Timeline to rethrow it as "Unable to set value".

**Comment by lodici** [comment]
I have worked out how to replicate fairly regularly. I run with ``-Xmx128m`` and use [SysInternals RamMap](https://technet.microsoft.com/en-us/sysinternals/rammap.aspx) (Windows only) beforehand to call the "Empty Standby List" option. When opening the Explorer screen, more often than not the error will be generated.

**Comment by lodici** [comment]
5370a73c4765ad879802502b16a2ba43b41b2c1f fixes the fact that throbber instances continued animating away even when not shown in the UI - don't think it is the cause of this error but it cannot have helped.

**Comment by ShawnieBoy** [comment]
I'm running with `-Xms256M -Xmx1g` guess those 24m make all the difference 😀

**Comment by lodici** [comment]
Real developers think in Megs! :neckbeard: 🤘

**Comment by lodici** [comment]
For some reason 63beb3c689513a1b04280be1aca12109df0bfda7 seems to fix this issue, at least the steps to replicate as described above consistently fail on the previous commit but have yet to do so on 63beb3c689513a1b04280be1aca12109df0bfda7 despite many attempts. However it is not clear to me why updating the layout code should have such an affect so I will leave this open for now.
