### ISSUE TITLE
NPE in CardViewer.getCardImage().

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1186]
Got the following exception on clicking on "Resume duel" in the main menu screen. Have not been able to replicate. Was in a dev build so possibly related to current development. Even so CardViewer just displays an image in the sidebar so is not critical functionality and therefore could fail more gracefully on null.

```
CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
CREATED ON 2017/07/12 09:17:05
MAGARENA VERSION 1.87, JRE 1.8.0_121, OS Windows 7_6.1 x86
================================
Used Memory: 127M
Free Memory: 120M
Total Memory: 247M
Max Memory: 494M
================================
-Dfile.encoding=UTF-8
-Dmagarena.dir=release
-DjarFile=distmagarena-github.jar
-Djava.util.logging.config.file=local.config\logger.config
-Xms256M
-Xmx512M


Turn : 1  Phase : Mulligan  Step : Begin  Player : antec  AI : monte carlo tree search  Score : 0
0] Player : antec  Life : 20  Delayed : Total=0
   - Hand : Forest
   - Hand : Forest
   - Hand : Forest
   - Hand : Forest
   - Hand : Giant Growth
   - Hand : Overrun
   - Hand : Forest
   - Library : Forest
   - Library : Forest
   - Library : Forest
   - Library : Forest
   - Library : Harmonize
   - Library : Mirri, Cat Warrior
   - Library : Overrun
1] Player : Monty Carlo  Life : 20  Delayed : Total=0
   - Hand : Myr Galvanizer
   - Hand : Plains
   - Hand : Plains
   - Hand : Darksteel Forge
   - Hand : Plains
   - Hand : Hovermyr
   - Hand : Darksteel Myr
   - Library : Darksteel Forge
   - Library : Spidersilk Net
   - Library : Arcbound Crusher
   - Library : Glorious Anthem
   - Library : Plains
   - Library : Gold Myr
   - Library : Steel Overseer
Stack : 0
Score = 0

Exception from controller.runGame: java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at magic.ui.widget.duel.viewer.CardImageWorker.getImage(CardImageWorker.java:72)
	at magic.ui.widget.duel.viewer.CardImageWorker.done(CardImageWorker.java:48)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at javax.swing.SwingWorker.get(SwingWorker.java:602)
	at magic.ui.widget.duel.viewer.CardImageWorker.getImage(CardImageWorker.java:64)
	... 21 more
Caused by: java.lang.NullPointerException
	at magic.ui.widget.duel.viewer.CardViewer.getCardImage(CardViewer.java:224)
	at magic.ui.widget.duel.viewer.CardImageWorker.doInBackground(CardImageWorker.java:39)
	at magic.ui.widget.duel.viewer.CardImageWorker.doInBackground(CardImageWorker.java:16)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
'''

**Comment by melvinzhang** [comment]
Looks like this is due to the corrupted card image, where null is returned by getOptimizedImage. Fixed in  69a3b6d13bce
