### ISSUE TITLE
magic.model.MagicCard cannot be cast to magic.model.MagicPermanent

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1204]
Suddenly getting alot of these errors on CircelCI.
```
Exception from controller.runGame: magic.model.MagicCard cannot be cast to magic.model.MagicPermanent
java.lang.ClassCastException: magic.model.MagicCard cannot be cast to magic.model.MagicPermanent
	at magic.model.target.MagicCopyPermanentPicker.getTargetScore(MagicCopyPermanentPicker.java:7)
	at magic.model.target.MagicTargetPicker.pickTargets(MagicTargetPicker.java:30)
	at magic.model.choice.MagicTargetChoice.getArtificialOptions(MagicTargetChoice.java:458)
	at magic.model.choice.MagicMayChoice.getArtificialChoiceResults(MagicMayChoice.java:130)
	at magic.model.choice.MagicChoice.getSimulationChoiceResult(MagicChoice.java:115)
	at magic.model.event.MagicEvent.getSimulationChoiceResult(MagicEvent.java:430)
	at magic.ai.MCTSAI.runSimulation(MCTSAI.java:480)
	at magic.ai.MCTSAI.randomPlay(MCTSAI.java:443)
	at magic.ai.MCTSAI.access$000(MCTSAI.java:63)
	at magic.ai.MCTSAI$2.run(MCTSAI.java:185)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by melvinzhang** [comment]
Thanks for heads up. It is due to changing the card 'Body Double' to card
script, but the card script parser assumes only permanents can be chosen.
I'll work on a fix, most likely by reverting the card back to groovy code.
