### ISSUE TITLE
MCTSAI.outputChoice IndexOutOfBoundsException

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#127]
Running latest build from IDE playing this [saved game file](https://gist.github.com/lodici/494c77b366d464cc28f2#file-_prevent-damage-game).

![crash](https://cloud.githubusercontent.com/assets/2443519/6856296/05679402-d3f7-11e4-9303-0611a07d27af.png)

```
CRASH REPORT FOR MAGARENA THREAD Thread[Thread-9,1,main]
CREATED ON 2015/03/26 20:23:13
MAGARENA VERSION 1.60, JRE 1.7.0_65, OS Windows 7_6.1 amd64
================================
Used Memory: 195M
Free Memory: 619M
Total Memory: 814M
Max Memory: 1819M
================================
-Dfile.encoding=UTF-8
-Dmagarena.dir=D:\_DATA\Java\NetBeansProjects\magarena-github\release
-ea
-DdevMode=true


Turn : 2  Phase : FirstMain  Step : ActivePlayer  Player : Monty Carlo  Score : 820
0] Player : SPR  Life : 10  Delayed : Total=0
   - Hand : Plains
   - Hand : Plains
   - Hand : Forest
   - Hand : Sphere of Purity
   - Graveyard : Flowering Field
   - Permanent : Forest  Tapped
   - Permanent : Orim, Samite Healer  Power : 1  Toughness : 3  Damage : 0  Summoned
   - Permanent : Plains  Tapped
   - Permanent : Plains  Tapped  Summoned
1] Player : Monty Carlo  Life : 10  Delayed : Total=0
   - Hand : Cystbearer
   - Hand : Inkmoth Nexus
   - Hand : Mutagenic Growth
   - Hand : Mutagenic Growth
   - Hand : Rancor
   - Hand : Titanic Growth
   - Hand : Ichorclaw Myr
   - Permanent : Forest
   - Permanent : Forest
Stack : 0
1.  (Plains) = 680
2.  (Flowering Field) = 510
3.  (Forest) = 717
4.  (Forest) = -717
5.  (Forest) = -717
6. MagicRemoveFromPlayAction (Flowering Field,0) = -505
7. MagicRemoveFromCombatAction (Flowering Field) = 0
8. MagicMoveCardAction (Flowering Field,Play,Graveyard) = 0
9. MagicRemoveTriggersStaticsAction = 0
10. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
11. MagicMarkerAction = 0
12. MagicLogMarkerAction = 0
13. MagicExecuteFirstEventAction = 0
14. MagicAddEventAction (EVENT: Plains Play Plains. ) = 0
15. MagicExecuteFirstEventAction = 0
16. MagicRemoveCardAction (Plains) = -375
17. MagicPlayCardAction = 0
18. MagicAddEventAction (EVENT: Plains Put Plains onto the battlefield. ) = 0
19. MagicExecuteFirstEventAction = 0
20. MagicPlayCardFromStackAction (Plains) = 680
21. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
22. MagicMarkerAction = 0
23. MagicLogMarkerAction = 0
24. MagicExecuteFirstEventAction = 0
25. MagicAddEventAction (EVENT: Orim, Samite Healer Pay {1}{W}{W}$. Choose how to pay the mana cost.) = 0
26. MagicAddEventAction (EVENT: Orim, Samite Healer Play Orim, Samite Healer. ) = 0
27. MagicTapAction (Plains) = -5
28. MagicTapAction (Plains) = -5
29. MagicTapAction (Forest) = -5
30. MagicExecuteFirstEventAction = 0
31. MagicExecuteFirstEventAction = 0
32. MagicRemoveCardAction (Orim, Samite Healer) = -315
33. MagicPutItemOnStackAction (MagicCardOnStack,Orim, Samite Healer) = -1
34. MagicAddEventAction (EVENT: Orim, Samite Healer  ) = 0
35. MagicExecuteFirstEventAction = 0
36. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
37. MagicExecuteFirstEventAction = 0
38. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
39. MagicExecuteFirstEventAction = 0
40. MagicStackResolveAction = 0
41. MagicPlayCardFromStackAction (Orim, Samite Healer) = 1270
42. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
43. MagicExecuteFirstEventAction = 0
44. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
45. MagicExecuteFirstEventAction = 0
46. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
47. MagicExecuteFirstEventAction = 0
48. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
49. MagicExecuteFirstEventAction = 0
50. MagicAddEventAction (EVENT: NONE  Declare attackers.) = 0
51. MagicExecuteFirstEventAction = 0
52. MagicDeclareAttackersAction = 0
53. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
54. MagicExecuteFirstEventAction = 0
55. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
56. MagicExecuteFirstEventAction = 0
57. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
58. MagicExecuteFirstEventAction = 0
59. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
60. MagicExecuteFirstEventAction = 0
61. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
62. MagicExecuteFirstEventAction = 0
63. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
64. MagicExecuteFirstEventAction = 0
65. MagicReturnExiledAction = 0
66. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
67. MagicExecuteFirstEventAction = 0
68. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
69. MagicExecuteFirstEventAction = 0
70. MagicCleanupTurnTriggersAction = 0
71. MagicCleanupPlayerAction = 0
72. MagicCleanupPermanentAction = 0
73. MagicCleanupCreatureAction = 0
74. MagicCleanupPermanentAction = 0
75. MagicCleanupPermanentAction = 0
76. MagicCleanupPlayerAction = 0
77. MagicCleanupPermanentAction = 0
78. MagicCleanupPermanentAction = 0
79. MagicCleanupTurnStaticsAction = 0
80. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
81. MagicExecuteFirstEventAction = 0
82. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
83. MagicExecuteFirstEventAction = 0
84. MagicDrawAction = -389
85. MagicAddEventAction (EVENT: NONE  ...) = 0
86. MagicExecuteFirstEventAction = 0
87. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
88. MagicExecuteFirstEventAction = 0
89. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
90. MagicExecuteFirstEventAction = 0
91. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
Score = 823

Exception from controller.runGame: Index: 2, Size: 2
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at magic.ai.MCTSAI.outputChoice(MCTSAI.java:334)
	at magic.ai.MCTSAI.findNextEventChoiceResults(MCTSAI.java:175)
	at magic.ui.SwingGameController.getArtificialNextEventChoiceResults(SwingGameController.java:572)
	at magic.ui.SwingGameController.executeNextEventWithChoices(SwingGameController.java:591)
	at magic.ui.SwingGameController.executeNextEvent(SwingGameController.java:721)
	at magic.ui.SwingGameController.executeNextEventOrPhase(SwingGameController.java:709)
	at magic.ui.SwingGameController.runGame(SwingGameController.java:653)
	at magic.ui.duel.DuelPanel$2$1.run(DuelPanel.java:129)
```

**Comment by lodici** [comment]
I am testing with the same saved game doing the same thing each time but have not been able to replicate the error.

**Comment by melvinzhang** [comment]
Have not observed this for last few releases, considering it resolved.
