### ISSUE TITLE
Constant crashing. 1.88 card images not downloading correctly.

### ISSUE THREAD

**Issue by Carnagehunts** [magarena/magarena#1325]
#### Crash report
CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
CREATED ON 2017/09/18 20:46:03
MAGARENA VERSION 1.88, JRE 1.8.0_144, OS Windows 7_6.1 amd64
================================
Used Memory: 138M
Free Memory: 167M
Total Memory: 306M
Max Memory: 455M
================================
-Xms256m
-Xmx512m
-Xverify:none

Exception from controller.runGame: java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at magic.ui.widget.duel.viewer.CardImageWorker.getImage(CardImageWorker.java:72)
	at magic.ui.widget.duel.viewer.CardImageWorker.done(CardImageWorker.java:48)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at javax.swing.SwingWorker.get(Unknown Source)
	at magic.ui.widget.duel.viewer.CardImageWorker.getImage(CardImageWorker.java:64)
	... 21 more
Caused by: java.lang.NullPointerException
	at magic.ui.widget.duel.viewer.CardViewer.getCardImage(CardViewer.java:224)
	at magic.ui.widget.duel.viewer.CardImageWorker.doInBackground(CardImageWorker.java:39)
	at magic.ui.widget.duel.viewer.CardImageWorker.doInBackground(CardImageWorker.java:16)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
CREATED ON 2017/09/18 22:37:21
MAGARENA VERSION 1.88, JRE 1.8.0_144, OS Windows 7_6.1 amd64
================================
Used Memory: 71M
Free Memory: 300M
Total Memory: 371M
Max Memory: 455M
================================
-Xms256m
-Xmx512m
-Xverify:none

Turn : 1  Phase : Mulligan  Step : Begin  Player : Monty Carlo  AI : monte carlo tree search  Score : 0
0] Player : Pifen  Life : 20  Delayed : Total=0
1] Player : Monty Carlo  Life : 20  Delayed : Total=0
Stack : 0
Score = 0

Exception from controller.runGame: java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at magic.ui.widget.duel.viewer.CardImageWorker.getImage(CardImageWorker.java:72)
	at magic.ui.widget.duel.viewer.CardImageWorker.done(CardImageWorker.java:48)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at javax.swing.SwingWorker.get(Unknown Source)
	at magic.ui.widget.duel.viewer.CardImageWorker.getImage(CardImageWorker.java:64)
	... 21 more
Caused by: java.lang.NullPointerException
	at magic.ui.widget.duel.viewer.CardViewer.getCardImage(CardViewer.java:224)
	at magic.ui.widget.duel.viewer.CardImageWorker.doInBackground(CardImageWorker.java:39)
	at magic.ui.widget.duel.viewer.CardImageWorker.doInBackground(CardImageWorker.java:16)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

#### Gameplay report
I can't play this game. Just tried today to play, downloaded images and most images are corrupted or just incorrect and if I go to card explore or even just new duel as soon as card menu appears it crashes instantly. Is there any solution to this? I've looked online if there was at least a download version with cards preinstalled so I don't have to go through this but none exist. Really interested in playing. Please Help.

---

**Comment by ShawnieBoy** [comment]
Sorry that you've encountered this bug - some unforeseen issues with the image sources.
A workaround for this issue is to set the card display from printed to rendered proxy #1318

**Comment by melvinzhang** [comment]
Duplicate of #1318. Found the cause of the exception, fix incoming.

**Comment by melvinzhang** [comment]
@Carnagehunts we have patched the 1.88 zip files with the fix. If you redownload a new copy from https://github.com/magarena/magarena/releases/tag/1.88 you will get a fixed copy.
