### ISSUE TITLE
Michiko Konda, Truth Seeker (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1377]
[Michiko_Konda__Truth_Seeker.zip](https://github.com/magarena/magarena/files/1908452/Michiko_Konda__Truth_Seeker.zip)

**Comment by bilbo2** [comment]
Seems to be cause for a crash when testing with this card:

3747. DequeueTriggerAction = 0
3748. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
3749. ExecuteFirstEventAction = 0
3750. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
3751. ExecuteFirstEventAction = 0
3752. StackResolveAction = 0
3753. AddEventAction (EVENT: bilbo Sacrifice a permanent to sacrifice$. Choose a permanent to sacrifice.) = 0
Score = -5015

```
Exception from controller.runGame: player has no card definition
java.lang.RuntimeException: player has no card definition
        at magic.model.MagicPlayer.getCardDefinition(MagicPlayer.java:756)
        at magic.ui.screen.duel.game.SwingGameController.setSourceCardDefinition(SwingGameController.java:465)
        at magic.ui.screen.duel.game.SwingGameController.getPlayerNextEventChoiceResults(SwingGameController.java:640)
        at magic.ui.screen.duel.game.SwingGameController.executeNextEventWithChoices(SwingGameController.java:661)
        at magic.ui.screen.duel.game.SwingGameController.executeNextEvent(SwingGameController.java:768)
        at magic.ui.screen.duel.game.SwingGameController.executeNextEventOrPhase(SwingGameController.java:756)
        at magic.ui.screen.duel.game.SwingGameController.runGame(SwingGameController.java:720)
        at magic.ui.screen.duel.game.DuelGameScreen$1.run(DuelGameScreen.java:51)

```

**Comment by bilbo2** [comment]
Full log:
[michiko.zip](https://github.com/magarena/magarena/files/1835677/michiko.zip)

**Comment by kelsioboy** [comment]
Thanks @bilbo2  I have managed to reproduce the problem, it has already been fixed and I have repacked the old groovy with the new one.

**Comment by melvinzhang** [comment]
Merged
