### ISSUE TITLE
crash when playing Supernatural Stamina

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1416]
Play Supernatural Stamina targeting your own creature results in a crash:
```
Exception from controller.runGame: java.lang.NullPointerException
magic.exception.GameException: java.lang.NullPointerException
        at magic.model.MagicGame.doAction(MagicGame.java:565)
        at magic.model.phase.MagicPhase.executePhase(MagicPhase.java:43)
        at magic.model.MagicGame.executePhase(MagicGame.java:476)
        at magic.ui.screen.duel.game.SwingGameController.executeNextEventOrPhase(SwingGameController.java:758)
        at magic.ui.screen.duel.game.SwingGameController.runGame(SwingGameController.java:720)
        at magic.ui.screen.duel.game.DuelGameScreen$1.run(DuelGameScreen.java:51)
Caused by: java.lang.NullPointerException
        at magic.model.ARG.wordrun(ARG.java:101)
        at magic.model.MagicAbility$152.addAbilityImpl(MagicAbility.java:1268)
        at magic.model.MagicAbility.addAbility(MagicAbility.java:1824)
        at magic.model.MagicAbility.getAbilityList(MagicAbility.java:1881)
        at magic.model.action.GainAbilityAction.<init>(GainAbilityAction.java:29)
        at magic.model.action.GainAbilityAction.<init>(GainAbilityAction.java:49)
        at Supernatural_Stamina$1$_executeEvent_closure1.doCall(Supernatural_Stamina.groovy:19)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
        at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
        at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
        at com.sun.proxy.$Proxy11.doAction(Unknown Source)
        at magic.model.event.MagicEvent.processTargetPermanent(MagicEvent.java:621)
        at Supernatural_Stamina$1.executeEvent(Supernatural_Stamina.groovy:17)
        at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:726)
        at magic.model.MagicGame.executeEvent(MagicGame.java:796)
        at magic.model.stack.MagicItemOnStack.resolve(MagicItemOnStack.java:130)
        at magic.model.stack.MagicCardOnStack.resolve(MagicCardOnStack.java:113)
        at magic.model.action.StackResolveAction.doAction(StackResolveAction.java:13)
        at magic.model.MagicGame.doAction(MagicGame.java:563)
        ... 5 more
```

**Comment by melvinzhang** [comment]
@Fulmene it should be using getAbilityList, but there is a limitation with getAbilityList to parse this ability. I'll look into it.

**Comment by melvinzhang** [comment]
It can be fixed to use getAbilityList when the ability line is quoted to prevent getAbilityList from breaking it up. Eg. ` MagicAbility.getAbilityList("\"When SN dies, return SN from the graveyard to the battlefield tapped under its owner's control.\"");`

However, this ability cannot be parsed, this is the reason the card requires groovy code. Groovy code is needed to implement "When SN dies, return it to the battlefield tapped under its owner's control."

@Fulmene the ability needs to be coded out in groovy, it is not supported by the ability parsing. Are you able to write the groovy version of this? If not, perhaps we leave this card out first.

**Comment by melvinzhang** [comment]
A similar card with a similar effect and has the groovy code is https://github.com/magarena/magarena/blob/f47b0268990a424d02f2bbdad1199403b8267648/release/Magarena/scripts/Ashcloud_Phoenix.groovy

**Comment by melvinzhang** [comment]
Use AddTriggerAction to associate the dies trigger to the target of Supernatural Stamina.

**Comment by Fulmene** [comment]
I tried at first but couldn't figure out how to reanimate with MagicPermanent, so I resorted to getAbility. Implementing it now.

**Comment by melvinzhang** [comment]
Tested in a small test game. Works tell, the trigger fires and the creature comes back into play when it is destroyed.
