### ISSUE TITLE
Unexpected Results (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1481]
[Unexpected_Results.zip](https://github.com/magarena/magarena/files/1754541/Unexpected_Results.zip)

**Comment by bilbo2** [comment]
I've tried this, but it has two glitches:

When asking about whether to cast the card without paying the cost, it does not shop preview of what are you going to cast. The preview shows the "Unexpected Results" card, i.e. source of the event.

It seems also to cause crashes (Monte carlo getting confused by some situations?) right at start of the game, although I am not sure whether this card is the cause (I am testing more new cards at once). This would need more investigation. After the crash, I got log + stacktrace:

```
5326. ShuffleLibraryAction = 0
5327. RevealAction = 0
5328. AIRevealAction = 0
5329. AddEventAction (EVENT: NONE   reveals <NONE~0>.) = 0
5330. AddEventAction (EVENT: Unexpected Results If it's a nonland card, bilbo may$ cast it without paying its mana cost. Cast NONE without paying its mana cost?) = 0
5331. MoveCardAction (Unexpected Results,Stack,Graveyard) = 0
5332. ExecuteFirstEventAction = 0
5333. ExecuteFirstEventAction = 0
5334. CastCardAction (bilbo,NONE) = 0
Score = -10044

Exception from controller.runGame: magic.exception.GameException: java.lang.RuntimeException: getGame called for MagicPlayer.NONE
magic.exception.GameException: magic.exception.GameException: java.lang.RuntimeException: getGame called for MagicPlayer.NONE
        at magic.model.MagicGame.doAction(MagicGame.java:565)
        at magic.model.MagicGame.executeNextEvent(MagicGame.java:865)
        at magic.ai.MCTSAI.runSimulation(MCTSAI.java:482)
        at magic.ai.MCTSAI.randomPlay(MCTSAI.java:443)
        at magic.ai.MCTSAI.access$000(MCTSAI.java:63)
        at magic.ai.MCTSAI$2.run(MCTSAI.java:185)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: magic.exception.GameException: java.lang.RuntimeException: getGame called for MagicPlayer.NONE
        at magic.model.MagicGame.doAction(MagicGame.java:565)
        at Unexpected_Results$_run_closure1.doCall(Unexpected_Results.groovy:4)
        at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
        at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
        at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
        at com.sun.proxy.$Proxy13.executeEvent(Unknown Source)
        at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:726)
        at magic.model.MagicGame.executeEvent(MagicGame.java:796)
        at magic.model.action.ExecuteFirstEventAction.doAction(ExecuteFirstEventAction.java:18)
        at magic.model.MagicGame.doAction(MagicGame.java:563)
        ... 8 more
Caused by: java.lang.RuntimeException: getGame called for MagicPlayer.NONE
        at magic.model.MagicPlayer$1.getGame(MagicPlayer.java:42)
        at magic.model.MagicCard.getGame(MagicCard.java:453)
        at magic.model.event.MagicPayManaCostEvent.Cast(MagicPayManaCostEvent.java:16)
        at magic.model.MagicCardDefinition.getCostEvent(MagicCardDefinition.java:724)
        at magic.model.MagicCardDefinition.getWithoutManaCostEvent(MagicCardDefinition.java:718)
        at magic.model.MagicCard.getWithoutManaCostEvent(MagicCard.java:232)
        at magic.model.action.CastCardAction.doAction(CastCardAction.java:42)
        at magic.model.MagicGame.doAction(MagicGame.java:563)

```

**Comment by melvinzhang** [comment]
The bug here is caused by using getCardAtTop(), it could return MagicCard.NONE when the library is empty. The correct pattern is to use getCardsFromTop(1) and loop over the potential card.

**Comment by kelsioboy** [comment]
Hi guys, I reviewed the groovy as the @melvinzhang  said, please test again.

**Comment by bilbo2** [comment]
Tested, seems there is bug with current version that if you use the second mode (revealed card happens to be land, so you put it into play and take this card back to hand), the card duplicates itself and ends in both your hand and the library (it can appear even multiple times in your graveyard if you reveal more lands with consecutive casts).
