### ISSUE TITLE
able to cast unpayable card

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1491]
Similar to #226 which was for activating abilities.

For example, Player with 2 life, mana source with "Pay 1 life: add {C} on the field" and card with casting cost of "{X}, Pay 2 life".

Player is able to cast the spell though it is impossible to pay the cost. Player will first pay 2 life, then become unable to generate at least one mana to pay {X} as the mana source requires life payment.

**Comment by melvinzhang** [comment]
When the MCTS AI encounters this situation it results in a crash. It should result in a game loss instead as per other cases of reaching unpayable mana.
```
Exception from controller.runGame: Unable to pay for {X} in {X} as maxX = 0
magic.exception.GameException: Unable to pay for {X} in {X} as maxX = 0
	at magic.model.choice.MagicPayManaCostChoice.buildDelayedPayManaCostResults(MagicPayManaCostChoice.java:60)
	at magic.model.choice.MagicPayManaCostChoice.getSimulationChoiceResult(MagicPayManaCostChoice.java:97)
	at magic.model.event.MagicEvent.getSimulationChoiceResult(MagicEvent.java:420)
	at magic.ai.MCTSAI.runSimulation(MCTSAI.java:480)
	at magic.ai.MCTSAI.randomPlay(MCTSAI.java:443)
	at magic.ai.MCTSAI.access$000(MCTSAI.java:63)
	at magic.ai.MCTSAI$2.run(MCTSAI.java:185)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by melvinzhang** [comment]
To step test case, use Kozilek's Translator for mana source, and Corrosive Gale as card to cast.

**Comment by Phoenixton** [comment]
Hi!

I would like to look into this issue, but I have a non-code related question first: your original post, and my own experiment with Magarena, imply that it is illegal to cast an X spell with X=0. However, that isn't consistent with the rules of paper Magic as I remember them. Here, for instance, it should be entirely possible to cast Corrosive Gale with X=0, it would just do 0 damage. Did you (collectively) decide to prohibit players from casting X spells with X=0 for convenience's sake? Thing is, while it doesn't change anything in many instances (there are very few reasons to ever cast Corrosive Gale for 0), it does dramatically affect other cards, such as Chalice of the Void, which can no longer be set to 0 to counter 0-cost spells (which is one of the card's main uses).

Thanks a bunch!

**Comment by melvinzhang** [comment]
@Phoenixton welcome and thanks for looking into this issue.

> Did you (collectively) decide to prohibit players from casting X spells with X=0 for convenience's sake?

It was in the code-base when ubeefx open sourced it. My best guess is that it is there to avoid bad plays from the AI and to reduce the number of options the AI needs to consider for {X}. For symmetry, we also impose this on the player.

In general, we do try to follow the paper Magic rules, but as our focus is on AI, we will alter the rules to make the AI matchup more challenging. See https://github.com/magarena/magarena/wiki/GameRules for the major rules changes.
