### ISSUE TITLE
Chain Lightning causes Index out of bounds in MagicEvent.clearTargetChoice

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#150]
```
Turn : 10  Phase : SecondMain  Step : ActivePlayer  Player : minimax (cheat)  Score : 1998
0] Player : minimax (cheat)  Life : 7  Delayed : Total=0
   - Hand : Boros Guildgate
   - Hand : Gold-Forged Sentinel
   - Hand : Abzan Skycaptain
   - Hand : Thatcher Revolt
   - Graveyard : Crimson Manticore
   - Graveyard : Origin Spellbomb
   - Graveyard : Chain Lightning
   - Permanent : Myr  Power : 1  Toughness : 1  Damage : 0  Tapped
   - Permanent : Battered Golem  Power : 3  Toughness : 2  Damage : 0  Tapped
   - Permanent : Boros Guildgate
   - Permanent : Plains
   - Permanent : Plains
   - Permanent : Sacred Foundry  Tapped
   - Permanent : Scuzzback Scrapper  Power : 1  Toughness : 1  Damage : 0  Tapped
   - Permanent : Warmth
1] Player : monte carlo tree search  Life : -1  Delayed : Red=2 Total=2
   - Hand : Phantasmal Forces
   - Hand : Goblin Bushwhacker
   - Hand : Twincast
   - Hand : Island
   - Hand : Island
   - Graveyard : Ray of Erasure
   - Graveyard : Riptide Pilferer
   - Permanent : Island
   - Permanent : Mana Confluence
   - Permanent : Mountain
   - Permanent : Sulfur Falls
   - Permanent : Thalakos Sentry  Power : 1  Toughness : 2  Damage : 0  Tapped
Stack : 1
   - Name : Chain Lightning  Player : monte carlo tree search
1. MagicMarkerAction = 0
2. MagicExecuteFirstEventAction = 0
3. MagicExecuteFirstEventAction = 0
4. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
5. MagicExecuteFirstEventAction = 0
6. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
7. MagicMarkerAction = 0
8. MagicExecuteFirstEventAction = 0
9. MagicStackResolveAction = 0
10. MagicDealDamageAction = 0
11. MagicChangeLifeAction (monte carlo tree search,-3) = 2000
12. MagicChangePlayerStateAction = 0
13. MagicChangePlayerStateAction = 0
14. MagicAddEventAction (EVENT: Chain Lightning monte carlo tree search may$ pay {R}{R}$. If that player does, he or she may copy this spell and may choose a new target for that copy. Pay {R}{R}?) = 0
15. MagicMoveCardAction (Chain Lightning,Stack,Graveyard) = 0
16. MagicMarkerAction = 0
17. MagicExecuteFirstEventAction = 0
18. MagicPayDelayedCostAction = 0
19. MagicCopyCardOnStackAction (Chain Lightning) = 0
Score = 2000

Exception from controller.runGame: magic.exception.GameException: java.lang.ArrayIndexOutOfBoundsException: 0
magic.exception.GameException: magic.exception.GameException: java.lang.ArrayIndexOutOfBoundsException: 0
        at magic.model.MagicGame.doAction(MagicGame.java:530)
        at magic.model.MagicGame.executeNextEvent(MagicGame.java:781)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:168)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
        at magic.ai.MMAB$MMABWorker.evaluateGame(MMAB.java:260)
        at magic.ai.MMAB$1.run(MMAB.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: magic.exception.GameException: java.lang.ArrayIndexOutOfBoundsException: 0
        at magic.model.MagicGame.doAction(MagicGame.java:530)
        at Chain_Lightning$_run_closure1.doCall(Chain_Lightning.groovy:5)
        at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.Closure.call(Closure.java:423)
        at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:51)
        at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:103)
        at com.sun.proxy.$Proxy13.executeEvent(Unknown Source)
        at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:668)
        at magic.model.MagicGame.executeEvent(MagicGame.java:724)
        at magic.model.action.MagicExecuteFirstEventAction.doAction(MagicExecuteFirstEventAction.java:18)
        at magic.model.MagicGame.doAction(MagicGame.java:528)
        ... 9 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at magic.model.event.MagicEvent.clearTargetChoice(MagicEvent.java:432)
        at magic.model.action.MagicCopyCardOnStackAction.doAction(MagicCopyCardOnStackAction.java:23)
        at magic.model.MagicGame.doAction(MagicGame.java:528)
        ... 25 more
```

**Comment by ShawnieBoy** [comment]
That's strange, I'll have a look at what's going on.

**Comment by ShawnieBoy** [comment]
Is there a game log with this? It looks like there's nothing on the stack for Chain Lightning to copy.

**Comment by melvinzhang** [comment]
There isn't, Chain Lightning copies an internal copy of the card on stack which it gets from event.getCardOnStack().

**Comment by melvinzhang** [comment]
It looks like choiceResults is the default value of MagicEvent.NO_CHOICE_RESULTS, hence when MagicCopyCardOnStackAction tries to clear the target choice (which should be index 0 of choiceResults) it fails with "index out of bound" exception.

**Comment by ShawnieBoy** [comment]
That's weird, as I never had this pop up when testing it - I was assuming it was due to a particular card interaction or play-state

**Comment by ShawnieBoy** [comment]
Try as I might, I can't duplicate this

**Comment by melvinzhang** [comment]
Unable to replicate.
