### ISSUE TITLE
1.94 doesn't start on Windows 10_10.0 using JRE 1.8.0_181

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1617]
Submitter: MAGARENA VERSION 1.94, JRE 1.8.0_181, OS Windows 10_10.0 amd64   
Email: bpoplar@roadrunner.com
WONT START

 WON'T START

**Comment by melvinzhang** [comment]
similar crash reported on forum with the following crash.log
```
CRASH REPORT FOR MAGARENA THREAD Thread[main,5,main]
CREATED ON 2018/10/31 17:37:15
MAGARENA VERSION 1.94, JRE 1.8.0_161, OS Windows 7_6.1 x86
================================
Used Memory: 7M
Free Memory: 240M
Total Memory: 247M
Max Memory: 494M
================================
-Xms256m
-Xmx512m
-Xverify:none


Exception from controller.runGame: null
java.lang.ExceptionInInitializerError
	at magic.ui.theme.AbstractTheme.<init>(AbstractTheme.java:27)
	at magic.ui.theme.CustomTheme.<init>(CustomTheme.java:30)
	at magic.ui.theme.CustomTheme.loadTheme(CustomTheme.java:152)
	at magic.ui.theme.ThemeFactory.loadTheme(ThemeFactory.java:64)
	at magic.ui.theme.ThemeFactory.setCurrentTheme(ThemeFactory.java:75)
	at magic.ui.theme.ThemeFactory.loadThemes(ThemeFactory.java:24)
	at magic.ui.theme.ThemeFactory.<init>(ThemeFactory.java:20)
	at magic.ui.theme.ThemeFactory.<clinit>(ThemeFactory.java:15)
	at magic.ui.utility.MagicStyle.getTheme(MagicStyle.java:57)
	at magic.ui.widget.cards.table.CardsTableStyle.<clinit>(CardsTableStyle.java:11)
	at magic.data.GeneralConfig.load(GeneralConfig.java:108)
	at magic.utility.MagicSystem.initialize(MagicSystem.java:186)
	at magic.MagicMain.main(MagicMain.java:66)
Caused by: java.lang.NullPointerException
	at magic.ui.MagicImages.getPreferredImageSize(MagicImages.java:79)
	at magic.ui.MagicImages.<clinit>(MagicImages.java:35)
	... 13 more
```

**Comment by melvinzhang** [comment]
looks like it is due to using getResource and trying to open the URL as a File. A better way is to use getResourceAsStream

**Comment by melvinzhang** [comment]
forum report is confirmed to be a case of https://bugs.java.com/view_bug.do?bug_id=4523159 The install directory under a directory named `MTG!`. Use getResourceAsStream does not help in this case as it will return null.
