### ISSUE TITLE
infinite loop during MagicCopyMap.copy

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#190]
occured for 11b2a5f617e2aa8de
see https://www.firemind.ch/duels/506717 and https://www.firemind.ch/duels/510071
```
java.lang.StackOverflowError
	at magic.model.stack.MagicCardOnStack.copy(MagicCardOnStack.java:25)
	at magic.model.MagicCopyMap.copy(MagicCopyMap.java:18)
	at magic.model.MagicCopyMap.copyObject(MagicCopyMap.java:26)
	at magic.model.MagicCopyMap.copyObjects(MagicCopyMap.java:44)
	at magic.model.stack.MagicItemOnStack.<init>(MagicItemOnStack.java:52)
	at magic.model.stack.MagicCardOnStack.<init>(MagicCardOnStack.java:67)
	at magic.model.stack.MagicCardOnStack.copy(MagicCardOnStack.java:119)
	at magic.model.stack.MagicCardOnStack.copy(MagicCardOnStack.java:25)
	at magic.model.MagicCopyMap.copy(MagicCopyMap.java:18)
        ...
```

**Comment by ShawnieBoy** [comment]
Looks like Flusterstorm is the common card that would be creating copies - Are the copies adding to the storm count on their resolution?

**Comment by melvinzhang** [comment]
The 'copy' here not the copy action in the game, it is when a game object is copied to be used in the Al local instance of MagicGame.

**Comment by melvinzhang** [comment]
You might be on to something here. Spells can't target themselves but if
several go on the stack at the same time with storm you could have spell A
target B and B target A leading to a copying loop when the game is cloned
for the AI.

**Comment by ShawnieBoy** [comment]
Yes, as Flusterstorm requires a target spell when going on the stack, and storm provides plenty of targets
