### ISSUE TITLE
TestGame crash with Planeswalkers

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#206]
If a TestGame is created with a Planeswalker on the battlefield, TextImages gets sad:
```
Exception from controller.runGame: No corresponding icon for {lyl}
java.lang.RuntimeException: No corresponding icon for {lyl}
	at magic.data.TextImages.getIcon(TextImages.java:81)
	at magic.ui.widget.TextLabel.buildComponent(TextLabel.java:81)
	at magic.ui.widget.TextLabel.buildComponents(TextLabel.java:110)
	at magic.ui.widget.TextLabel.<init>(TextLabel.java:57)
	at magic.ui.duel.viewer.PermanentButton.<init>(PermanentButton.java:56)
	at magic.ui.duel.viewer.PermanentPanel.<init>(PermanentPanel.java:36)
	at magic.ui.duel.viewer.PermanentsViewer.update(PermanentsViewer.java:79)
	at magic.ui.duel.viewer.BattlefieldViewer.<init>(BattlefieldViewer.java:24)
	at magic.ui.duel.TextModeBattlefieldPanel.<init>(TextModeBattlefieldPanel.java:28)
	at magic.ui.duel.DuelPanel.<init>(DuelPanel.java:83)
	at magic.ui.screen.DuelGameScreen.getScreenContent(DuelGameScreen.java:65)
	at magic.ui.screen.DuelGameScreen.<init>(DuelGameScreen.java:57)
	at magic.ui.ScreenController.showDuelGameScreen(ScreenController.java:154)
	at magic.MagicMain.startUI(MagicMain.java:110)
	at magic.MagicMain.access$000(MagicMain.java:24)
	at magic.MagicMain$1.run(MagicMain.java:55)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

I've tried including Lvl counters in the TextImages list but it's still not happy.

**Comment by ShawnieBoy** [comment]
My bad - I blame my log font - it's {lyl} not {lvl} - I was including level counters instead of loyalty.

Still raises TextMode again though...
