### ISSUE TITLE
Remove deck strength viewer.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#211]
![screenshot00118](https://cloud.githubusercontent.com/assets/2443519/7216622/d7400f00-e5fd-11e4-9f35-a5ed258ac16c.png)

- Does anyone ever use it?
- I think it should be moved into the deck editor. 
  - Its current location implies that you are testing against your selected opponent but in fact (for obvious performance reasons) it runs MMABFast vs MMABFast.
  - Even on a level of 1 it takes too long in the context of setting up a new duel. I just want to play, it seems more natural to do deck anaysis from the deck editor.
  - It seems to me that there is some overlap with Firemind. Could these functions be merged?

**Comment by ShawnieBoy** [comment]
I second moving it to the deck editor, makes more sense in context - though to be honest I never use it as it takes far too long!

**Comment by melvinzhang** [comment]
It's location is meant to imply you are testing again the opponent's deck. In the context of randomly generated decks, my guess is that the purpose is to check that the generated decks are roughly equal in strength so that the duel would not be one sided. 

If it is in the deck editor, which you can start directly from the main screen, what would be the "other" deck? Or would it only appear in the deck editor if you launched the deck editor from the duel screen?

**Comment by lodici** [comment]
Currently, when I run it a level one it takes about 30 seconds. At level 8 (the default) it is unusable, I waited for 3 minutes and it never moved from Game 0. It was just "generating max time for AI game exceeded" messages.

As it stands I just think it comes across as a bit of a novelty function that clutters up the duel configuration screen with a set of options that most players will not be interested in. I do think the idea behind it is very interesting - for example,  if it was to run automatically in the background at level 1 in order to display a simple deck strength gauge as quickly as possible (without unduely concerning the player who just wants to start a duel).

For those users in deck development, test or analysis mode the current UI would seem better located in the deck editor. As you indicate it would need to be updated so that you can choose the deck to test against but given the context of the deck editor I think that would be expected anyway.

One other idea I came up with is to use the deck strength calculator to create a database of deck strengths for the prebuilt decks. This would give you a way of rating a deck and defining the difficulty for a duel. For example, given the "2012Affinity" deck, show a list of decks it performed poorly against for a difficult duel or altenatively a list of decks it has a 80% win ratio for an easy duel, etc. I did some calculations using the [combination formula](http://stackoverflow.com/questions/2201113/combinatoric-n-choose-r-in-java-math) (which I think is the correct thing to use) - given 238 prebuilt & firemind decks, using _C(238, 2)_ this would mean building a database of 28,203 deck strength ratings or about 9 days worth of calculations running 100 games at level 1 (on my quad core anyway, probably could do it in ten minutes on a hex)!

**Comment by ShawnieBoy** [comment]
...you rang?

With the deck strengths, I'm assuming that you'd only be interested in the other prebuilt decks, otherwise we could just add them to Firemind and see how they do.

As a quick test I ran 2012Affinity against itself at AI lvl 1 - Apart from generating lots of AI Max time warnings, it's taken 3min to get to game 15. Something seems a bit wrong. (Especially considering a 26% win rate)

**Comment by lodici** [comment]
You are right, I did the same thing and let it run for 5 minutes. It reached Game 31 with the win ratio hovering around 50% (which you would expect) but it was discarding alot of games because of ``WARNING. Max time for AI game exceeded``. Also, tried 2012Affinity against any 3-color random deck, also similar performance. It appears the 30-seconds I quoted was overly optimistic.

Finally, tried with two random any three color decks and...
```
Exception from controller.runGame: java.lang.ArrayIndexOutOfBoundsException: 1
magic.exception.GameException: java.lang.ArrayIndexOutOfBoundsException: 1
	at magic.model.MagicGame.doAction(MagicGame.java:571)
	at magic.model.score.MagicGameCombatScore.getScore(MagicGameCombatScore.java:35)
	at magic.model.choice.MagicDeclareBlockersResultBuilder.buildBlockersForAttacker(MagicDeclareBlockersResultBuilder.java:103)
	at magic.model.choice.MagicDeclareBlockersResultBuilder.buildBlockersForAttacker(MagicDeclareBlockersResultBuilder.java:122)
	at magic.model.choice.MagicDeclareBlockersResultBuilder.buildBlockersForAttacker(MagicDeclareBlockersResultBuilder.java:122)
	at magic.model.choice.MagicDeclareBlockersResultBuilder.build(MagicDeclareBlockersResultBuilder.java:243)
	at magic.model.choice.MagicDeclareBlockersResultBuilder.<init>(MagicDeclareBlockersResultBuilder.java:51)
	at magic.model.choice.MagicDeclareBlockersChoice.getArtificialOptions(MagicDeclareBlockersChoice.java:35)
	at magic.model.choice.MagicChoice.getArtificialChoiceResults(MagicChoice.java:98)
	at magic.model.event.MagicEvent.getArtificialChoiceResults(MagicEvent.java:390)
	at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:207)
	at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
	at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
	at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
	at magic.ai.MMAB$MMABWorker.evaluateGame(MMAB.java:260)
	at magic.ai.MMAB$1.run(MMAB.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at magic.model.MagicGame.executeEvent(MagicGame.java:756)
	at magic.model.stack.MagicItemOnStack.resolve(MagicItemOnStack.java:118)
	at magic.model.action.StackResolveAction.doAction(StackResolveAction.java:13)
	at magic.model.MagicGame.doAction(MagicGame.java:569)
```

**Comment by melvinzhang** [comment]
Thanks for the crash log. I think this is a bug in the new trigger system, it wasn't managed with actions and could not be undone correctly in the AI simulations. Fix incoming.

**Comment by lodici** [comment]
I don't think the calculator is fit for purpose or at least public release. The idea of a deck strength indicator is great but I don't think this implementation works. I think you could only apply it to prebuilt decks by building a predefined database of strength values "offline" instead of creating them on the fly but that also has its limitations as mentioned above.

**Comment by melvinzhang** [comment]
Agree, I think Firemind would be the better place to get a sense of deck strength. Also in actual games, I think the library order has a greater effect on how a specific game play out than the deck strength. Deck strength only makes sense statistically when many games are used, but that takes time to evaluate properly and Firemind is better suited.
