### ISSUE TITLE
pending triggers not resolved before moving to next phase

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#212]
In the following crash log, the Sage's Row Denizen's trigger is enqueued during declare attackers phase, but resolved during declare blockers phase. It should be resolved during declare attackers phase.

```
CRASH REPORT FOR MAGARENA THREAD Thread[pool-3633-thread-1,5,main]
CREATED ON 2015/04/19 23:55:08
MAGARENA VERSION 1.61, JRE 1.7.0_45, OS Linux_3.7.10-101.fc17.x86_64 amd64
================================
Used Memory: 110M
Free Memory: 136M
Total Memory: 247M
Max Memory: 494M
================================
-Xms256M
-Xmx512M
-Xverify:none
-Dcom.sun.management.jmxremote
-Dmagarena.dir=<https://buildhive.cloudbees.com/job/magarena/job/magarena/ws/release>
-Ddebug=false
-Dgame.log=1429484788.log
-Djava.awt.headless=true


Turn : 12  Phase : DeclareBlockers  Step : ActivePlayer  Player : MCTS  Score : 241
0] Player : MMABC  Life : 8  Delayed : Blue=1 Colorless=1 Total=2
   - Hand : Quillspike
   - Hand : Lilting Refrain
   - Hand : Shriekgeist
   - Graveyard : Insatiable Souleater
   - Permanent : Cloud Sprite  Power : 1  Toughness : 1  Damage : 0  Summoned
   - Permanent : Blind Phantasm  Power : 2  Toughness : 3  Damage : 0
   - Permanent : Chimeric Mass  Power : 3  Toughness : 3  Damage : 0
   - Permanent : Cloudseeder  Power : 1  Toughness : 1  Damage : 0  Tapped
   - Permanent : Island
   - Permanent : Rupture Spire  Tapped
   - Permanent : Sage's Row Denizen  Power : 2  Toughness : 3  Damage : 0  Summoned
   - Permanent : Swamp
   - Permanent : Swamp
1] Player : MCTS  Life : 4  Delayed : Total=0
   - Hand : Swamp
   - Hand : Giant Octopus
   - Hand : Haunter of Nightveil
   - Hand : Vial of Poison
   - Hand : Swamp
   - Graveyard : Crimson Kobolds
   - Graveyard : Snake Cult Initiation
   - Permanent : Adventuring Gear
   - Permanent : Island
   - Permanent : Island
   - Permanent : Squelching Leeches  Power : 2  Toughness : 2  Damage : 0  Tapped
   - Permanent : Swamp
   - Permanent : Swamp
Stack : 0
1. MarkerAction = 0
2. ExecuteFirstEventAction = 0
3. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
4. ExecuteFirstEventAction = 0
5. AddEventAction (EVENT: NONE  Declare attackers.) = 0
6. MarkerAction = 0
7. ExecuteFirstEventAction = 0
8. DeclareAttackersAction = 0
9. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
10. ExecuteFirstEventAction = 0
11. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
12. ExecuteFirstEventAction = 0
13. MarkerAction = 0
14. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
15. MarkerAction = 0
16. ExecuteFirstEventAction = 0
17. AddEventAction (EVENT: Sage's Row Denizen Pay {2}{U}$. Choose how to pay the mana cost.) = 0
18. AddEventAction (EVENT: Sage's Row Denizen Play Sage's Row Denizen. ) = 0
19. ExecuteFirstEventAction = 0
20. PayDelayedCostAction = 0
21. ExecuteFirstEventAction = 0
22. RemoveCardAction (Sage's Row Denizen) = -248
23. PutItemOnStackAction (MagicCardOnStack,Sage's Row Denizen) = -1
24. AddEventAction (EVENT: Sage's Row Denizen  ) = 0
25. ExecuteFirstEventAction = 0
26. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
27. ExecuteFirstEventAction = 0
28. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
29. ExecuteFirstEventAction = 0
30. StackResolveAction = 0
31. PlayCardFromStackAction (Sage's Row Denizen) = 1453
32. ChangeStateAction = 0
33. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
34. ExecuteFirstEventAction = 0
35. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
36. ExecuteFirstEventAction = 0
37. ReturnExiledAction = 0
38. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
39. ExecuteFirstEventAction = 0
40. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
41. ExecuteFirstEventAction = 0
42. CleanupTurnTriggersAction = 0
43. CleanupPlayerAction = 0
44. CleanupPermanentAction = 0
45. CleanupPermanentAction = 0
46. CleanupPermanentAction = 0
47. CleanupPermanentAction = 0
48. CleanupPermanentAction = 0
49. CleanupPermanentAction = 0
50. CleanupPermanentAction = 0
51. CleanupPermanentAction = 0
52. CleanupPlayerAction = 0
53. CleanupPermanentAction = 0
54. CleanupPermanentAction = 0
55. CleanupPermanentAction = 0
56. CleanupPermanentAction = 0
57. CleanupPermanentAction = 0
58. CleanupPermanentAction = 0
59. CleanupTurnStaticsAction = 0
60. MarkerAction = 0
61. PayDelayedCostsAction = 0
62. UntapAction (Island) = -5
63. UntapAction (Island) = -5
64. ChangeStateAction = 0
65. ChangeStateAction = 0
66. UntapAction (Swamp) = -5
67. UntapAction (Swamp) = -5
68. DrawAction = -375
69. AddEventAction (EVENT: NONE  ...) = 0
70. ExecuteFirstEventAction = 0
71. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
72. MarkerAction = 0
73. ExecuteFirstEventAction = 0
74. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
75. ExecuteFirstEventAction = 0
76. AddEventAction (EVENT: NONE  Declare attackers.) = 0
77. MarkerAction = 0
78. ExecuteFirstEventAction = 0
79. DeclareAttackersAction = 0
80. TapAction (Squelching Leeches) = 10
81. DeclareAttackerAction = 0
82. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
83. ExecuteFirstEventAction = 0
84. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
85. MarkerAction = 0
86. ExecuteFirstEventAction = 0
87. AddEventAction (EVENT: Chimeric Mass  ) = 0
88. AddEventAction (EVENT: Chimeric Mass Pay {1}$. Choose how to pay the mana cost.) = 0
89. AddEventAction (EVENT: Chimeric Mass Play activated ability of Chimeric Mass. ) = 0
90. ExecuteFirstEventAction = 0
91. PlayAbilityAction = 0
92. ExecuteFirstEventAction = 0
93. PayDelayedCostAction = 0
94. ExecuteFirstEventAction = 0
95. PutItemOnStackAction (MagicAbilityOnStack,Chimeric Mass) = -1
96. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
97. ExecuteFirstEventAction = 0
98. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
99. ExecuteFirstEventAction = 0
100. StackResolveAction = 0
101. BecomesCreatureAction = 0
102. AddStaticAction (Chimeric Mass,Chimeric_Mass$1@35dd9650) = 0
103. AddStaticAction (Chimeric Mass,Chimeric_Mass$2@66b779d0) = 0
104. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
105. ExecuteFirstEventAction = 0
106. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
107. MarkerAction = 0
108. ExecuteFirstEventAction = 0
109. AddEventAction (EVENT: Cloudseeder Tap Cloudseeder. ) = 0
110. AddEventAction (EVENT: Cloudseeder Pay {U}$. Choose how to pay the mana cost.) = 0
111. AddEventAction (EVENT: Cloudseeder MMABC discards a card$. Choose a card from your hand.) = 0
112. AddEventAction (EVENT: Cloudseeder Play activated ability of Cloudseeder. ) = 0
113. ExecuteFirstEventAction = 0
114. TapAction (Cloudseeder) = -10
115. ExecuteFirstEventAction = 0
116. PayDelayedCostAction = 0
117. MarkerAction = 0
118. ExecuteFirstEventAction = 0
119. DiscardCardAction = -180
120. MoveCardAction (Insatiable Souleater,OwnersHand,Graveyard) = 0
121. ExecuteFirstEventAction = 0
122. PutItemOnStackAction (MagicAbilityOnStack,Cloudseeder) = -1
123. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
124. ExecuteFirstEventAction = 0
125. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
126. ExecuteFirstEventAction = 0
127. StackResolveAction = 0
128. PlayTokenAction = 0
129. AddEventAction (EVENT: Cloud Sprite Put Cloud Sprite onto the battlefield. ) = 0
130. ExecuteFirstEventAction = 0
131. PlayCardFromStackAction (Cloud Sprite) = 620
132. EnqueueTriggerAction = 0
133. AddEventAction (EVENT: NONE  Declare blockers.) = 0
134. MarkerAction = 0
135. DeclareBlockersAction = 0
136. CombatDamageAction = 0
137. CombatDamageAction = 0
138. DealDamageAction = 0
139. ChangeLifeAction (MMABC,-2) = -1000
140. ChangePlayerStateAction = 0
141. AddStaticAction (MagicPermanent.NONE,magic.model.action.ChangePlayerStateAction$3@179e7b5f) = 0
142. ChangePlayerStateAction = 0
143. AddStaticAction (MagicPermanent.NONE,magic.model.action.ChangePlayerStateAction$3@25b5a616) = 0
144. PutItemOnStackAction (MagicTriggerOnStack,Sage's Row Denizen) = -1
145. AddEventAction (EVENT: Sage's Row Denizen  Choose target player.) = 0
146. DequeueTriggerAction = 0
147. StackResolveAction = 0
Score = 246

Exception from controller.runGame: java.lang.ArrayIndexOutOfBoundsException: 0
magic.exception.GameException: java.lang.ArrayIndexOutOfBoundsException: 0
        at magic.model.MagicGame.doAction(MagicGame.java:569)
        at magic.model.score.MagicGameCombatScore.getScore(MagicGameCombatScore.java:35)
        at magic.model.choice.MagicDeclareBlockersResultBuilder.buildBlockersForAttacker(MagicDeclareBlockersResultBuilder.java:103)
        at magic.model.choice.MagicDeclareBlockersResultBuilder.buildBlockersForAttacker(MagicDeclareBlockersResultBuilder.java:122)
        at magic.model.choice.MagicDeclareBlockersResultBuilder.build(MagicDeclareBlockersResultBuilder.java:243)
        at magic.model.choice.MagicDeclareBlockersResultBuilder.<init>(MagicDeclareBlockersResultBuilder.java:51)
        at magic.model.choice.MagicDeclareBlockersChoice.getArtificialOptions(MagicDeclareBlockersChoice.java:34)
        at magic.model.choice.MagicChoice.getArtificialChoiceResults(MagicChoice.java:98)
        at magic.model.event.MagicEvent.getArtificialChoiceResults(MagicEvent.java:390)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:207)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:188)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:188)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
        at magic.ai.MMAB$MMABWorker.evaluateGame(MMAB.java:260)
        at magic.ai.MMAB$1.run(MMAB.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at magic.model.MagicGame.executeEvent(MagicGame.java:759)
        at magic.model.stack.MagicItemOnStack.resolve(MagicItemOnStack.java:118)
        at magic.model.action.StackResolveAction.doAction(StackResolveAction.java:13)
        at magic.model.MagicGame.doAction(MagicGame.java:567)
        ... 23 more
```

**Comment by melvinzhang** [comment]
Another instance reported by Jenkins

```
CRASH REPORT FOR MAGARENA THREAD Thread[pool-2890-thread-1,5,main]
CREATED ON 2015/04/20 03:12:59
MAGARENA VERSION 1.61, JRE 1.7.0_51, OS Linux_3.7.10-101.fc17.x86_64 amd64
================================
Used Memory: 150M
Free Memory: 97M
Total Memory: 247M
Max Memory: 494M
================================
-Xms256M
-Xmx512M
-Xverify:none
-Dcom.sun.management.jmxremote
-Dmagarena.dir=<https://buildhive.cloudbees.com/job/magarena/job/magarena/ws/release>
-Ddebug=false
-Dgame.log=1429497245.log
-Djava.awt.headless=true


Turn : 19  Phase : DeclareBlockers  Step : ActivePlayer  Player : MCTS  Score : -5372
0] Player : MMABC  Life : 2  Delayed : Black=1 Colorless=4 Total=5
   - Hand : Psychotic Haze
   - Hand : Mythic Proportions
   - Hand : Unstoppable Ash
   - Hand : Opulent Palace
   - Hand : Corpse Dance
   - Graveyard : Elite Cat Warrior
   - Permanent : Basilisk Collar
   - Permanent : Forest
   - Permanent : Forest
   - Permanent : Forest
   - Permanent : Forest
   - Permanent : Living Terrain
   - Permanent : Spidersilk Net
   - Permanent : Swamp
   - Permanent : Swamp  Power : 4  Toughness : 5  Damage : 0  Tapped
   - Permanent : Vesper Ghoul  Power : 1  Toughness : 1  Damage : 0  Tapped
   - Permanent : Yavimaya Granger  Power : 2  Toughness : 2  Damage : 0  Summoned
1] Player : MCTS  Life : 7  Delayed : Red=2 Colorless=2 Total=4
   - Hand : Jungle Shrine
   - Graveyard : Slinking Giant
   - Graveyard : Elite Scaleguard
   - Graveyard : Burden of Guilt
   - Permanent : Agrus Kos, Wojek Veteran  Power : 5  Toughness : 5  Damage : 0  Tapped
   - Permanent : Lone Missionary  Power : 6  Toughness : 7  Damage : 0  Tapped
   - Permanent : Mountain
   - Permanent : Mountain
   - Permanent : Plains
   - Permanent : Plains
   - Permanent : Plains
   - Permanent : Plains
   - Permanent : Uncontrollable Anger  Summoned
Stack : 0
1. MarkerAction = 0
2. ExecuteFirstEventAction = 0
3. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
4. ExecuteFirstEventAction = 0
5. ReturnExiledAction = 0
6. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
7. ExecuteFirstEventAction = 0
8. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
9. ExecuteFirstEventAction = 0
10. CleanupTurnTriggersAction = 0
11. CleanupPlayerAction = 0
12. CleanupPermanentAction = 0
13. CleanupPermanentAction = 0
14. CleanupPermanentAction = 0
15. CleanupPermanentAction = 0
16. CleanupPermanentAction = 0
17. CleanupPermanentAction = 0
18. CleanupPermanentAction = 0
19. CleanupPermanentAction = 0
20. CleanupPermanentAction = 0
21. CleanupPermanentAction = 0
22. CleanupPlayerAction = 0
23. CleanupPermanentAction = 0
24. CleanupPermanentAction = 0
25. CleanupPermanentAction = 0
26. CleanupPermanentAction = 0
27. CleanupPermanentAction = 0
28. CleanupPermanentAction = 0
29. CleanupPermanentAction = 0
30. CleanupPermanentAction = 0
31. CleanupTurnStaticsAction = 0
32. MarkerAction = 0
33. ChangeStateAction = 0
34. ChangeStateAction = 0
35. UntapAction (Mountain) = -5
36. UntapAction (Plains) = -5
37. UntapAction (Plains) = -5
38. UntapAction (Plains) = -5
39. ChangeStateAction = 0
40. ChangeStateAction = 0
41. UntapAction (Plains) = -5
42. DrawAction = -200
43. AddEventAction (EVENT: NONE  ...) = 0
44. ExecuteFirstEventAction = 0
45. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
46. ExecuteFirstEventAction = 0
47. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
48. ExecuteFirstEventAction = 0
49. AddEventAction (EVENT: NONE  Declare attackers.) = 0
50. MarkerAction = 0
51. ExecuteFirstEventAction = 0
52. DeclareAttackersAction = 0
53. TapAction (Agrus Kos, Wojek Veteran) = 10
54. TapAction (Lone Missionary) = 10
55. DeclareAttackerAction = 0
56. DeclareAttackerAction = 0
57. EnqueueTriggerAction = 0
58. PutItemOnStackAction (MagicTriggerOnStack,Agrus Kos, Wojek Veteran) = 1
59. DequeueTriggerAction = 0
60. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
61. ExecuteFirstEventAction = 0
62. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
63. MarkerAction = 0
64. ExecuteFirstEventAction = 0
65. StackResolveAction = 0
66. ChangeTurnPTAction = 0
67. AddStaticAction (Agrus Kos, Wojek Veteran,magic.model.action.ChangeTurnPTAction$1@58a2480b) = 0
68. ChangeTurnPTAction = 0
69. AddStaticAction (Agrus Kos, Wojek Veteran,magic.model.action.ChangeTurnPTAction$1@627f7a3) = 0
70. ChangeTurnPTAction = 0
71. AddStaticAction (Lone Missionary,magic.model.action.ChangeTurnPTAction$1@29f2f17d) = 0
72. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
73. ExecuteFirstEventAction = 0
74. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
75. MarkerAction = 0
76. ExecuteFirstEventAction = 0
77. AddEventAction (EVENT: Corpse Dance Pay {2}{B}$. Choose how to pay the mana cost.) = 0
78. AddEventAction (EVENT: Corpse Dance MMABC may$ pay the buyback cost. Pay the buyback cost?) = 0
79. AddEventAction (EVENT: Corpse Dance Play Corpse Dance. ) = 0
80. ExecuteFirstEventAction = 0
81. PayDelayedCostAction = 0
82. MarkerAction = 0
83. ExecuteFirstEventAction = 0
84. AddFirstEventAction (EVENT: Corpse Dance Pay {2}$. Choose how to pay the mana cost.) = 0
85. SetKickerAction = 0
86. ExecuteFirstEventAction = 0
87. PayDelayedCostAction = 0
88. ExecuteFirstEventAction = 0
89. RemoveCardAction (Corpse Dance) = -438
90. PutItemOnStackAction (MagicCardOnStack,Corpse Dance) = -1
91. AddEventAction (EVENT: Corpse Dance  ) = 0
92. ExecuteFirstEventAction = 0
93. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
94. ExecuteFirstEventAction = 0
95. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
96. MarkerAction = 0
97. ExecuteFirstEventAction = 0
98. AddEventAction (EVENT: Uncontrollable Anger Pay {2}{R}{R}$. Choose how to pay the mana cost.) = 0
99. AddEventAction (EVENT: Uncontrollable Anger Play Uncontrollable Anger. ) = 0
100. ExecuteFirstEventAction = 0
101. PayDelayedCostAction = 0
102. ExecuteFirstEventAction = 0
103. RemoveCardAction (Uncontrollable Anger) = 200
104. PutItemOnStackAction (MagicCardOnStack,Uncontrollable Anger) = 1
105. AddEventAction (EVENT: Uncontrollable Anger  Choose target creature.) = 0
106. AddEventAction (EVENT: Uncontrollable Anger  ) = 0
107. ExecuteFirstEventAction = 0
108. ExecuteFirstEventAction = 0
109. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
110. ExecuteFirstEventAction = 0
111. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
112. ExecuteFirstEventAction = 0
113. StackResolveAction = 0
114. PlayCardFromStackAction (Uncontrollable Anger,Lone Missionary) = -500
115. ChangeStateAction = 0
116. StackResolveAction = 0
117. ReanimateAction = 0
118. RemoveCardAction (Yavimaya Granger) = 0
119. PlayCardAction = 0
120. AddEventAction (EVENT: Yavimaya Granger Put Yavimaya Granger onto the battlefield. ) = 0
121. ChangeCardDestinationAction = 0
122. MoveCardAction (Corpse Dance,Stack,OwnersHand) = 438
123. ExecuteFirstEventAction = 0
124. PlayCardFromStackAction (Yavimaya Granger) = 1342
125. GainAbilityAction (Yavimaya Granger,magic.model.MagicAbilityList@ccc5b0f) = 0
126. AddStaticAction (Yavimaya Granger,magic.model.action.GainAbilityAction$1@3c6e3c59) = 0
127. AddTriggerAction (Yavimaya Granger,magic.model.trigger.MagicAtEndOfTurnTrigger$4@693c160d) = 0
128. EnqueueTriggerAction = 0
129. AddEventAction (EVENT: NONE  Declare blockers.) = 0
130. MarkerAction = 0
131. DeclareBlockersAction = 0
132. CombatDamageAction = 0
133. CombatDamageAction = 0
134. DealDamageAction = 0
135. ChangeLifeAction (MMABC,-5) = -2200
136. ChangePlayerStateAction = 0
137. AddStaticAction (MagicPermanent.NONE,magic.model.action.ChangePlayerStateAction$3@67cbe574) = 0
138. ChangePlayerStateAction = 0
139. AddStaticAction (MagicPermanent.NONE,magic.model.action.ChangePlayerStateAction$3@7b4557e8) = 0
140. DealDamageAction = 0
141. ChangeLifeAction (MMABC,-6) = -4000
142. ChangePlayerStateAction = 0
143. AddStaticAction (MagicPermanent.NONE,magic.model.action.ChangePlayerStateAction$3@58e7f92) = 0
144. ChangePlayerStateAction = 0
145. AddStaticAction (MagicPermanent.NONE,magic.model.action.ChangePlayerStateAction$3@4e594d17) = 0
146. PutItemOnStackAction (MagicTriggerOnStack,Yavimaya Granger) = -1
147. AddEventAction (EVENT: Yavimaya Granger  Search your library for a basic land card and put it onto the battlefield tapped? Then shuffle your library.) = 0
148. DequeueTriggerAction = 0
149. StackResolveAction = 0
Score = -5363

Exception from controller.runGame: java.lang.ArrayIndexOutOfBoundsException: 0
magic.exception.GameException: java.lang.ArrayIndexOutOfBoundsException: 0
        at magic.model.MagicGame.doAction(MagicGame.java:569)
        at magic.model.score.MagicGameCombatScore.getScore(MagicGameCombatScore.java:35)
        at magic.model.choice.MagicDeclareBlockersResultBuilder.buildBlockersForAttacker(MagicDeclareBlockersResultBuilder.java:103)
        at magic.model.choice.MagicDeclareBlockersResultBuilder.buildBlockersForAttacker(MagicDeclareBlockersResultBuilder.java:122)
        at magic.model.choice.MagicDeclareBlockersResultBuilder.buildBlockersForAttacker(MagicDeclareBlockersResultBuilder.java:122)
        at magic.model.choice.MagicDeclareBlockersResultBuilder.build(MagicDeclareBlockersResultBuilder.java:243)
        at magic.model.choice.MagicDeclareBlockersResultBuilder.<init>(MagicDeclareBlockersResultBuilder.java:51)
        at magic.model.choice.MagicDeclareBlockersChoice.getArtificialOptions(MagicDeclareBlockersChoice.java:34)
        at magic.model.choice.MagicChoice.getArtificialChoiceResults(MagicChoice.java:98)
        at magic.model.event.MagicEvent.getArtificialChoiceResults(MagicEvent.java:390)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:207)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:188)
        at magic.ai.MMAB$MMABWorker.evaluateGame(MMAB.java:260)
        at magic.ai.MMAB$1.run(MMAB.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at magic.model.event.MagicEvent.isYes(MagicEvent.java:454)
        at magic.model.event.MagicRuleEventAction$158$1.executeEvent(MagicRuleEventAction.java:3622)
        at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:650)
        at magic.model.MagicGame.executeEvent(MagicGame.java:763)
        at magic.model.stack.MagicItemOnStack.resolve(MagicItemOnStack.java:118)
        at magic.model.action.StackResolveAction.doAction(StackResolveAction.java:13)
        at magic.model.MagicGame.doAction(MagicGame.java:567)
        ... 21 more
```
