### ISSUE TITLE
Unable to start new duel if previous deck becomes illegal

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#220]
Was testing some new cards in a deck, some weren't working correctly so removed the script files.

Restarted and created a new deck with the remaining cards that were working.

Attempted to start a new Duel, crash due to not being able to find one of the removed script files.

If I'm starting a new duel it shouldn't be trying to load previous decks?

**Comment by lodici** [comment]
crash log please.

**Comment by ShawnieBoy** [comment]
```
CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
CREATED ON 2015/04/23 12:07:58
MAGARENA VERSION 1.61, JRE 1.8.0_45, OS Windows 7_6.1 amd64
================================
Used Memory: 196M
Free Memory: 935M
Total Memory: 1131M
Max Memory: 7282M
================================
-Xms1g
-Xmx8g


Exception from controller.runGame: card script file not found: D:\Magarena Repositories\magarena\release\Magarena\scripts\Duct_Crawler.txt
java.lang.RuntimeException: card script file not found: D:\Magarena Repositories\magarena\release\Magarena\scripts\Duct_Crawler.txt
	at magic.data.CardDefinitions.loadCardDefinition(CardDefinitions.java:193)
	at magic.data.CardDefinitions.getCard(CardDefinitions.java:274)
	at magic.model.DuelPlayerConfig.load(DuelPlayerConfig.java:65)
	at magic.data.DuelConfig.load(DuelConfig.java:101)
	at magic.model.MagicDuel.load(MagicDuel.java:226)
	at magic.model.MagicDuel.load(MagicDuel.java:235)
	at magic.ui.MagicFrame.loadDuel(MagicFrame.java:123)
	at magic.ui.screen.MainMenuScreen$2.actionPerformed(MainMenuScreen.java:98)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by lodici** [comment]
```
  at magic.ui.screen.MainMenuScreen$2.actionPerformed(MainMenuScreen.java:98)
```
says you clicked on "Resume Duel" not "New Duel". Hence the crash - unlikely to happen in release unless the user is manually removing script files in which case they get what they deserve! :smiling_imp:

**Comment by ShawnieBoy** [comment]
```
CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
CREATED ON 2015/04/23 13:00:45
MAGARENA VERSION 1.61, JRE 1.8.0_45, OS Windows 7_6.1 amd64
================================
Used Memory: 387M
Free Memory: 669M
Total Memory: 1057M
Max Memory: 7282M
================================
-Xms1g
-Xmx8g


Exception from controller.runGame: card script file not found: D:\Magarena Repositories\magarena\release\Magarena\scripts\Duct_Crawler.txt
java.lang.RuntimeException: card script file not found: D:\Magarena Repositories\magarena\release\Magarena\scripts\Duct_Crawler.txt
	at magic.data.CardDefinitions.loadCardDefinition(CardDefinitions.java:193)
	at magic.data.CardDefinitions.getCard(CardDefinitions.java:274)
	at magic.model.DuelPlayerConfig.load(DuelPlayerConfig.java:65)
	at magic.data.DuelConfig.load(DuelConfig.java:101)
	at magic.data.DuelConfig.load(DuelConfig.java:108)
	at magic.ui.screen.NewDuelSettingsScreen.<init>(NewDuelSettingsScreen.java:41)
	at magic.ui.ScreenController.showDuelPlayersScreen(ScreenController.java:138)
	at magic.ui.screen.MainMenuScreen$1.actionPerformed(MainMenuScreen.java:91)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

Here's the correct log

**Comment by lodici** [comment]
Just to confirm you are removing a script from the ``scripts`` folder?

**Comment by ShawnieBoy** [comment]
Yes

**Comment by ShawnieBoy** [comment]
The interesting thing is that the deck has since been re-saved without the missing card. But it looks like it's still using an older decklist (?)

**Comment by lodici** [comment]
That is correct and by design. It has always been so.The deck cards are copied at the time the duel is created. No reference is kept to the original deck.

**Comment by lodici** [comment]
Incidentally the (temp) workaround is to delete ``Magarena\duels\latest.duel``.

**Comment by ShawnieBoy** [comment]
I see, learn something new every day :grinning: Thanks for the workaround
