### ISSUE TITLE
NPE when opened deck editor

### ISSUE THREAD

**Issue by bilbo2** [magarena/magarena#252]
I opened deck editor, chose player decks and then when clicked on any deck (all of them contain at least one unimplemented card, though, so maybe that can be the cause, although about 14 days ago it worked fine there), I got his NPE:

Exception from controller.runGame: null
java.lang.NullPointerException
        at java.lang.String.compareTo(String.java:1139)
        at magic.model.MagicCardDefinition$3.compare(MagicCardDefinition.java:928)
        at magic.model.MagicCardDefinition$3.compare(MagicCardDefinition.java:925)
        at magic.model.MagicCondensedCardDefinition$5.compare(MagicCondensedCardDefinition.java:68)
        at magic.model.MagicCondensedCardDefinition$5.compare(MagicCondensedCardDefinition.java:65)
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:324)
        at java.util.TimSort.sort(TimSort.java:189)
        at java.util.TimSort.sort(TimSort.java:173)
        at java.util.Arrays.sort(Arrays.java:659)
        at java.util.Collections.sort(Collections.java:217)
        at magic.ui.cardtable.CardTableModel.setCards(CardTableModel.java:118)
        at magic.ui.cardtable.CardTable.setCards(CardTable.java:196)
        at magic.ui.screen.DecksScreen$ScreenContent.setDeck(DecksScreen.java:236)
        at magic.ui.widget.deck.DeckPicker$3$1.run(DeckPicker.java:248)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.awt.EventQueue$3.run(EventQueue.java:704)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

Using newest git revision f3b65fbca995962e2c6ae8f45783202c533b6a24

**Comment by ShawnieBoy** [comment]
I've noticed this today as well - it's decks containing unimplemented cards for some reason. @lodici should be on the case ;)

**Comment by lodici** [comment]
Thanks - replicated.
