### ISSUE TITLE
'getGame called for MagicPlayer.NONE' on playing Duplicant

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#265]
found by build server, stack trace:

```
Caused by: java.lang.RuntimeException: getGame called for MagicPlayer.NONE
        at magic.model.MagicPlayer$1.getGame(MagicPlayer.java:42)
        at magic.model.target.MagicPermanentFilterImpl.filter(MagicPermanentFilterImpl.java:26)
        at magic.model.target.MagicPermanentFilterImpl.filter(MagicPermanentFilterImpl.java:14)
        at magic.model.MagicAmountFactory$1.getAmount(MagicAmountFactory.java:12)
        at magic.model.mstatic.MagicCDA$2.modPowerToughness(MagicCDA.java:40)
        at magic.model.MagicCardDefinition.applyCDAPowerToughness(MagicCardDefinition.java:691)
        at magic.model.MagicCard.genPowerToughness(MagicCard.java:187)
        at magic.model.MagicCard.genPowerToughness(MagicCard.java:182)
        at magic.model.MagicCard.getPower(MagicCard.java:174)
        at Duplicant$1.modPowerToughness(Duplicant.groovy:6)
        at magic.model.MagicPermanent.apply(MagicPermanent.java:499)
        at magic.model.MagicPermanent.updateProperties(MagicPermanent.java:444)
        at magic.model.MagicPermanent.update(MagicPermanent.java:416)
        at magic.model.MagicGame.update(MagicGame.java:570)
        at magic.model.MagicGame.executeEvent(MagicGame.java:758)
        at magic.model.stack.MagicItemOnStack.resolve(MagicItemOnStack.java:122)
        at magic.model.action.StackResolveAction.doAction(StackResolveAction.java:13
```

**Comment by melvinzhang** [comment]
Related crash:
```
Caused by: java.lang.RuntimeException: getGame called for MagicPlayer.NONE
        at magic.model.MagicPlayer$1.getGame(MagicPlayer.java:42)
        at magic.model.target.MagicPermanentFilterImpl.filter(MagicPermanentFilterImpl.java:26)
        at magic.model.target.MagicPermanentFilterImpl.filter(MagicPermanentFilterImpl.java:14)
        at magic.model.MagicAmountFactory$1.getAmount(MagicAmountFactory.java:12)
        at magic.model.mstatic.MagicCDA$2.modPowerToughness(MagicCDA.java:40)
        at magic.model.MagicCardDefinition.applyCDAPowerToughness(MagicCardDefinition.java:691)
        at magic.model.MagicCard.genPowerToughness(MagicCard.java:187)
        at magic.model.MagicCard.genPowerToughness(MagicCard.java:182)
        at magic.model.MagicCard.getPower(MagicCard.java:174)
        at Corpse_Lunge$1$_executeEvent_closure1.doCall(Corpse_Lunge.groovy:16)
```

**Comment by ShawnieBoy** [comment]
That's strange, both getting the info of a card's power

**Comment by melvinzhang** [comment]
Not sure what is the card, but it has a CDA. https://github.com/magarena/magarena/commit/e31f42358686e2bcbba44fbde97a422009cb5b63 is an attempt to fix this. CDA can be called with MagicPermanent.NONE and previously it was using source.getController in the MagicAmount for the CDA which becomes MagicPlayer.NONE. MagicPermanentFilterImpl calls player.getGame(). So the player passed to filter should never be NONE.

**Comment by ShawnieBoy** [comment]
Well, if it is a card with a CDA, it should be returning zero anyway. A MagicCard could just skip the CDA part for power/toughness

**Comment by melvinzhang** [comment]
Zero? CDA means means it applies in all zones. Tarmogoyf's power is defined in all zones to be the number of card types among cards in all graveyards and its toughness is equal to that number plus 1.

**Comment by ShawnieBoy** [comment]
I never realized they applied in all zones! I always thought that the power/toughness when in hand was more of a play aid, lol.

I always thought it meant that it wasn't a fixed number - possibly an old version of the rule stuck in my head - or hijacking the X = 0 for mana.

Learn something new every day.

**Comment by melvinzhang** [comment]
Could not reproduce.
