### ISSUE TITLE
java.lang.RuntimeException: Missing default AI player profile!

### ISSUE THREAD

**Issue by itandetnik** [magarena/magarena#329]
Fresh install of Maragena 1.62. Imported from 1.61. Crashes on Resume Duel or New Duel.

    CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
    CREATED ON 2015/06/02 00:00:59
    MAGARENA VERSION 1.62, JRE 1.8.0_31, OS Windows 7_6.1 x86
    ================================
    Used Memory: 72M
    Free Memory: 175M
    Total Memory: 247M
    Max Memory: 494M
    ================================
    -Xms256m
    -Xmx512m
    -Xverify:none

    Exception from controller.runGame: null
    java.lang.ExceptionInInitializerError
    	at magic.model.MagicDuel.<init>(MagicDuel.java:41)
    	at magic.ui.MagicFrame.loadDuel(MagicFrame.java:128)
    	at magic.ui.screen.MainMenuScreen$2.actionPerformed(MainMenuScreen.java:98)
    	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
    	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
    	at java.awt.Component.processMouseEvent(Unknown Source)
    	at javax.swing.JComponent.processMouseEvent(Unknown Source)
    	at java.awt.Component.processEvent(Unknown Source)
    	at java.awt.Container.processEvent(Unknown Source)
    	at java.awt.Component.dispatchEventImpl(Unknown Source)
    	at java.awt.Container.dispatchEventImpl(Unknown Source)
    	at java.awt.Component.dispatchEvent(Unknown Source)
    	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    	at java.awt.Container.dispatchEventImpl(Unknown Source)
    	at java.awt.Window.dispatchEventImpl(Unknown Source)
    	at java.awt.Component.dispatchEvent(Unknown Source)
    	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    	at java.awt.EventQueue.access$500(Unknown Source)
    	at java.awt.EventQueue$3.run(Unknown Source)
    	at java.awt.EventQueue$3.run(Unknown Source)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    	at java.awt.EventQueue$4.run(Unknown Source)
    	at java.awt.EventQueue$4.run(Unknown Source)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    	at java.awt.EventQueue.dispatchEvent(Unknown Source)
    	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    	at java.awt.EventDispatchThread.run(Unknown Source)
    Caused by: java.lang.RuntimeException: Missing default AI player profile!
    	at magic.model.player.PlayerProfiles.getDefaultAiPlayer(PlayerProfiles.java:133)
    	at magic.data.DuelConfig.<init>(DuelConfig.java:44)
    	at magic.data.DuelConfig.<clinit>(DuelConfig.java:14)
    	... 40 more

**Comment by lodici** [comment]
Try removing the ``Magarena/duels`` directory.

**Comment by itandetnik** [comment]
Removing `Magarena/duels` didn't help. Resume Duel (unsurprisingly) says "No saved duels found", New Duel still crashes.

Removing `Magarena/players` does seem to have helped. The application created a new player and 3 AIs on the next run. I was then able to copy over the old player and AI, they appeared in the list and can be selected. So looks like I'm all set.

**Comment by lodici** [comment]
If you still have it, it would be really useful if you could post a link to a zipped copy of your 1.61 ``players`` directory but that seems to be suprisingly difficult so if you could email it to lodici123@gmail.com instead I can try and replicate. Thanks for the feedback anyway.

**Comment by lodici** [comment]
Thanks for zip and I have replicated. Impressive stats BTW - need to tweak the layout to fit better.
![screenshot00167](https://cloud.githubusercontent.com/assets/2443519/7938015/304f5d98-093b-11e5-9ad4-c758fe18e8f5.png)

**Comment by lodici** [comment]
Regression introduced by fix for #181. Did not take into account that it is possible for a user to remove the default AI player profiles. In this case all AI profiles have been removed except for MCTSC so there is no default MCTS to find. Solution is to return the first AI profile if MCTS is missing.

Does raise the question - should you be able to remove the default AI profiles?

**Comment by lodici** [comment]
The 1.62 solution is...
1. After importing, close Magarena.
2. Make a copy of the ``Magarena\players`` directory.
3. Delete the ``Magarena\players`` directory.
4. Run Magarena and click on "New Duel" to create default AI profiles.
5. Exit Magarena.
6. Copy the contents of the ``Magarena\players`` backup made in 2. into the new ``Magarena\players``.
7. The previous profiles should now be available to select from the New Duel screen.
