### ISSUE TITLE
I'm making more errors...

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#348]
I'm creating errors left, right and centre :cry: 
This time errors from [Compulsive Research](http://magiccards.info/c14/en/102.html)

```groovy
def action = {
    final MagicGame game, final MagicEvent event ->
    final MagicEvent discardEvent = new MagicDiscardChosenEvent(event.getSource(), event.getRefPlayer(), LAND_CARD_FROM_HAND)
    if (event.isYes() && discardEvent.isSatisfied()) {
        game.addEvent(discardEvent);
    } else {
        game.addEvent(new MagicDiscardEvent(event.getSource(), event.getRefPlayer(), 2));
    }
}

[
    new MagicSpellCardEvent() {
        @Override
        public MagicEvent getEvent(final MagicCardOnStack cardOnStack,final MagicPayedCost payedCost) {
            return new MagicEvent(
                cardOnStack,
                TARGET_PLAYER,
                this,
                "Target player\$ draws three cards. Then that player discards two cards unless he or she discards a land card."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            event.processTargetPlayer(game, {
                game.doAction(new DrawAction(it, 3));
                game.addEvent(new MagicEvent(
                    event.getSource(),
                    it,
                    new MagicMayChoice("Discard a land card?"),
                    action,
                    "PN may\$ discard a land card. If he or she doesn't, PN discards two cards"
                ));
            })
        }
    }
]
```
This crashed to desktop with no crash log or error thrown, but thankfully a test scenario gave me this error when declining to discard a land card when I could have:

```
Exception from controller.runGame: java.lang.ClassCastException
magic.exception.GameException: java.lang.ClassCastException
        at magic.model.MagicGame.doAction(MagicGame.java:566)
        at magic.model.MagicGame.executeNextEvent(MagicGame.java:832)
        at magic.ui.SwingGameController.executeNextEventWithChoices(SwingGameController.java:617)
        at magic.ui.SwingGameController.executeNextEvent(SwingGameController.java:734)
        at magic.ui.SwingGameController.executeNextEventOrPhase(SwingGameController.java:722)
        at magic.ui.SwingGameController.runGame(SwingGameController.java:666)
        at magic.ui.duel.DuelPanel$2$1.run(DuelPanel.java:127)
Caused by: java.lang.ClassCastException
```

**Comment by ShawnieBoy** [comment]
Damnit - it's just me and getPlayer(), getRefPlayer() again!!
Sry
