### ISSUE TITLE
Mark of Eviction

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#349]
With the new error reporting I've got this crash

```
Exception from controller.runGame: java.util.ConcurrentModificationException
magic.exception.GameException: java.util.ConcurrentModificationException
	at magic.model.MagicGame.doAction(MagicGame.java:566)
	at magic.model.phase.MagicPhase.executePhase(MagicPhase.java:43)
	at magic.model.MagicGame.executePhase(MagicGame.java:480)
	at magic.model.MagicGame.advanceToNextEventWithChoice(MagicGame.java:794)
	at magic.ai.MCTSAI.getNextChoices(MCTSAI.java:483)
	at magic.ai.MCTSAI.growTree(MCTSAI.java:343)
	at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:239)
	at magic.ai.MCTSAI$1.execute(MCTSAI.java:148)
	at magic.ai.Task.run(Task.java:7)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.util.ConcurrentModificationException
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(Unknown Source)
	at java.util.TreeMap$KeyIterator.next(Unknown Source)
	at Mark_of_Eviction$1.executeEvent(Mark_of_Eviction.groovy:20)
	at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:659)
	at magic.model.MagicGame.executeEvent(MagicGame.java:775)
	at magic.model.stack.MagicItemOnStack.resolve(MagicItemOnStack.java:122)
	at magic.model.action.StackResolveAction.doAction(StackResolveAction.java:13)
	at magic.model.MagicGame.doAction(MagicGame.java:564)
	... 13 more
```

It's really not happy with the event.getRefPermanent() Even if I ignore it and use event.getPermanent().getEnchantedPermanent() I still get the same error. 

Groovy for reference:
```groovy
[
    new MagicAtYourUpkeepTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent,final MagicPlayer upkeepPlayer) {
            final MagicPermanent enchanted = permanent.getEnchantedPermanent()
            return enchanted.isValid() ? 
                new MagicEvent(
                    permanent,
                    enchanted,
                    this,
                    "Return RN and all Auras attached to that creature to their owners' hands."
                ) :
            MagicEvent.NONE;
        }

        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            final MagicPermanent enchanted = event.getRefPermanent();
            final Set<MagicPermanent> auras = enchanted.getAuraPermanents();
            for (final MagicPermanent aura : auras) {
                game.doAction(new RemoveFromPlayAction(aura, MagicLocationType.OwnersHand));
            }
            game.doAction(new RemoveFromPlayAction(enchanted, MagicLocationType.OwnersHand));
        }
    }
]
```

**Comment by ShawnieBoy** [comment]
Thinking about the error name, it could be that it needs to remove itself as part of the effect, so the effect source disappears?

**Comment by melvinzhang** [comment]
Using RemoveAllFromPlayAction should solve it. Should not modify a collection while looping over it. The action modifies the set returned by getAuraPermanents

**Comment by melvinzhang** [comment]
see release/Magarena/scripts/Scarab_of_the_Unseen.groovy
