### ISSUE TITLE
AI crash from activating Transluminant/Giant Caterpillar

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#362]
AI activated Transluminant on its own turn and generated this error.
```
Exception from controller.runGame: Index: 5, Size: 3
java.lang.IndexOutOfBoundsException: Index: 5, Size: 3
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at magic.ai.MCTSAI.growTree(MCTSAI.java:404)
        at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:239)
        at magic.ai.MCTSAI$1.run(MCTSAI.java:148)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by melvinzhang** [comment]
I'm unable to reproduce this. Can you create a test case?

**Comment by ShawnieBoy** [comment]
I've tried to duplicate it, but no luck

**Comment by melvinzhang** [comment]
unable to replicate.

**Comment by ShawnieBoy** [comment]
This looks like the same as #307

**Comment by melvinzhang** [comment]
Same issue with Giant Caterpillar
```
MCTS cheat=false index=1 life=8 turn=16 phase=FirstMain sims=498 time=1015
* [66/590/?] (pass)
  [65/427/?] (Downsize)
LOG (P): MMABC puts a 1/1 green Insect creature token with flying named Butterfly onto the battlefield at the beginning of the next end step.
CACHE HIT
HIT  : GAME: id=-997508304774583030 t=16 p=FirstMain s=OtherPlayer tp=0 lp=0 ppc=5 pp=true sc=false x=0 e=1 s=0
16 2030937207 1466408595 0 0 1 5 1 1 -1 4776293161289454514 382790725146443516 382790725146443516 3074026649660989021 -606811616556353797 2906986742408042396 10000001 1737895306650325711 -5869944701610222753 382790725146443516
2 0 0 0 0 0 0 1 7 1 0 0 5148243289684306330 -8897871045087686669 1342649868048261334 382790725146443516 4802688072623158199 0 6 1688110989 0
8 0 0 0 0 0 0 0 7 0 1 0 4216006170852515320 563093251288724354 3000743137169129306 382790725146443516 3118122963554139830 0 -1 0 0
MCTS cached=590
ADDED: GAME: id=1589541301896435865 t=16 p=FirstMain s=OtherPlayer tp=0 lp=0 ppc=5 pp=false sc=true x=0 e=2 s=1
16 2030937207 1466408595 0 0 1 5 1 -1 1 4776293161289454514 3465326937035470869 382790725146443516 5658160278998217691 -2687345933855832699 -5257027265805301963 23941 1737895306650325711 -5869944701610222753 382790725146443516
2 0 0 0 0 0 0 1 7 1 0 0 5148243289684306330 -8897871045087686669 1342649868048261334 382790725146443516 4802688072623158199 0 -1 -1 0
8 0 0 0 0 0 0 0 7 0 1 0 4337458885904222155 563093251288724354 3000743137169129306 382790725146443516 -4149162168918964862 0 3 176263389 0
ADDED: GAME: id=9006129203027052593 t=16 p=DeclareBlockers s=ActivePlayer tp=0 lp=0 ppc=0 pp=false sc=false x=0 e=1 s=0
16 1272550416 1551446957 0 0 1 0 1 -1 -1 4776293161289454514 382790725146443516 382790725146443516 8787636571344813325 2541677443712843593 -3028905657112911633 10000001 -2321204278167649313 -5869944701610222753 382790725146443516
2 0 0 0 0 0 0 1 7 1 0 2 5148243289684306330 -8897871045087686669 1342649868048261334 382790725146443516 -4543902360125239871 0 -1 -1 0
8 0 0 0 0 0 0 0 7 0 1 0 4216006170852515320 563093251288724354 3000743137169129306 382790725146443516 3118122963554139830 0 -1 -1 0
 -> pass -> Downsize -> Nantuko Mentor -> [] -> [] -> Nantuko Mentor -> c3-w2-x0-0-0-0-0-0-2-0
PAREN: Butterfly
PAREN: Nantuko Mentor
PAREN: Stampeding Elk Herd
CHILD: Butterfly
CHILD: Nantuko Mentor
CHILD: Stampeding Elk Herd
GAME : Butterfly
GAME : Butterfly
GAME : Nantuko Mentor
GAME : Stampeding Elk Herd
```

**Comment by lodici** [comment]
Just got a similar crash with latest 1.70 build. I was playing FX_Counter deck and MCTSC L4 was playing FX_Burn. Right at start of game, I had played a land and it was AI's turn.
```
CRASH REPORT FOR MAGARENA THREAD Thread[pool-10-thread-3,5,main]
CREATED ON 2016/01/04 01:40:09
MAGARENA VERSION 1.70, JRE 1.8.0_66, OS Linux_3.19.0-32-generic amd64
================================
Used Memory: 219M
Free Memory: 135M
Total Memory: 354M
Max Memory: 455M
================================
-Dfile.encoding=UTF-8
-DjarFile=dist\magarena-github.jar
-DdevMode=true
-Dmagarena.dir=release
-ea
-Xmx512m


Turn : 3  Phase : FirstMain  Step : ActivePlayer  Player : Monty Carlo  Score : 1037
0] Player : Tester  Life : 1  Delayed : Total=0
   - Hand : Island
   - Hand : Island
   - Hand : Island
   - Hand : Narcolepsy
   - Hand : Vapor Snag
   - Hand : Ætherize
   - Hand : Counterspell
   - Permanent : Island  Summoned
1] Player : Monty Carlo  Life : 1  Delayed : Total=0
   - Hand : Bonfire of the Damned
   - Hand : Mountain
   - Hand : Mountain
   - Hand : Flame Slash
   - Hand : Mountain
   - Hand : Fire Servant
Stack : 0
1. AddEventAction (EVENT: NONE Tester may$ take a mulligan. ) = 0
2. AddEventAction (EVENT: NONE Monty Carlo may$ take a mulligan. ) = 0
3. ExecuteFirstEventAction = 0
4. ExecuteFirstEventAction = 0
5. ShuffleCardsIntoLibraryAction = 0
6. ShiftCardAction = 0
7. RemoveCardAction (Lightning Bolt) = 650
8. MoveCardAction (Lightning Bolt,OwnersHand,TopOfOwnersLibrary) = 0
9. ShiftCardAction = 0
10. RemoveCardAction (Mountain) = 375
11. MoveCardAction (Mountain,OwnersHand,TopOfOwnersLibrary) = 0
12. ShiftCardAction = 0
13. RemoveCardAction (Mountain) = 375
14. MoveCardAction (Mountain,OwnersHand,TopOfOwnersLibrary) = 0
15. ShiftCardAction = 0
16. RemoveCardAction (Goblin Fireslinger) = 395
17. MoveCardAction (Goblin Fireslinger,OwnersHand,TopOfOwnersLibrary) = 0
18. ShiftCardAction = 0
19. RemoveCardAction (Mountain) = 375
20. MoveCardAction (Mountain,OwnersHand,TopOfOwnersLibrary) = 0
21. ShiftCardAction = 0
22. RemoveCardAction (Mountain) = 375
23. MoveCardAction (Mountain,OwnersHand,TopOfOwnersLibrary) = 0
24. ShiftCardAction = 0
25. RemoveCardAction (Chandra's Spitfire) = 394
26. MoveCardAction (Chandra's Spitfire,OwnersHand,TopOfOwnersLibrary) = 0
27. ShuffleLibraryAction = 0
28. DrawAction = -2934
29. AddEventAction (EVENT: NONE Monty Carlo may$ take a mulligan. ) = 0
30. ExecuteFirstEventAction = 0
31. ShuffleCardsIntoLibraryAction = 0
32. ShiftCardAction = 0
33. RemoveCardAction (Thundermaw Hellkite) = 410
34. MoveCardAction (Thundermaw Hellkite,OwnersHand,TopOfOwnersLibrary) = 0
35. ShiftCardAction = 0
36. RemoveCardAction (Lightning Bolt) = 650
37. MoveCardAction (Lightning Bolt,OwnersHand,TopOfOwnersLibrary) = 0
38. ShiftCardAction = 0
39. RemoveCardAction (Mountain) = 375
40. MoveCardAction (Mountain,OwnersHand,TopOfOwnersLibrary) = 0
41. ShiftCardAction = 0
42. RemoveCardAction (Mizzium Mortars) = 648
43. MoveCardAction (Mizzium Mortars,OwnersHand,TopOfOwnersLibrary) = 0
44. ShiftCardAction = 0
45. RemoveCardAction (Thundermaw Hellkite) = 410
46. MoveCardAction (Thundermaw Hellkite,OwnersHand,TopOfOwnersLibrary) = 0
47. ShiftCardAction = 0
48. RemoveCardAction (Devil's Play) = 441
49. MoveCardAction (Devil's Play,OwnersHand,TopOfOwnersLibrary) = 0
50. ShuffleLibraryAction = 0
51. DrawAction = -2320
52. AddEventAction (EVENT: NONE Monty Carlo may$ take a mulligan. ) = 0
53. ExecuteFirstEventAction = 0
54. AddEventAction (EVENT: NONE  Move this card from the top of the library to the bottom?) = 0
55. ExecuteFirstEventAction = 0
56. ScryAction = 0
57. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
58. ExecuteFirstEventAction = 0
59. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
60. ExecuteFirstEventAction = 0
61. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
62. ExecuteFirstEventAction = 0
63. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
64. ExecuteFirstEventAction = 0
65. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
66. ExecuteFirstEventAction = 0
67. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
68. ExecuteFirstEventAction = 0
69. AddEventAction (EVENT: NONE  Declare attackers.) = 0
70. ExecuteFirstEventAction = 0
71. DeclareAttackersAction = 0
72. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
73. ExecuteFirstEventAction = 0
74. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
75. ExecuteFirstEventAction = 0
76. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
77. ExecuteFirstEventAction = 0
78. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
79. ExecuteFirstEventAction = 0
80. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
81. ExecuteFirstEventAction = 0
82. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
83. ExecuteFirstEventAction = 0
84. ReturnExiledAction = 0
85. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
86. ExecuteFirstEventAction = 0
87. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
88. ExecuteFirstEventAction = 0
89. CleanupTurnTriggersAction = 0
90. CleanupPlayerAction = 0
91. CleanupPlayerAction = 0
92. CleanupTurnStaticsAction = 0
93. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
94. ExecuteFirstEventAction = 0
95. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
96. ExecuteFirstEventAction = 0
97. DrawAction = 440
98. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
99. ExecuteFirstEventAction = 0
100. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
101. ExecuteFirstEventAction = 0
102. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
103. MarkerAction = 0
104. LogMarkerAction = 0
105. ExecuteFirstEventAction = 0
106. AddEventAction (EVENT: Island Play <Island~1000060>. ) = 0
107. ExecuteFirstEventAction = 0
108. RemoveCardAction (Island) = -375
109. PlayCardAction = 0
110. AddEventAction (EVENT: Island Put <Island~1000060> onto the battlefield. ) = 0
111. ExecuteFirstEventAction = 0
112. PlayCardFromStackAction (Island) = 679
113. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
114. ExecuteFirstEventAction = 0
115. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
116. ExecuteFirstEventAction = 0
117. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
118. ExecuteFirstEventAction = 0
119. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
120. ExecuteFirstEventAction = 0
121. AddEventAction (EVENT: NONE  Declare attackers.) = 0
122. ExecuteFirstEventAction = 0
123. DeclareAttackersAction = 0
124. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
125. ExecuteFirstEventAction = 0
126. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
127. ExecuteFirstEventAction = 0
128. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
129. ExecuteFirstEventAction = 0
130. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
131. ExecuteFirstEventAction = 0
132. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
133. ExecuteFirstEventAction = 0
134. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
135. ExecuteFirstEventAction = 0
136. ReturnExiledAction = 0
137. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
138. ExecuteFirstEventAction = 0
139. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
140. ExecuteFirstEventAction = 0
141. CleanupTurnTriggersAction = 0
142. CleanupPlayerAction = 0
143. CleanupPermanentAction = 0
144. CleanupPlayerAction = 0
145. CleanupTurnStaticsAction = 0
146. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
147. ExecuteFirstEventAction = 0
148. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
149. ExecuteFirstEventAction = 0
150. DrawAction = -326
151. AddEventAction (EVENT: NONE  ...) = 0
152. ExecuteFirstEventAction = 0
153. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
154. ExecuteFirstEventAction = 0
155. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
156. ExecuteFirstEventAction = 0
157. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
Score = 1037

Exception from controller.runGame: ERROR! Inconsistent node found
GAME: id=0 t=4 p=Cleanup s=NextPhase tp=0 lp=0 ppc=0 pp=false sc=false x=0 e=1 s=0 true true
java.lang.AssertionError: ERROR! Inconsistent node found
GAME: id=0 t=4 p=Cleanup s=NextPhase tp=0 lp=0 ppc=0 pp=false sc=false x=0 e=1 s=0 true true
	at magic.ai.MCTSAI.growTree(MCTSAI.java:362)
	at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:239)
	at magic.ai.MCTSAI$1.run(MCTSAI.java:146)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by melvinzhang** [comment]
Thanks, I see the problem now. They were referring to the sacrificed permanent in the delayed trigger, this is problematic because the sacrificed permanent is not copied in the AI's simulation of the game.

**Comment by melvinzhang** [comment]
They should be implemented in the style of Grave Betrayal. Fix incoming.

**Comment by melvinzhang** [comment]
Unfortunately I'm able to replicate the crash in a test game, so I could not confirm if the delayed trigger fix actually worked. I just realized it will be very useful to have a game snapshot at the point of the crash, the crash reporter gets a copy of the MagicGame, so it should be possible to save it as a snapshot. 

The simple hand and permanents output of the reporter is there to help us replicate the state but having a proper snapshot will be much more useful and less work required on our part.

**Comment by melvinzhang** [comment]
created https://github.com/magarena/magarena/issues/627 for the snapshot during crash suggestion

**Comment by melvinzhang** [comment]
Delayed trigger fix seems to have worked, have not observed this bug during CI testing for a while.
