### ISSUE TITLE
Call of the Wild Crash

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#365]
I think that on a similar vein to #364, Call of the Wild is producing a crash - while mechanically similar to Skyward Eye Prophets, it can be activated multiple times in a turn.

Here is the crash:
```
Exception from controller.runGame: magic.exception.GameException: java.lang.RuntimeException: getGame called for MagicPlayer.NONE
magic.exception.GameException: magic.exception.GameException: java.lang.RuntimeException: getGame called for MagicPlayer.NONE
	at magic.model.MagicGame.doAction(MagicGame.java:566)
	at magic.model.phase.MagicPhase.executePhase(MagicPhase.java:43)
	at magic.model.MagicGame.executePhase(MagicGame.java:480)
	at magic.model.MagicGame.advanceToNextEventWithChoice(MagicGame.java:794)
	at magic.ai.MCTSAI.runSimulation(MCTSAI.java:452)
	at magic.ai.MCTSAI.randomPlay(MCTSAI.java:428)
	at magic.ai.MCTSAI.access$000(MCTSAI.java:63)
	at magic.ai.MCTSAI$2.run(MCTSAI.java:189)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: magic.exception.GameException: java.lang.RuntimeException: getGame called for MagicPlayer.NONE
	at magic.model.MagicGame.doAction(MagicGame.java:566)
	at Call_of_the_Wild$1.executeEvent(Call_of_the_Wild.groovy:28)
	at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:659)
	at magic.model.MagicGame.executeEvent(MagicGame.java:775)
	at magic.model.stack.MagicItemOnStack.resolve(MagicItemOnStack.java:122)
	at magic.model.action.StackResolveAction.doAction(StackResolveAction.java:13)
	at magic.model.MagicGame.doAction(MagicGame.java:564)
	... 10 more
Caused by: java.lang.RuntimeException: getGame called for MagicPlayer.NONE
	at magic.model.MagicPlayer$1.getGame(MagicPlayer.java:42)
	at magic.model.MagicCard.getGame(MagicCard.java:392)
	at magic.model.stack.MagicItemOnStack.<init>(MagicItemOnStack.java:38)
	at magic.model.stack.MagicItemOnStack.<init>(MagicItemOnStack.java:46)
	at magic.model.stack.MagicCardOnStack.<init>(MagicCardOnStack.java:43)
	at magic.model.stack.MagicCardOnStack.<init>(MagicCardOnStack.java:60)
	at magic.model.action.PlayCardAction.doAction(PlayCardAction.java:44)
	at magic.model.MagicGame.doAction(MagicGame.java:564)
	... 16 more
```
Groovy file: 
```
[
    new MagicPermanentActivation(
        new MagicActivationHints(MagicTiming.Draw),
        "Reveal"
    ) {
        @Override
        public Iterable<MagicEvent> getCostEvent(final MagicPermanent source) {
            return [new MagicPayManaCostEvent(source, "{2}{G}{G}")];
        }

        @Override
        public MagicEvent getPermanentEvent(final MagicPermanent source, final MagicPayedCost payedCost) {
            return new MagicEvent(
                source,
                this,
                "PN reveals the top card of his or her library. If it's a creature card, "+
                "PN puts it onto the battlefield. Otherwise, PN puts it into his or her graveyard."
            );
        }

        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            final MagicPlayer player = event.getPlayer();
            final MagicCard card = player.getLibrary().getCardAtTop();
            game.doAction(new RevealAction(card));
            if (card.hasType(MagicType.Creature)) {
                game.doAction(new RemoveCardAction(card, MagicLocationType.OwnersLibrary));
                game.doAction(new PlayCardAction(card, player));
            } else {
                game.doAction(new RemoveCardAction(card, MagicLocationType.OwnersLibrary));
                game.doAction(new MoveCardAction(card, MagicLocationType.OwnersLibrary, MagicLocationType.Graveyard));
            }
        }
    }
]
```
And Skyward Eye Prophets (which doesn't crash) for comparison.
```
[
    new MagicPermanentActivation(
        new MagicActivationHints(MagicTiming.Draw),
        "Reveal"
    ) {
        @Override
        public Iterable<MagicEvent> getCostEvent(final MagicPermanent source) {
            return [new MagicTapEvent(source)];
        }

        @Override
        public MagicEvent getPermanentEvent(final MagicPermanent source, final MagicPayedCost payedCost) {
            return new MagicEvent(
                source,
                this,
                "PN reveals the top card of his or her library. If it's a land card, "+
                "PN puts it onto the battlefield. Otherwise, PN puts it into his or her hand."
            );
        }

        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            final MagicPlayer player = event.getPlayer();
            final MagicCard card = player.getLibrary().getCardAtTop();
            game.doAction(new RevealAction(card));
            if (card.hasType(MagicType.Land)) {
                game.doAction(new RemoveCardAction(card, MagicLocationType.OwnersLibrary));
                game.doAction(new PlayCardAction(card, player));
            } else {
                game.doAction(new RemoveCardAction(card, MagicLocationType.OwnersLibrary));
                game.doAction(new MoveCardAction(card, MagicLocationType.OwnersLibrary, MagicLocationType.OwnersHand));
            }
        }
    }
]
```

**Comment by melvinzhang** [comment]
Both groovy are do not handle the empty library case where getCardAtTop returns MagicCard.NONE. Should almost always use getCardAtTop(n) which returns a list of cards.

It should be:
```
for (MagicCard card : layer.getLibrary().getCardAtTop(1)) {
  game.doAction(new RevealAction(card))
  ...
}
```

**Comment by ShawnieBoy** [comment]
Ahh, of course - I think I stumbled into this before. Thanks for that
