### ISSUE TITLE
crash when activating ability that discards specific cards as cost

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#384]
```
65. UntapAction (Blood Crypt) = -5
66. UntapAction (Crosis's Catacombs) = -5
67. UntapAction (Mountain) = -5
68. UntapAction (Mountain) = -5
69. UntapAction (Mountain) = -5
70. UntapAction (Swamp) = -5
71. ChangeStateAction = 0
72. ChangeStateAction = 0
73. DrawAction = -300
74. AddEventAction (EVENT: NONE  ...) = 0
75. ExecuteFirstEventAction = 0
76. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
77. ExecuteFirstEventAction = 0
78. AddEventAction (EVENT: Volrath the Fallen Pay {1}{B}$. Choose how to pay the mana cost.) = 0
79. AddEventAction (EVENT: Volrath the Fallen MMABC discards a creature card$. Choose a creature card from your hand.) = 0
80. AddEventAction (EVENT: Volrath the Fallen Play activated ability of Volrath the Fallen. ) = 0
81. ExecuteFirstEventAction = 0
82. TapAction (Crosis's Catacombs) = 5
83. TapAction (Swamp) = 5
84. ExecuteFirstEventAction = 0
85. ExecuteFirstEventAction = 0
86. PutItemOnStackAction (MagicAbilityOnStack,Volrath the Fallen) = 1
87. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
88. ExecuteFirstEventAction = 0
89. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
90. ExecuteFirstEventAction = 0
91. StackResolveAction = 0
Score = 265

Exception from controller.runGame: java.lang.ClassCastException: magic.model.target.MagicTargetNone cannot be cast to magic.model.MagicCard
magic.exception.GameException: java.lang.ClassCastException: magic.model.target.MagicTargetNone cannot be cast to magic.model.MagicCard
        at magic.model.MagicGame.doAction(MagicGame.java:566)
        at magic.model.phase.MagicPhase.executePhase(MagicPhase.java:43)
        at magic.model.MagicGame.executePhase(MagicGame.java:480)
        at magic.model.MagicGame.advanceToNextEventWithChoice(MagicGame.java:794)
        at magic.ai.MCTSAI.runSimulation(MCTSAI.java:452)
        at magic.ai.MCTSAI.randomPlay(MCTSAI.java:428)
        at magic.ai.MCTSAI.access$000(MCTSAI.java:63)
        at magic.ai.MCTSAI$2.run(MCTSAI.java:189)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassCastException: magic.model.target.MagicTargetNone cannot be cast to magic.model.MagicCard
        at magic.model.event.MagicEvent.getRefCard(MagicEvent.java:357)
        at Volrath_the_Fallen$1.executeEvent(Volrath_the_Fallen.groovy:26)
        at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:659)
        at magic.model.MagicGame.executeEvent(MagicGame.java:775)
        at magic.model.stack.MagicItemOnStack.resolve(MagicItemOnStack.java:122)
        at magic.model.action.StackResolveAction.doAction(StackResolveAction.java:13)
        at magic.model.MagicGame.doAction(MagicGame.java:564)
        ... 10 more
```

**Comment by PalladiaMors** [comment]
My bad, didn't see this when I playtested this card. Looked really simple, but I guess that's why ShawnieBoy left this one out. Hopefully there's still time to remove it before the release?

**Comment by ShawnieBoy** [comment]
For some reason determining the payedCost.getTarget() of a restricted choice (e.g. Discard an Artifact/Creature etc.) always returns MagicTarget.NONE. A 'free' choice (Discard a Card) works fine. Not been able to determine the reason.

Gonna be a bit sporadic on here - middle of moving :grimacing:

**Comment by ShawnieBoy** [comment]
Could be due to the AI not really knowing what the card was which was discarded?

**Comment by lodici** [comment]
see also [failed Jenkins build #1497](https://buildhive.cloudbees.com/job/magarena/job/magarena/1497/consoleText).

**Comment by melvinzhang** [comment]
@ShawnieBoy I think you are on the right track, it is to do with how MCTS randomizes the hidden information during simulation. The opponent has creature card in hand, and could activate Volrath's ability, but when it went into the simulation the hidden cards (opponent's hand) is randomized and there is no longer any creature card.

@lodici what is the connection to #1497 I do not see the link between the crash in that build and this issue.

**Comment by lodici** [comment]
Apologies, they are unrelated.

**Comment by lodici** [comment]
Seemingly related [crashed build](https://buildhive.cloudbees.com/job/magarena/job/magarena/1581/console) (Call_for_Blood).

**Comment by ShawnieBoy** [comment]
The Call_for_Blood crash is due to having no legal targets available. Normally it would just not be cast, but as it's looking for information from the target it's getting to a crash-state.

**Comment by melvinzhang** [comment]
Looks like Shallow Grave is reanimating Call for Blood which it should not be able to do. Caused by an earlier simplification I made, which change it from "top creature card" to "top card". Working on a fix now.

**Comment by lodici** [comment]
[crashed build](https://buildhive.cloudbees.com/job/magarena/job/magarena/1606/console)

**Comment by melvinzhang** [comment]
also occurs for Slumbering Tora, which has "Discard a Spirit or Arcane card" as cost.
