### ISSUE TITLE
crash when executing the Magarena.sh file

### ISSUE THREAD

**Issue by franzerich** [magarena/magarena#400]
Since 1.61, i get the following crash report when i execute the .sh file:
```
CRASH REPORT FOR MAGARENA THREAD Thread[main,5,main]
CREATED ON 2015/07/18 16:15:35
MAGARENA VERSION 1.63, JRE 1.7.0_79, OS Linux_3.16.0-4-amd64 amd64
================================
Used Memory: 2M
Free Memory: 243M
Total Memory: 246M
Max Memory: 455M
================================
-Xms256M
-Xmx512M
-Xverify:none


Exception from controller.runGame: null
java.awt.HeadlessException
	at java.awt.SplashScreen.getSplashScreen(SplashScreen.java:117)
	at magic.MagicMain.setSplashScreen(MagicMain.java:85)
	at magic.MagicMain.main(MagicMain.java:32)
```

What is the Problem?

**Comment by lodici** [comment]
Try...

1. download latest version (1.63).
2. extract to a **new** folder and run sh.
3. if it fails, uninstall java. 
4. Install java **JDK**, not just java runtime environment (JRE).
5. repeat step 2.

**Comment by lodici** [comment]
Whilst working on something else entirely I inadvertently mangaged to replicate this error. 

It occurs if ``-Djava.awt.headless=true``. It is expected to be false. So either your ``sh`` has been updated or for some reason this VM setting is defaulting to true on your PC.

**Comment by pando85** [comment]
Still present:
```
$ ./Magarena.sh 
CRASH REPORT FOR MAGARENA THREAD Thread[main,5,main]
CREATED ON 2016/07/24 16:31:46
MAGARENA VERSION 1.74, JRE 1.8.0_102, OS Linux_4.4.13-1-MANJARO amd64
================================
Used Memory: 3M
Free Memory: 241M
Total Memory: 245M
Max Memory: 455M
================================
-Xms256M
-Xmx512M
-Xverify:none


Exception from controller.runGame: null
java.lang.ExceptionInInitializerError
	at magic.MagicMain.setSplashScreen(MagicMain.java:90)
	at magic.MagicMain.main(MagicMain.java:31)
Caused by: java.lang.RuntimeException: Failed to create '/opt/Magarena/Magarena/scripts_orig'.
	at magic.utility.MagicFileSystem.verifyDirectoryPath(MagicFileSystem.java:209)
	at magic.utility.MagicFileSystem$DataPath.<init>(MagicFileSystem.java:95)
	at magic.utility.MagicFileSystem$DataPath.<clinit>(MagicFileSystem.java:78)
	... 2 more
Caused by: java.nio.file.AccessDeniedException: /opt/Magarena/Magarena/scripts_orig
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at magic.utility.MagicFileSystem.verifyDirectoryPath(MagicFileSystem.java:207)
	... 4 more



Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "main"
```
```
$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

**Comment by melvinzhang** [comment]
Closing as there are no further updates on the issue.

**Comment by lodici** [comment]
See also #787 for an alternative solution.
