### ISSUE TITLE
Crash when opening deckbuilder

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#403]
Managed to get my pc set up somewhere (yay) so sorting out ORI addition.

Could just be my build, but I'm getting a crash when entering the Deckbuilder from the menu - Going into it from an existing deck from a duel is working fine.

```
java.lang.NullPointerException
	at magic.model.MagicCardDefinition.getRarity(MagicCardDefinition.java:338)
	at magic.data.CardStatistics.createStatistics(CardStatistics.java:94)
	at magic.data.CardStatistics.<init>(CardStatistics.java:82)
	at magic.ui.duel.viewer.DeckStatisticsViewer.setDeck(DeckStatisticsViewer.java:129)
	at magic.ui.deck.editor.DeckEditorScreenPanel.setSelectedCard(DeckEditorScreenPanel.java:73)
	at magic.ui.deck.editor.DeckEditorScreenPanel.<init>(DeckEditorScreenPanel.java:39)
	at magic.ui.screen.DeckEditorScreen.setScreenContent(DeckEditorScreen.java:83)
	at magic.ui.screen.DeckEditorScreen.<init>(DeckEditorScreen.java:79)
	at magic.ui.ScreenController.showDeckEditor(ScreenController.java:109)
	at magic.ui.screen.MainMenuScreen$4.actionPerformed(MainMenuScreen.java:100)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

I've tried clean builds etc. Just wondering if it's just me (It does happen :angry: )

**Comment by lodici** [comment]
Somehow you have managed to select a deck previously which has subsequently become invalid. However, it should definitely fail more gracefully. To manully fix for now, open ``general.cfg`` and delete the value against the ``MostRecentDeckFilename`` setting.

**Comment by ShawnieBoy** [comment]
Ahh, yes - I see now, was a test-deck for snow mana.
Having it open with no deck loaded instead would avoid that, if the current deck isn't valid (As what happens when trying to load an invalid deck)
