### ISSUE TITLE
MagicCardOnStack.getEvent returning MagicEvent.NONE causes crash

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#412]
reported by https://buildhive.cloudbees.com/job/magarena/job/magarena/1544/console
```
174. DrawAction = -272
175. AddEventAction (EVENT: NONE  ...) = 0
176. ExecuteFirstEventAction = 0
177. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
178. ExecuteFirstEventAction = 0
179. AddEventAction (EVENT: Putrid Imp Pay {B}$. Choose how to pay the mana cost.) = 0
180. AddEventAction (EVENT: Putrid Imp Play Putrid Imp. ) = 0
181. ExecuteFirstEventAction = 0
182. TapAction (Darkslick Shores) = 5
183. ExecuteFirstEventAction = 0
184. RemoveCardAction (Putrid Imp) = 400
185. PutItemOnStackAction (MagicCardOnStack,Putrid Imp) = 1
186. AddEventAction (EVENT: Putrid Imp  ) = 0
187. ExecuteFirstEventAction = 0
188. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
189. ExecuteFirstEventAction = 0
190. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
191. ExecuteFirstEventAction = 0
192. StackResolveAction = 0
193. PlayCardFromStackAction (Putrid Imp) = -953
194. ChangeStateAction = 0
195. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
Score = 146

Exception from controller.runGame: getTargetChoice called on MagicEvent.NONE
java.lang.RuntimeException: getTargetChoice called on MagicEvent.NONE
        at magic.model.event.MagicEvent$1.getTargetChoice(MagicEvent.java:80)
        at magic.model.target.MagicTargetFilterFactory$12.accept(MagicTargetFilterFactory.java:103)
        at magic.model.target.MagicTargetFilterFactory$12.accept(MagicTargetFilterFactory.java:101)
        at magic.model.target.MagicStackFilterImpl.filter(MagicStackFilterImpl.java:32)
        at magic.model.MagicGame.hasLegalTargets(MagicGame.java:1144)
        at magic.model.choice.MagicTargetChoice.hasOptions(MagicTargetChoice.java:505)
        at magic.model.event.MagicActivation.canPlay(MagicActivation.java:116)
        at magic.model.event.MagicSourceActivation.canPlay(MagicSourceActivation.java:26)
        at magic.model.choice.MagicPlayChoice.addValidChoices(MagicPlayChoice.java:78)
        at magic.model.choice.MagicPlayChoice.getArtificialOptions(MagicPlayChoice.java:68)
        at magic.model.choice.MagicChoice.getArtificialChoiceResults(MagicChoice.java:85)
```

**Comment by melvinzhang** [comment]
```
1245. AddFirstEventAction (EVENT: Uyo, Silent Prophet Return a land you control$ to its owner's hand. Choose a land you control.) = 0
1246. ExecuteFirstEventAction = 0
1247. RemoveFromPlayAction (Island,0) = 675
1248. RemoveFromCombatAction (Island) = 0
1249. MoveCardAction (Island,Play,OwnersHand) = -375
1250. RemoveTriggersStaticsAction = 0
1251. ExecuteFirstEventAction = 0
1252. PutItemOnStackAction (MagicAbilityOnStack,Uyo, Silent Prophet) = 1
1253. AddEventAction (EVENT: Uyo, Silent Prophet  Choose target instant or sorcery spell.) = 0
1254. ExecuteFirstEventAction = 0
1255. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1256. ExecuteFirstEventAction = 0
1257. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1258. ExecuteFirstEventAction = 0
1259. TapAction (Fountain of Youth) = -5
1260. AddEventAction (EVENT: Fountain of Youth Pay {2}$. Choose how to pay the mana cost.) = 0
1261. AddEventAction (EVENT: Fountain of Youth Play activated ability of Fountain of Youth. ) = 0
1262. ExecuteFirstEventAction = 0
1263. PayDelayedCostAction = 0
1264. ExecuteFirstEventAction = 0
1265. PutItemOnStackAction (MagicAbilityOnStack,Fountain of Youth) = -1
1266. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1267. ExecuteFirstEventAction = 0
1268. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1269. ExecuteFirstEventAction = 0
1270. StackResolveAction = 0
1271. ChangeLifeAction (MCTS,1) = 500
1272. ChangePlayerStateAction = 0
1273. AddStaticAction (MagicPermanent.NONE,magic.model.action.ChangePlayerStateAction$3@258dc3fd) = 0
1274. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1275. ExecuteFirstEventAction = 0
1276. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1277. ExecuteFirstEventAction = 0
1278. StackResolveAction = 0
1279. CopyCardOnStackAction (Gift of Estates) = 0
Score = -3948

Exception from controller.runGame: magic.exception.GameException: java.lang.RuntimeException: getTargetChoice called on MagicEvent.NONE
magic.exception.GameException: magic.exception.GameException: java.lang.RuntimeException: getTargetChoice called on MagicEvent.NONE
	at magic.model.MagicGame.doAction(MagicGame.java:566)
	at magic.model.phase.MagicPhase.executePhase(MagicPhase.java:43)
	at magic.model.MagicGame.executePhase(MagicGame.java:480)
	at magic.model.MagicGame.advanceToNextEventWithChoice(MagicGame.java:794)
	at magic.ai.MCTSAI.runSimulation(MCTSAI.java:452)
	at magic.ai.MCTSAI.randomPlay(MCTSAI.java:428)
	at magic.ai.MCTSAI.access$000(MCTSAI.java:63)
	at magic.ai.MCTSAI$2.run(MCTSAI.java:189)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: magic.exception.GameException: java.lang.RuntimeException: getTargetChoice called on MagicEvent.NONE
	at magic.model.MagicGame.doAction(MagicGame.java:566)
	at magic.model.event.MagicRuleEventAction$137$1.doAction(MagicRuleEventAction.java:2799)
	at magic.model.event.MagicEvent.processTargetCardOnStack(MagicEvent.java:593)
	at magic.model.event.MagicRuleEventAction$137.executeEvent(MagicRuleEventAction.java:2797)
	at magic.model.event.MagicRuleEventAction$164$1.executeEvent(MagicRuleEventAction.java:3758)
	at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:659)
	at magic.model.MagicGame.executeEvent(MagicGame.java:775)
	at magic.model.stack.MagicItemOnStack.resolve(MagicItemOnStack.java:122)
	at magic.model.action.StackResolveAction.doAction(StackResolveAction.java:13)
	at magic.model.MagicGame.doAction(MagicGame.java:564)
	... 10 more
Caused by: java.lang.RuntimeException: getTargetChoice called on MagicEvent.NONE
	at magic.model.event.MagicEvent$1.getTargetChoice(MagicEvent.java:80)
	at magic.model.action.CopyCardOnStackAction.doAction(CopyCardOnStackAction.java:22)
	at magic.model.MagicGame.doAction(MagicGame.java:564)
	... 19 more
```

**Comment by ShawnieBoy** [comment]
The Putrid Imp makes no sense to me - unless it's the threshold triggering while on the stack? (giving it +1/+1 and can't block) Could the 'can't block' be looking for a target instead of affecting itself?

**Comment by melvinzhang** [comment]
merge into #519
