### ISSUE TITLE
Crib Swap generating NPE when putting Changeling onto battlefield

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#413]
```
289. AddEventAction (EVENT: Crib Swap Pay {2}{W}$. Choose how to pay the mana cost.) = 0
290. AddEventAction (EVENT: Crib Swap Play Crib Swap. ) = 0
291. ExecuteFirstEventAction = 0
292. PayDelayedCostAction = 0
293. ExecuteFirstEventAction = 0
294. RemoveCardAction (Crib Swap) = -606
295. PutItemOnStackAction (MagicCardOnStack,Crib Swap) = -1
296. AddEventAction (EVENT: Crib Swap  Choose target creature.) = 0
297. AddEventAction (EVENT: Crib Swap  ) = 0
298. ExecuteFirstEventAction = 0
299. ExecuteFirstEventAction = 0
300. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
301. ExecuteFirstEventAction = 0
302. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
303. ExecuteFirstEventAction = 0
304. StackResolveAction = 0
305. RemoveFromPlayAction (Bramblesnap,0) = 942
306. RemoveFromCombatAction (Bramblesnap) = 0
307. MoveCardAction (Bramblesnap,Play,Exile) = 0
308. RemoveTriggersStaticsAction = 0
309. PlayTokenAction = 0
310. AddEventAction (EVENT: Changeling Put Changeling onto the battlefield. ) = 0
311. MoveCardAction (Crib Swap,Stack,Graveyard) = 0
312. ExecuteFirstEventAction = 0
313. PlayCardFromStackAction (Changeling) = 0
Score = 1190

Exception from controller.runGame: magic.exception.GameException: java.lang.NullPointerException
magic.exception.GameException: magic.exception.GameException: java.lang.NullPointerException
    at magic.model.MagicGame.doAction(MagicGame.java:566)
    at magic.model.MagicGame.executeNextEvent(MagicGame.java:836)
    at magic.model.MagicGame.advanceToNextEventWithChoice(MagicGame.java:796)
    at magic.ai.MCTSAI.runSimulation(MCTSAI.java:452)
    at magic.ai.MCTSAI.randomPlay(MCTSAI.java:428)
    at magic.ai.MCTSAI.access$000(MCTSAI.java:63)
    at magic.ai.MCTSAI$2.run(MCTSAI.java:189)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: magic.exception.GameException: java.lang.NullPointerException
    at magic.model.MagicGame.doAction(MagicGame.java:566)
    at magic.model.event.MagicPlayCardEvent$1.executeEvent(MagicPlayCardEvent.java:27)
    at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:659)
    at magic.model.MagicGame.executeEvent(MagicGame.java:775)
    at magic.model.action.ExecuteFirstEventAction.doAction(ExecuteFirstEventAction.java:18)
    at magic.model.MagicGame.doAction(MagicGame.java:564)
    ... 9 more
Caused by: java.lang.NullPointerException
    at magic.model.MagicCardDefinition.applyCDASubType(MagicCardDefinition.java:554)
    at magic.model.MagicPermanent.apply(MagicPermanent.java:466)
    at magic.model.MagicPermanent.updateProperties(MagicPermanent.java:435)
    at magic.model.MagicPermanent.update(MagicPermanent.java:416)
    at magic.model.MagicGame.update(MagicGame.java:574)
    at magic.model.action.PlayCardFromStackAction.doAction(PlayCardFromStackAction.java:73)
    at magic.model.MagicGame.doAction(MagicGame.java:564)
    ... 14 more
```

**Comment by ShawnieBoy** [comment]
Not been able to replicate - I'm assuming something strange occurring with the creature that is exiled, as the token enters the battlefield under the exiled creature's controllers control.

If the target creature, for some reason, didn't have a controller (as far as Magarena saw), that would give the NPE.

Only thing I can think of.
