### ISSUE TITLE
crash during removal of MagicChangePlayerStateAction in undo

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#43]
CRASH REPORT FOR MAGARENA THREAD Thread[pool-4822-thread-1,5,main]
CREATED ON 2014/12/01 15:38:15
MAGARENA VERSION 1.57, JRE 1.7.0_51, OS Linux_3.7.10-101.fc17.x86_64 amd64
================================
Used Memory: 168M
Free Memory: 120M
Total Memory: 288M
Max Memory: 494M
================================
-Xms256M
-Xmx512M
-Xverify:none
-Dcom.sun.management.jmxremote
-Dmagarena.dir=<https://buildhive.cloudbees.com/job/magarena/job/magarena/ws/release>
-Ddebug=false
-Dgame.log=1417444103.log
-Djava.awt.headless=true

Turn : 16  Phase : EndOfCombat  Step : NextPhase  Player : jenkins  Score : -244
0] Player : jenkins  Life : 9  Delayed : Total=0
   - Hand : Dictate of Erebos
   - Hand : Thraben Doomsayer
   - Hand : Woolly Spider
   - Permanent : Bayou  Tapped
   - Permanent : Boros Guildmage  Power : 2  Toughness : 2  Damage : 1  Tapped
   - Permanent : Darigaaz's Caldera
   - Permanent : Forest  Tapped
   - Permanent : Forest
   - Permanent : Ghalma's Warden  Power : 2  Toughness : 4  Damage : 2  Tapped
   - Permanent : Glimmerpoint Stag  Power : 3  Toughness : 3  Damage : 0  Summoned
   - Permanent : Neurok Replica  Power : 1  Toughness : 4  Damage : 0  Tapped
   - Permanent : Quest for Renewal
   - Permanent : Tainted Field  Tapped
   - Permanent : Tainted Field  Tapped
1] Player : Les Vegas  Life : 7  Delayed : Total=0
   - Hand : Gorilla Warrior
   - Hand : Dinrova Horror
   - Hand : Vivid Creek
   - Graveyard : Mothdust Changeling
   - Graveyard : Crafty Pathmage
   - Permanent : Crosis's Catacombs  Tapped
   - Permanent : Forest  Tapped
   - Permanent : Forest
   - Permanent : Hinterland Harbor  Tapped
   - Permanent : Salt Marsh  Tapped
   - Permanent : Sea Sprite  Power : 1  Toughness : 1  Damage : 0
   - Permanent : Tanglewalker  Power : 2  Toughness : 2  Damage : 2  Summoned
   - Permanent : Tuskguard Captain  Power : 2  Toughness : 3  Damage : 0  Tapped
Stack : 0
1. MagicMarkerAction = 0
2. MagicExecuteFirstEventAction = 0
3. MagicStackResolveAction = 0
4. MagicExileUntilEndOfTurnAction = 0
5. MagicRemoveFromPlayAction (Vampiric Link,0) = -711
6. MagicRemoveFromCombatAction (Vampiric Link) = 0
7. MagicMoveCardAction (Vampiric Link,Play,Exile) = 0
8. MagicRemoveTriggersStaticsAction = 0
9. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
10. MagicMarkerAction = 0
11. MagicExecuteFirstEventAction = 0
12. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
13. MagicExecuteFirstEventAction = 0
14. MagicAddEventAction (EVENT: NONE  Declare attackers.) = 0
15. MagicMarkerAction = 0
16. MagicExecuteFirstEventAction = 0
17. MagicDeclareAttackersAction = 0
18. MagicTapAction (Neurok Replica) = -10
19. MagicPutItemOnStackAction (MagicTriggerOnStack,Quest for Renewal) = -1
20. MagicAddEventAction (EVENT: Quest for Renewal  Proceed with "may" action?) = 0
21. MagicTapAction (Boros Guildmage) = -10
22. MagicPutItemOnStackAction (MagicTriggerOnStack,Quest for Renewal) = -1
23. MagicAddEventAction (EVENT: Quest for Renewal  Proceed with "may" action?) = 0
24. MagicTapAction (Ghalma's Warden) = -10
25. MagicPutItemOnStackAction (MagicTriggerOnStack,Quest for Renewal) = -1
26. MagicAddEventAction (EVENT: Quest for Renewal  Proceed with "may" action?) = 0
27. MagicDeclareAttackerAction = 0
28. MagicDeclareAttackerAction = 0
29. MagicDeclareAttackerAction = 0
30. MagicExecuteFirstEventAction = 0
31. MagicExecuteFirstEventAction = 0
32. MagicExecuteFirstEventAction = 0
33. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
34. MagicExecuteFirstEventAction = 0
35. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
36. MagicExecuteFirstEventAction = 0
37. MagicStackResolveAction = 0
38. MagicChangeCountersAction = 0
39. MagicStackResolveAction = 0
40. MagicChangeCountersAction = 0
41. MagicStackResolveAction = 0
42. MagicChangeCountersAction = 0
43. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
44. MagicExecuteFirstEventAction = 0
45. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
46. MagicExecuteFirstEventAction = 0
47. MagicAddEventAction (EVENT: NONE  Declare blockers.) = 0
48. MagicExecuteFirstEventAction = 0
49. MagicDeclareBlockersAction = 0
50. MagicDeclareBlockerAction = 0
51. MagicSetBlockerAction = 0
52. MagicDeclareBlockerAction = 0
53. MagicSetBlockerAction = 0
54. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
55. MagicExecuteFirstEventAction = 0
56. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
57. MagicExecuteFirstEventAction = 0
58. MagicCombatDamageAction = 0
59. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
60. MagicExecuteFirstEventAction = 0
61. MagicAddEventAction (EVENT: NONE  Play a card or ability.) = 0
62. MagicExecuteFirstEventAction = 0
63. MagicCombatDamageAction = 0
64. MagicDealDamageAction = 0
65. MagicDealDamageAction = 0
66. MagicDealDamageAction = 0
67. MagicDealDamageAction = 0
68. MagicDealDamageAction = 0
69. MagicChangeLifeAction (Les Vegas,-1) = 500
70. MagicChangePlayerStateAction = 0
71. MagicAddStaticAction (MagicPermanent.NONE,magic.model.action.MagicChangePlayerStateAction$3@33e2df95) = 0
72. MagicChangePlayerStateAction = 0
Score = -244

Exception from controller.runGame: nothing to remove
java.lang.RuntimeException: nothing to remove
        at magic.model.mstatic.MagicPermanentStaticMap.remove(MagicPermanentStaticMap.java:89)
        at magic.model.MagicGame.removeStatic(MagicGame.java:1198)
        at magic.model.action.MagicAddStaticAction.undoAction(MagicAddStaticAction.java:29)
        at magic.model.MagicGame.restore(MagicGame.java:599)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:178)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:220)
        at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:220)
        at magic.ai.MMAB$MMABWorker.evaluateGame(MMAB.java:245)
        at magic.ai.MMAB$1.run(MMAB.java:88)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)

**Comment by melvinzhang** [comment]
merge into #61
