### ISSUE TITLE
MagicBuilderManaCost.compress AssertionError: typeCount is inconsistent

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#431]
```
CRASH REPORT FOR MAGARENA THREAD Thread[pool-5-thread-2,5,main]
CREATED ON 2015/09/10 11:24:34
MAGARENA VERSION 1.65, JRE 1.8.0_45-internal, OS Linux_3.16.0-38-generic amd64
================================
Used Memory: 164M
Free Memory: 425M
Total Memory: 590M
Max Memory: 1774M
================================
-Dfile.encoding=UTF-8
-Dsun.java2d.opengl=true
-DjarFile=dist\magarena-github.jar
-DdevMode=true
-Dmagarena.dir=release
-ea


Turn : 1  Phase : FirstMain  Step : NextPhase  Player : Les Vegas  Score : 0
0] Player : lodici  Life : 20  Delayed : Total=0
   - Hand : Grave Titan
   - Hand : Maelstrom Pulse
   - Hand : Night's Whisper
   - Hand : Swamp
   - Hand : Swamp
   - Hand : Swamp
   - Hand : Swamp
1] Player : Les Vegas  Life : 20  Delayed : Total=0
   - Hand : Plains
   - Hand : Plains
   - Hand : Plains
   - Hand : Glorious Anthem
   - Hand : Glorious Anthem
   - Hand : Plains
   - Hand : Swords to Plowshares
Stack : 0
1. AddEventAction (EVENT: NONE SPR may$ take a mulligan. ) = 0
2. AddEventAction (EVENT: NONE Les Vegas may$ take a mulligan. ) = 0
3. ExecuteFirstEventAction = 0
4. ExecuteFirstEventAction = 0
5. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
6. ExecuteFirstEventAction = 0
7. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
8. ExecuteFirstEventAction = 0
9. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
10. ExecuteFirstEventAction = 0
11. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
12. ExecuteFirstEventAction = 0
Score = 0

Exception from controller.runGame: typeCount is inconsistent: typeCount = 4, compressedIndex = 3
java.lang.AssertionError: typeCount is inconsistent: typeCount = 4, compressedIndex = 3
	at magic.model.choice.MagicBuilderManaCost.compress(MagicBuilderManaCost.java:52)
	at magic.model.MagicManaCost.addTo(MagicManaCost.java:315)
	at magic.model.MagicManaCost.getBuilderCost(MagicManaCost.java:303)
	at magic.model.condition.MagicManaCostCondition.accept(MagicManaCostCondition.java:23)
	at magic.model.event.MagicPayManaCostEvent.isSatisfied(MagicPayManaCostEvent.java:39)
	at magic.model.event.MagicActivation.canPlay(MagicActivation.java:108)
	at magic.model.event.MagicSourceActivation.canPlay(MagicSourceActivation.java:26)
	at magic.model.choice.MagicPlayChoice.addValidChoices(MagicPlayChoice.java:78)
	at magic.model.choice.MagicPlayChoice.getArtificialOptions(MagicPlayChoice.java:68)
	at magic.model.choice.MagicChoice.getArtificialChoiceResults(MagicChoice.java:85)
	at magic.model.choice.MagicChoice.getSimulationChoiceResult(MagicChoice.java:102)
	at magic.model.event.MagicEvent.getSimulationChoiceResult(MagicEvent.java:412)
	at magic.ai.VegasWorker.runGame(VegasWorker.java:28)
	at magic.ai.VegasWorker.run(VegasWorker.java:43)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by melvinzhang** [comment]
Relate crash in CI
```


Turn : 1  Phase : FirstMain  Step : ActivePlayer  Player : MMABC  Score : 0
0] Player : MMABC  Life : 10  Delayed : Total=0
   - Hand : Mountain
   - Hand : Active Volcano
   - Hand : Elvish Handservant
   - Hand : Jayemdae Tome
   - Hand : Savage Lands
   - Hand : Forest
   - Hand : Rupture Spire
1] Player : MCTS  Life : 10  Delayed : Total=0
   - Hand : Forest
   - Hand : Axebane Stag
   - Hand : Forest
   - Hand : Brushstrider
   - Hand : Yavimaya Scion
   - Hand : Temple of Plenty
   - Hand : Reaping the Rewards
Stack : 0
1. AddEventAction (EVENT: NONE MMABC may$ take a mulligan. ) = 0
2. AddEventAction (EVENT: NONE MCTS may$ take a mulligan. ) = 0
3. ExecuteFirstEventAction = 0
4. ExecuteFirstEventAction = 0
5. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
Score = 0

Exception from controller.runGame: 1
java.lang.ArrayIndexOutOfBoundsException: 1
	at magic.model.choice.MagicBuilderManaCost.compress(MagicBuilderManaCost.java:46)
	at magic.model.MagicManaCost.addTo(MagicManaCost.java:315)
	at magic.model.MagicManaCost.getBuilderCost(MagicManaCost.java:303)
	at magic.model.condition.MagicManaCostCondition.accept(MagicManaCostCondition.java:23)
	at magic.model.event.MagicPayManaCostEvent.isSatisfied(MagicPayManaCostEvent.java:38)
	at magic.model.event.MagicActivation.canPlay(MagicActivation.java:108)
	at magic.model.event.MagicSourceActivation.canPlay(MagicSourceActivation.java:26)
	at magic.model.choice.MagicPlayChoice.addValidChoices(MagicPlayChoice.java:78)
	at magic.model.choice.MagicPlayChoice.getArtificialOptions(MagicPlayChoice.java:68)
	at magic.model.choice.MagicChoice.getArtificialChoiceResults(MagicChoice.java:86)
	at magic.model.event.MagicEvent.getArtificialChoiceResults(MagicEvent.java:402)
	at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:207)
	at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:188)
	at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:235)
	at magic.ai.MMAB$MMABWorker.runGame(MMAB.java:188)
	at magic.ai.MMAB$MMABWorker.evaluateGame(MMAB.java:260)
	at magic.ai.MMAB$1.run(MMAB.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by melvinzhang** [comment]
fixed by computing typeCount in compress so it does not have to be kept in sync manually.
