### ISSUE TITLE
change to CI that supports Java 8

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#449]
Buildhive does not have support for Java 8 and there is not much activity on the project.

**Comment by melvinzhang** [comment]
https://circleci.com/ provides 1 container for free and has integration with docker which can be used to customize the build environment

**Comment by lodici** [comment]
My first commit and it falls over! Perhaps I should change my name. 
```
CRASH REPORT FOR MAGARENA THREAD Thread[pool-354-thread-24,5,main]
CREATED ON 2015/09/30 15:19:33
MAGARENA VERSION 1.67, JRE 1.8.0_40, OS Linux_3.14.28-031428-generic amd64
================================
Used Memory: 212M
Free Memory: 117M
Total Memory: 330M
Max Memory: 455M
================================
-Xms256M
-Xmx512M
-Xverify:none
-Dcom.sun.management.jmxremote
-Dmagarena.dir=/home/ubuntu/magarena/release
-Ddebug=false
-Dgame.log=1443625948.log
-Djava.awt.headless=true


Turn : 5  Phase : FirstMain  Step : ActivePlayer  Player : MCTS  Score : 1759
0] Player : MMABC  Life : 10  Delayed : Total=0
   - Hand : Arrogant Wurm
   - Hand : Spiked Baloth
   - Hand : Darksteel Brute
   - Hand : Theft of Dreams
   - Hand : Skyshroud Sentinel
   - Hand : Thornwood Falls
   - Permanent : Forest  Tapped  Summoned
   - Permanent : Giant Tortoise  Power : 1  Toughness : 4  Damage : 0  Summoned
   - Permanent : Opulent Palace  Tapped
1] Player : MCTS  Life : 10  Delayed : Total=0
   - Hand : Snapping Thragg
   - Hand : Heartwood Dryad
   - Hand : Bull Elephant
   - Hand : Leaf Gilder
   - Graveyard : Rupture Spire
   - Permanent : Forest
   - Permanent : Forest
   - Permanent : No-Dachi
Stack : 0
1. AddEventAction (EVENT: NONE MMABC may$ take a mulligan. ) = 0
2. AddEventAction (EVENT: NONE MCTS may$ take a mulligan. ) = 0
3. ExecuteFirstEventAction = 0
4. ExecuteFirstEventAction = 0
5. ShiftCardAction = 0
6. RemoveCardAction (Bull Elephant) = 186
7. MoveCardAction (Bull Elephant,OwnersHand,OwnersLibrary) = 0
8. ShuffleIntoLibraryAction = 0
9. ShiftCardAction = 0
10. RemoveCardAction (Sakura-Tribe Scout) = 391
11. MoveCardAction (Sakura-Tribe Scout,OwnersHand,OwnersLibrary) = 0
12. ShuffleIntoLibraryAction = 0
13. ShiftCardAction = 0
14. RemoveCardAction (Forest) = 412
15. MoveCardAction (Forest,OwnersHand,OwnersLibrary) = 0
16. ShuffleIntoLibraryAction = 0
17. ShiftCardAction = 0
18. RemoveCardAction (Kazandu Refuge) = 487
19. MoveCardAction (Kazandu Refuge,OwnersHand,OwnersLibrary) = 0
20. ShuffleIntoLibraryAction = 0
21. ShiftCardAction = 0
22. RemoveCardAction (No-Dachi) = 333
23. MoveCardAction (No-Dachi,OwnersHand,OwnersLibrary) = 0
24. ShuffleIntoLibraryAction = 0
25. ShiftCardAction = 0
26. RemoveCardAction (Spearpoint Oread) = 296
27. MoveCardAction (Spearpoint Oread,OwnersHand,OwnersLibrary) = 0
28. ShuffleIntoLibraryAction = 0
29. ShiftCardAction = 0
30. RemoveCardAction (Humbler of Mortals) = 294
31. MoveCardAction (Humbler of Mortals,OwnersHand,OwnersLibrary) = 0
32. ShuffleIntoLibraryAction = 0
33. DrawAction = -2568
34. AddEventAction (EVENT: NONE MCTS may$ take a mulligan. ) = 0
35. ExecuteFirstEventAction = 0
36. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
37. ExecuteFirstEventAction = 0
38. AddEventAction (EVENT: Forest Play <Forest#1000073>. ) = 0
39. ExecuteFirstEventAction = 0
40. RemoveCardAction (Forest) = 412
41. PlayCardAction = 0
42. AddEventAction (EVENT: Forest Put <Forest#1000073> onto the battlefield. ) = 0
43. ExecuteFirstEventAction = 0
44. PlayCardFromStackAction (Forest) = -717
45. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
46. ExecuteFirstEventAction = 0
47. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
48. ExecuteFirstEventAction = 0
49. AddEventAction (EVENT: NONE  Declare attackers.) = 0
50. ExecuteFirstEventAction = 0
51. DeclareAttackersAction = 0
52. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
53. ExecuteFirstEventAction = 0
54. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
55. ExecuteFirstEventAction = 0
56. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
57. ExecuteFirstEventAction = 0
58. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
59. ExecuteFirstEventAction = 0
60. ReturnExiledAction = 0
61. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
62. ExecuteFirstEventAction = 0
63. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
64. ExecuteFirstEventAction = 0
65. CleanupTurnTriggersAction = 0
66. CleanupPlayerAction = 0
67. CleanupPlayerAction = 0
68. CleanupPermanentAction = 0
69. CleanupTurnStaticsAction = 0
70. DrawAction = 291
71. AddEventAction (EVENT: NONE  ...) = 0
72. ExecuteFirstEventAction = 0
73. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
74. ExecuteFirstEventAction = 0
75. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
76. ExecuteFirstEventAction = 0
77. AddEventAction (EVENT: NONE  Declare attackers.) = 0
78. ExecuteFirstEventAction = 0
79. DeclareAttackersAction = 0
80. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
81. ExecuteFirstEventAction = 0
82. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
83. ExecuteFirstEventAction = 0
84. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
85. ExecuteFirstEventAction = 0
86. AddEventAction (EVENT: Opulent Palace Play <Opulent Palace#1000025>. ) = 0
87. ExecuteFirstEventAction = 0
88. RemoveCardAction (Opulent Palace) = -637
89. PlayCardAction = 0
90. AddEventAction (EVENT: Opulent Palace Put <Opulent Palace#1000025> onto the battlefield. ) = 0
91. ExecuteFirstEventAction = 0
92. PlayCardFromStackAction (Opulent Palace) = 936
93. TapAction (Opulent Palace) = 0
94. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
95. ExecuteFirstEventAction = 0
96. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
97. ExecuteFirstEventAction = 0
98. ReturnExiledAction = 0
99. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
100. ExecuteFirstEventAction = 0
101. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
102. ExecuteFirstEventAction = 0
103. CleanupTurnTriggersAction = 0
104. CleanupPlayerAction = 0
105. CleanupPermanentAction = 0
106. CleanupPlayerAction = 0
107. CleanupPermanentAction = 0
108. CleanupTurnStaticsAction = 0
109. ChangeStateAction = 0
110. ChangeStateAction = 0
111. DrawAction = -186
112. AddEventAction (EVENT: NONE  ...) = 0
113. ExecuteFirstEventAction = 0
114. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
115. ExecuteFirstEventAction = 0
116. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
117. ExecuteFirstEventAction = 0
118. AddEventAction (EVENT: NONE  Declare attackers.) = 0
119. ExecuteFirstEventAction = 0
120. DeclareAttackersAction = 0
121. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
122. ExecuteFirstEventAction = 0
123. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
124. ExecuteFirstEventAction = 0
125. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
126. ExecuteFirstEventAction = 0
127. AddEventAction (EVENT: Forest Play <Forest#1000079>. ) = 0
128. ExecuteFirstEventAction = 0
129. RemoveCardAction (Forest) = 412
130. PlayCardAction = 0
131. AddEventAction (EVENT: Forest Put <Forest#1000079> onto the battlefield. ) = 0
132. ExecuteFirstEventAction = 0
133. PlayCardFromStackAction (Forest) = -716
134. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
135. ExecuteFirstEventAction = 0
136. AddEventAction (EVENT: No-Dachi Pay {2}$. Choose how to pay the mana cost.) = 0
137. AddEventAction (EVENT: No-Dachi Play <No-Dachi#1000050>. ) = 0
138. ExecuteFirstEventAction = 0
139. TapAction (Forest) = 5
140. TapAction (Forest) = 5
141. ExecuteFirstEventAction = 0
142. RemoveCardAction (No-Dachi) = 333
143. PutItemOnStackAction (MagicCardOnStack,No-Dachi) = 1
144. AddEventAction (EVENT: No-Dachi  ) = 0
145. ExecuteFirstEventAction = 0
146. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
147. ExecuteFirstEventAction = 0
148. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
149. ExecuteFirstEventAction = 0
150. StackResolveAction = 0
151. PlayCardFromStackAction (No-Dachi) = -737
152. ChangeStateAction = 0
153. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
154. ExecuteFirstEventAction = 0
155. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
156. ExecuteFirstEventAction = 0
157. ReturnExiledAction = 0
158. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
159. ExecuteFirstEventAction = 0
160. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
161. ExecuteFirstEventAction = 0
162. CleanupTurnTriggersAction = 0
163. CleanupPlayerAction = 0
164. CleanupPermanentAction = 0
165. CleanupPlayerAction = 0
166. CleanupPermanentAction = 0
167. CleanupPermanentAction = 0
168. CleanupPermanentAction = 0
169. CleanupTurnStaticsAction = 0
170. ChangeStateAction = 0
171. ChangeStateAction = 0
172. UntapAction (Opulent Palace) = 5
173. DrawAction = 466
174. AddEventAction (EVENT: NONE  ...) = 0
175. ExecuteFirstEventAction = 0
176. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
177. ExecuteFirstEventAction = 0
178. AddEventAction (EVENT: Forest Play <Forest#1000031>. ) = 0
179. ExecuteFirstEventAction = 0
180. RemoveCardAction (Forest) = -412
181. PlayCardAction = 0
182. AddEventAction (EVENT: Forest Put <Forest#1000031> onto the battlefield. ) = 0
183. ExecuteFirstEventAction = 0
184. PlayCardFromStackAction (Forest) = 715
185. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
186. ExecuteFirstEventAction = 0
187. AddEventAction (EVENT: Giant Tortoise Pay {1}{U}$. Choose how to pay the mana cost.) = 0
188. AddEventAction (EVENT: Giant Tortoise Play <Giant Tortoise#1000013>. ) = 0
189. ExecuteFirstEventAction = 0
190. TapAction (Forest) = -5
191. TapAction (Opulent Palace) = -5
192. ExecuteFirstEventAction = 0
193. RemoveCardAction (Giant Tortoise) = -303
194. PutItemOnStackAction (MagicCardOnStack,Giant Tortoise) = -1
195. AddEventAction (EVENT: Giant Tortoise  ) = 0
196. ExecuteFirstEventAction = 0
197. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
198. ExecuteFirstEventAction = 0
199. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
200. ExecuteFirstEventAction = 0
201. StackResolveAction = 0
202. PlayCardFromStackAction (Giant Tortoise) = 1396
203. ChangeStateAction = 0
204. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
205. ExecuteFirstEventAction = 0
206. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
207. ExecuteFirstEventAction = 0
208. AddEventAction (EVENT: NONE  Declare attackers.) = 0
209. ExecuteFirstEventAction = 0
210. DeclareAttackersAction = 0
211. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
212. ExecuteFirstEventAction = 0
213. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
214. ExecuteFirstEventAction = 0
215. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
216. ExecuteFirstEventAction = 0
217. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
218. ExecuteFirstEventAction = 0
219. ReturnExiledAction = 0
220. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
221. ExecuteFirstEventAction = 0
222. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
223. ExecuteFirstEventAction = 0
224. CleanupTurnTriggersAction = 0
225. CleanupPlayerAction = 0
226. CleanupPermanentAction = 0
227. CleanupPermanentAction = 0
228. CleanupPermanentAction = 0
229. CleanupPlayerAction = 0
230. CleanupPermanentAction = 0
231. CleanupPermanentAction = 0
232. CleanupPermanentAction = 0
233. CleanupTurnStaticsAction = 0
234. UntapAction (Forest) = -5
235. ChangeStateAction = 0
236. ChangeStateAction = 0
237. UntapAction (Forest) = -5
238. ChangeStateAction = 0
239. ChangeStateAction = 0
240. DrawAction = -240
241. AddEventAction (EVENT: NONE  ...) = 0
242. ExecuteFirstEventAction = 0
243. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
244. ExecuteFirstEventAction = 0
245. AddEventAction (EVENT: Rupture Spire Play <Rupture Spire#1000068>. ) = 0
246. ExecuteFirstEventAction = 0
247. RemoveCardAction (Rupture Spire) = 926
248. PlayCardAction = 0
249. AddEventAction (EVENT: Rupture Spire Put <Rupture Spire#1000068> onto the battlefield. ) = 0
250. ExecuteFirstEventAction = 0
251. PlayCardFromStackAction (Rupture Spire) = -1224
252. TapAction (Rupture Spire) = 0
253. EnqueueTriggerAction = 0
254. PutItemOnStackAction (MagicTriggerOnStack,Rupture Spire) = 1
255. AddEventAction (EVENT: Rupture Spire  Pay {1}? If you don't, sacrifice <Rupture Spire#1000068>.) = 0
256. DequeueTriggerAction = 0
257. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
258. ExecuteFirstEventAction = 0
259. ExecuteFirstEventAction = 0
260. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
261. ExecuteFirstEventAction = 0
262. StackResolveAction = 0
263. SacrificeAction (Rupture Spire,0) = 1221
264. RemoveFromCombatAction (Rupture Spire) = 0
265. MoveCardAction (Rupture Spire,Play,Graveyard) = 0
266. RemoveTriggersStaticsAction = 0
267. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
Score = 1763

Exception from controller.runGame: Task magic.ai.MCTSAI$1@4c4a2182 rejected from java.util.concurrent.ThreadPoolExecutor@49d28889[Shutting down, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 23]
java.util.concurrent.RejectedExecutionException: Task magic.ai.MCTSAI$1@4c4a2182 rejected from java.util.concurrent.ThreadPoolExecutor@49d28889[Shutting down, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 23]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:279)
	at magic.ai.MCTSAI$1.run(MCTSAI.java:148)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lodici** [comment]
Congrats for finding an alternative solution. :clap: Have you managed to create artifact links?

**Comment by lodici** [comment]
Also I suggest avoiding the term "Continuous Integration" on the main page - very long, very techy/geeky.

**Comment by melvinzhang** [comment]
Agree, please change it!

**Comment by melvinzhang** [comment]
The build artifacts show up when you view the build page while logged in to circleci. I've sent a support request asking of the build artifacts can also be shown on the public (without login) page.

**Comment by melvinzhang** [comment]
@lodici Do you get a notification from circleci when a build fails or do you have to check the page manually?

**Comment by lodici** [comment]
I don't have an account so I check the page manually. I actually have my own CI build monitor which I used for Jenkins and circleci has a REST api which I could use but again you need an account in order to obtain a token.

I guess artifacts (public) availability is not a huge issue - how many people actually download the dev builds on a regular basis? It's not like we have a dedicated team of testers.

I am not overly keen on the circleci site with its heavy use of javascript so I will probably steer clear of creating an account unless absolutely necessary but it does let us use Java 1.8 which I think is the main thing, you are able to run your AI tests and as long as you are able to create the GitHub download links for releases then I think we have everything we need.

**Comment by lodici** [comment]
Out of interest would circleci be able to handle the bundling of a JRE using something like packr or oracle's own self-containted packaging tools?

**Comment by melvinzhang** [comment]
I've sent invites for circleci in case anyone wants to keep track of build issues. When "follow" the build on circleci, you get email notifications of build issues.

Normally I create the github releases on my computer instead of using the CI as the CI job is set to run for about 2 hours.

With regards to bundling of JRE, it can be automated in CI. It is a Linux environment where we run the Makefile. So action that can be expressed as a Makefile rule can be automatically run by circleci. For instance, it currently runs the "circleci" rule in the Makefile.

**Comment by lodici** [comment]
I downloaded the latest 1.67 zip artifact (I created a circleci account!) and tried running the jar using java 1.7 and as expected it fell over. To cross check I trued running 1.66 and it worked fine.  However, Magarena.exe (1.67) does not work because I think it is looking for a 32 bit version of 1.7 and I don't have that installed on my PC. Possibly Launch4J needs updating to point to 1.8 as well?

**Comment by melvinzhang** [comment]
Thanks for spotting this. Fixed in https://github.com/magarena/magarena/commit/b196fb7ec7a60bb41480d122a2492eb1964ebb53
