### ISSUE TITLE
magic.ai.MCTSAI.TreeUpdate java.lang.InterruptedException

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#458]
see https://circleci.com/gh/magarena/magarena/5.

```
Exception from controller.runGame: java.lang.InterruptedException
java.lang.RuntimeException: java.lang.InterruptedException
	at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:227)
	at magic.ai.MCTSAI$1.run(MCTSAI.java:148)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:439)
	at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:225)
	... 4 more
```

**Comment by melvinzhang** [comment]
Similarly issue
```
Exception from controller.runGame: Task magic.ai.MCTSAI$1@4c4a2182 rejected from java.util.concurrent.ThreadPoolExecutor@49d28889[Shutting down, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 23]
java.util.concurrent.RejectedExecutionException: Task magic.ai.MCTSAI$1@4c4a2182 rejected from java.util.concurrent.ThreadPoolExecutor@49d28889[Shutting down, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 23]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
    at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:279)
    at magic.ai.MCTSAI$1.run(MCTSAI.java:148)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by melvinzhang** [comment]
no longer observed in CI, looks like 5ba1abf2de7cda736efecf0a5b523a7e795dbc10 worked
