### ISSUE TITLE
1.66 crashes when there's more than one card face down

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#474]
Also, since I upgraded to java 8, the game crashes when there's more than one card face down in play.
I thought it had something to do with the new java version, so I waited for a new java update, but the problem persit 
--  by jerichopumpkin @ http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=17748&p=187847&sid=78e55cdc4d35fec6b2535022f9e3399e#p187847
![crash](https://cloud.githubusercontent.com/assets/1620634/10709980/0b4566b8-7a75-11e5-99de-2550d08c45f9.png)
[crash.txt](https://github.com/magarena/magarena/files/19922/crash.txt)

@lodici seems to be an issue with TComponentBuilder

**Comment by lodici** [comment]
Tried replicating with TestMorph - so far no joy.

**Comment by melvinzhang** [comment]
I'm able to replicate via TestMorph.

1. Cast Backslide, targetting one of the Thousand Winds to turn it facedown
2. Attack with the facedown Thousand Winds
3. Crash with the following exception
```
Exception from controller.runGame: String index out of range: -3
java.lang.StringIndexOutOfBoundsException: String index out of range: -3
        at java.lang.String.substring(String.java:1967)
        at magic.ui.message.TComponentBuilder.buildTComponents(TComponentBuilder.java:133)
        at magic.ui.message.TextLabel.<init>(TextLabel.java:59)
        at magic.ui.duel.sidebar.MessagePanel.setMessagePanelLayout(MessagePanel.java:68)
        at magic.ui.duel.sidebar.MessagePanel.<init>(MessagePanel.java:39)
        at magic.ui.duel.sidebar.LogViewer.getNewMessagePanel(LogViewer.java:71)
        at magic.ui.duel.sidebar.LogViewer.update(LogViewer.java:62)
        at magic.ui.duel.sidebar.DuelSideBarPanel.doUpdate(DuelSideBarPanel.java:117)
        at magic.ui.duel.DuelPanel.update(DuelPanel.java:209)
        at magic.ui.SwingGameController$11.run(SwingGameController.java:604)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by lodici** [comment]
Thanks - I can replicate as well.

**Comment by lodici** [comment]
It is because the card ID delimiter is the hash character but when playing morph the card is named "Permanent #<id+1>", so for example you end up with the log card name token as "<Permanent #22#21>". The simple fix is to use a different delimiter for the card id, one that has no chance of being present in the card name - I am considering using the "^" character such that the raw log would look like
```
(P): Tap <Island^27>. Tap <Island^29>. Pay {1}{U}. Play <Backslide^48>.
(P): Turn target creature with a morph ability face down (<Thousand Winds^21>).
(P): Player attacks with <Permanent #22^21>.
```
Can anyone see this causing problems?

**Comment by lodici** [comment]
Can't use "^" as it is a regex character. Looking at "~" instead.

**Comment by lodici** [comment]
Checked ``AllCardNames.txt`` and ``~`` is not present so used this character as the delimiter.
