### ISSUE TITLE
activating Manacles of Decay {R} ability causes crash

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#475]
```
Exception from controller.runGame: java.lang.ClassCastException: magic.model.MagicCard$1 cannot be cast to magic.model.MagicPermanent
magic.exception.GameException: java.lang.ClassCastException: magic.model.MagicCard$1 cannot be cast to magic.model.MagicPermanent
    at magic.model.MagicGame.doAction(MagicGame.java:554)
    at magic.model.phase.MagicPhase.executePhase(MagicPhase.java:43)
    at magic.model.MagicGame.executePhase(MagicGame.java:468)
    at magic.model.MagicGame.advanceToNextEventWithChoice(MagicGame.java:782)
    at magic.ai.MCTSAI.runSimulation(MCTSAI.java:464)
    at magic.ai.MCTSAI.randomPlay(MCTSAI.java:440)
    at magic.ai.MCTSAI.access$000(MCTSAI.java:64)
    at magic.ai.MCTSAI$2.run(MCTSAI.java:190)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: magic.model.MagicCard$1 cannot be cast to magic.model.MagicPermanent
    at magic.model.target.MagicTargetFilterFactory$98.accept(MagicTargetFilterFactory.java:929)
    at magic.model.target.MagicTargetFilterFactory$98.accept(MagicTargetFilterFactory.java:927)
    at magic.model.target.MagicPermanentFilterImpl.filter(MagicPermanentFilterImpl.java:31)
    at magic.model.target.MagicPermanentFilterImpl.filter(MagicPermanentFilterImpl.java:18)
    at magic.model.event.MagicRuleEventAction$155$1$1.modGame(MagicRuleEventAction.java:3259)
    at magic.model.MagicGame.apply(MagicGame.java:594)
    at magic.model.MagicGame.update(MagicGame.java:607)
    at magic.model.MagicGame.update(MagicGame.java:576)
    at magic.model.MagicGame.executeEvent(MagicGame.java:764)
    at magic.model.stack.MagicItemOnStack.resolve(MagicItemOnStack.java:122)
    at magic.model.action.StackResolveAction.doAction(StackResolveAction.java:13)
    at magic.model.MagicGame.doAction(MagicGame.java:552)
    ... 10 more
```

**Comment by melvinzhang** [comment]
bug in magic.model.event.MagicRuleEventAction$155$1$1.modGame(MagicRuleEventAction.java:3259)
