### ISSUE TITLE
choice does not match event when trying to execute event during growTree

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#479]
Game state is always with exactly one action:
```
 Stack : 0                                                                                                                                                                                     
 1. ExecuteFirstEventAction = 0                                                                                                                                                                
 Score = 0
```

Stack traces:
```
Exception from controller.runGame: java.lang.ClassCastException: magic.model.choice.MagicDeclareAttackersResult cannot be cast to magic.model.choice.MagicPlayChoiceResult
magic.exception.GameException: java.lang.ClassCastException: magic.model.choice.MagicDeclareAttackersResult cannot be cast to magic.model.choice.MagicPlayChoiceResult
    at magic.model.MagicGame.doAction(MagicGame.java:554)
    at magic.model.MagicGame.executeNextEvent(MagicGame.java:820)
    at magic.ai.MCTSAI.growTree(MCTSAI.java:404)
    at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:239)
    at magic.ai.MCTSAI$1.run(MCTSAI.java:148)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: magic.model.choice.MagicDeclareAttackersResult cannot be cast to magic.model.choice.MagicPlayChoiceResult
    at magic.model.event.MagicEvent.getPlayChoice(MagicEvent.java:498)
    at magic.model.event.MagicPriorityEvent$1.executeEvent(MagicPriorityEvent.java:17)
    at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:659)
    at magic.model.MagicGame.executeEvent(MagicGame.java:763)
    at magic.model.action.ExecuteFirstEventAction.doAction(ExecuteFirstEventAction.java:18)
    at magic.model.MagicGame.doAction(MagicGame.java:552)
    ... 7 more
```
```
Exception from controller.runGame: java.lang.ClassCastException: magic.model.choice.MagicPlayChoiceResult cannot be cast to magic.model.choice.MagicDeclareAttackersResult
magic.exception.GameException: java.lang.ClassCastException: magic.model.choice.MagicPlayChoiceResult cannot be cast to magic.model.choice.MagicDeclareAttackersResult
    at magic.model.MagicGame.doAction(MagicGame.java:554)
    at magic.model.MagicGame.executeNextEvent(MagicGame.java:820)
    at magic.ai.MCTSAI.growTree(MCTSAI.java:376)
    at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:239)
    at magic.ai.MCTSAI$1.run(MCTSAI.java:148)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: magic.model.choice.MagicPlayChoiceResult cannot be cast to magic.model.choice.MagicDeclareAttackersResult
    at magic.model.event.MagicEvent.getAttackers(MagicEvent.java:490)
    at magic.model.event.MagicDeclareAttackersEvent$1.executeEvent(MagicDeclareAttackersEvent.java:26)
    at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:659)
    at magic.model.MagicGame.executeEvent(MagicGame.java:763)
    at magic.model.action.ExecuteFirstEventAction.doAction(ExecuteFirstEventAction.java:18)
    at magic.model.MagicGame.doAction(MagicGame.java:552)
    ... 7 more
```
```
Exception from controller.runGame: java.lang.ClassCastException: magic.model.choice.MagicPlayChoiceResult cannot be cast to magic.model.choice.MagicDeclareAttackersResult
magic.exception.GameException: java.lang.ClassCastException: magic.model.choice.MagicPlayChoiceResult cannot be cast to magic.model.choice.MagicDeclareAttackersResult
    at magic.model.MagicGame.doAction(MagicGame.java:554)
    at magic.model.MagicGame.executeNextEvent(MagicGame.java:820)
    at magic.ai.MCTSAI.getNextChoices(MCTSAI.java:520)
    at magic.ai.MCTSAI.growTree(MCTSAI.java:353)
    at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:241)
    at magic.ai.MCTSAI$1.run(MCTSAI.java:149)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: magic.model.choice.MagicPlayChoiceResult cannot be cast to magic.model.choice.MagicDeclareAttackersResult
    at magic.model.event.MagicEvent.getAttackers(MagicEvent.java:490)
    at magic.model.event.MagicDeclareAttackersEvent$1.executeEvent(MagicDeclareAttackersEvent.java:26)
    at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:659)
    at magic.model.MagicGame.executeEvent(MagicGame.java:763)
    at magic.model.action.ExecuteFirstEventAction.doAction(ExecuteFirstEventAction.java:18)
    at magic.model.MagicGame.doAction(MagicGame.java:552)
    ... 8 more
```

**Comment by melvinzhang** [comment]
looks like it is solved by https://github.com/magarena/magarena/commit/14dcb5ac957055e4e07c9abaa226efaf20753d17

The underlying problem was a global value RCHOICES that is shared between different calls to the AI. The commit makes it a local variable so that it is no longer shared between calls to the AI.
