### ISSUE TITLE
CI crash when copying spell with 'if' clause

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#519]
There are only two such spells: Edge of Autumn, and Gift of Estates.

```
1268. AddEventAction (EVENT: Edge of Autumn Pay {1}{G}$. Choose how to pay the mana cost.) = 0
1269. AddEventAction (EVENT: Edge of Autumn Play <Edge of Autumn~1000020>. ) = 0
1270. ExecuteFirstEventAction = 0
1271. PayDelayedCostAction = 0
1272. ExecuteFirstEventAction = 0
1273. RemoveCardAction (Edge of Autumn) = 297
1274. PutItemOnStackAction (MagicCardOnStack,Edge of Autumn) = 1
1275. AddEventAction (EVENT: Edge of Autumn  ) = 0
1276. ExecuteFirstEventAction = 0
1277. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1278. ExecuteFirstEventAction = 0
1279. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1280. ExecuteFirstEventAction = 0
1281. AddEventAction (EVENT: Reiterate Pay {1}{R}{R}$. Choose how to pay the mana cost.) = 0
1282. AddEventAction (EVENT: Reiterate MCTS may$ pay the buyback cost. Pay the buyback cost?) = 0
1283. AddEventAction (EVENT: Reiterate Play <Reiterate~1000042>. ) = 0
1284. ExecuteFirstEventAction = 0
1285. PayDelayedCostAction = 0
1286. ExecuteFirstEventAction = 0
1287. ExecuteFirstEventAction = 0
1288. RemoveCardAction (Reiterate) = -436
1289. PutItemOnStackAction (MagicCardOnStack,Reiterate) = -1
1290. AddEventAction (EVENT: Reiterate  Choose target instant or sorcery spell.) = 0
1291. AddEventAction (EVENT: Reiterate  ) = 0
1292. ExecuteFirstEventAction = 0
1293. ExecuteFirstEventAction = 0
1294. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1295. ExecuteFirstEventAction = 0
1296. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1297. ExecuteFirstEventAction = 0
1298. StackResolveAction = 0
1299. CopyCardOnStackAction (Edge of Autumn) = 0
Score = 3866

Exception from controller.runGame: magic.exception.GameException: java.lang.RuntimeException: getTargetChoice called on MagicEvent.NONE
magic.exception.GameException: magic.exception.GameException: java.lang.RuntimeException: getTargetChoice called on MagicEvent.NONE
	at magic.model.MagicGame.doAction(MagicGame.java:554)
	at magic.model.phase.MagicPhase.executePhase(MagicPhase.java:43)
	at magic.model.MagicGame.executePhase(MagicGame.java:468)
	at magic.model.MagicGame.advanceToNextEventWithChoice(MagicGame.java:782)
	at magic.ai.MCTSAI.runSimulation(MCTSAI.java:466)
	at magic.ai.MCTSAI.randomPlay(MCTSAI.java:439)
	at magic.ai.MCTSAI.access$000(MCTSAI.java:64)
	at magic.ai.MCTSAI$2.run(MCTSAI.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: magic.exception.GameException: java.lang.RuntimeException: getTargetChoice called on MagicEvent.NONE
	at magic.model.MagicGame.doAction(MagicGame.java:554)
	at magic.model.event.MagicRuleEventAction$137$1.doAction(MagicRuleEventAction.java:2790)
	at magic.model.event.MagicEvent.processTargetCardOnStack(MagicEvent.java:593)
	at magic.model.event.MagicRuleEventAction$137.executeEvent(MagicRuleEventAction.java:2788)
	at magic.model.event.MagicSpellCardEvent$2.executeEvent(MagicSpellCardEvent.java:61)
	at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:659)
	at magic.model.MagicGame.executeEvent(MagicGame.java:763)
	at magic.model.stack.MagicItemOnStack.resolve(MagicItemOnStack.java:127)
	at magic.model.stack.MagicCardOnStack.resolve(MagicCardOnStack.java:112)
	at magic.model.action.StackResolveAction.doAction(StackResolveAction.java:13)
	at magic.model.MagicGame.doAction(MagicGame.java:552)
	... 10 more
Caused by: java.lang.RuntimeException: getTargetChoice called on MagicEvent.NONE
	at magic.model.event.MagicEvent$1.getTargetChoice(MagicEvent.java:80)
	at magic.model.action.CopyCardOnStackAction.doAction(CopyCardOnStackAction.java:22)
	at magic.model.MagicGame.doAction(MagicGame.java:552)
	... 20 more
```

**Comment by melvinzhang** [comment]
due to the MagicSourceEvent, generated by MagicRuleEventAction, returning MagicEvent.NONE when the if condition is not satisfied.

**Comment by melvinzhang** [comment]
```
1245. AddFirstEventAction (EVENT: Uyo, Silent Prophet Return a land you control$ to its owner's hand. Choose a land you control.) = 0
1246. ExecuteFirstEventAction = 0
1247. RemoveFromPlayAction (Island,0) = 675
1248. RemoveFromCombatAction (Island) = 0
1249. MoveCardAction (Island,Play,OwnersHand) = -375
1250. RemoveTriggersStaticsAction = 0
1251. ExecuteFirstEventAction = 0
1252. PutItemOnStackAction (MagicAbilityOnStack,Uyo, Silent Prophet) = 1
1253. AddEventAction (EVENT: Uyo, Silent Prophet  Choose target instant or sorcery spell.) = 0
1254. ExecuteFirstEventAction = 0
1255. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1256. ExecuteFirstEventAction = 0
1257. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1258. ExecuteFirstEventAction = 0
1259. TapAction (Fountain of Youth) = -5
1260. AddEventAction (EVENT: Fountain of Youth Pay {2}$. Choose how to pay the mana cost.) = 0
1261. AddEventAction (EVENT: Fountain of Youth Play activated ability of Fountain of Youth. ) = 0
1262. ExecuteFirstEventAction = 0
1263. PayDelayedCostAction = 0
1264. ExecuteFirstEventAction = 0
1265. PutItemOnStackAction (MagicAbilityOnStack,Fountain of Youth) = -1
1266. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1267. ExecuteFirstEventAction = 0
1268. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1269. ExecuteFirstEventAction = 0
1270. StackResolveAction = 0
1271. ChangeLifeAction (MCTS,1) = 500
1272. ChangePlayerStateAction = 0
1273. AddStaticAction (MagicPermanent.NONE,magic.model.action.ChangePlayerStateAction$3@258dc3fd) = 0
1274. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1275. ExecuteFirstEventAction = 0
1276. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1277. ExecuteFirstEventAction = 0
1278. StackResolveAction = 0
1279. CopyCardOnStackAction (Gift of Estates) = 0
Score = -3948

Exception from controller.runGame: magic.exception.GameException: java.lang.RuntimeException: getTargetChoice called on MagicEvent.NONE
magic.exception.GameException: magic.exception.GameException: java.lang.RuntimeException: getTargetChoice called on MagicEvent.NONE
	at magic.model.MagicGame.doAction(MagicGame.java:566)
	at magic.model.phase.MagicPhase.executePhase(MagicPhase.java:43)
	at magic.model.MagicGame.executePhase(MagicGame.java:480)
	at magic.model.MagicGame.advanceToNextEventWithChoice(MagicGame.java:794)
	at magic.ai.MCTSAI.runSimulation(MCTSAI.java:452)
	at magic.ai.MCTSAI.randomPlay(MCTSAI.java:428)
	at magic.ai.MCTSAI.access$000(MCTSAI.java:63)
	at magic.ai.MCTSAI$2.run(MCTSAI.java:189)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: magic.exception.GameException: java.lang.RuntimeException: getTargetChoice called on MagicEvent.NONE
	at magic.model.MagicGame.doAction(MagicGame.java:566)
	at magic.model.event.MagicRuleEventAction$137$1.doAction(MagicRuleEventAction.java:2799)
	at magic.model.event.MagicEvent.processTargetCardOnStack(MagicEvent.java:593)
	at magic.model.event.MagicRuleEventAction$137.executeEvent(MagicRuleEventAction.java:2797)
	at magic.model.event.MagicRuleEventAction$164$1.executeEvent(MagicRuleEventAction.java:3758)
	at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:659)
	at magic.model.MagicGame.executeEvent(MagicGame.java:775)
	at magic.model.stack.MagicItemOnStack.resolve(MagicItemOnStack.java:122)
	at magic.model.action.StackResolveAction.doAction(StackResolveAction.java:13)
	at magic.model.MagicGame.doAction(MagicGame.java:564)
	... 10 more
Caused by: java.lang.RuntimeException: getTargetChoice called on MagicEvent.NONE
	at magic.model.event.MagicEvent$1.getTargetChoice(MagicEvent.java:80)
	at magic.model.action.CopyCardOnStackAction.doAction(CopyCardOnStackAction.java:22)
	at magic.model.MagicGame.doAction(MagicGame.java:564)
	... 19 more
```
