### ISSUE TITLE
ArrayIndexOutOfBoundsException: CardsCanvas.highlightCardUnderMousePointer

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#540]
Raised in [forum](http://www.slightlymagic.net/forum/viewtopic.php?f=82&p=189551#p189550) (logs available).
```
Exception from controller.runGame: 6
java.lang.ArrayIndexOutOfBoundsException: 6
	at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:387)
	at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:396)
	at magic.ui.canvas.cards.CardsCanvas.highlightCardUnderMousePointer(CardsCanvas.java:279)
	at magic.ui.canvas.cards.CardsCanvas.drawCards(CardsCanvas.java:273)
	at magic.ui.canvas.cards.CardsCanvas.paintComponent(CardsCanvas.java:259)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by lodici** [comment]
This fix is easy, by including check on upper limit - on line #276...
```
if (currentCardIndex >= 0 && currentCardIndex < cards.size())
```
but would prefer to replicate if possible first.

**Comment by lodici** [comment]
Replicated on the Mulligan screen by either moving mouse around screen while deal animation is running or clicking on highlighted section at the same time.
