### ISSUE TITLE
[1.68] Unsupported minor.major version 52.0

### ISSUE THREAD

**Issue by monuszko** [magarena/magarena#549]
The game crashes when I try to run it.

./Magarena.sh 
Exception in thread "main" java.lang.UnsupportedClassVersionError: magic/MagicMain : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

My system is Debian GNU/Linux Jessie (8.0).

java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

dpkg -l | grep java
(...)
ii  java-common                           0.52                                 all          Base of all Java packages
ii  java-wrappers                         0.1.28                               all          wrappers for java executables

dpkg -l | grep jdk
ii  openjdk-6-jre:amd64                   6b31-1.13.3-1                        amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-6-jre-headless:amd64          6b31-1.13.3-1                        amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
ii  openjdk-6-jre-lib                     6b31-1.13.3-1                        all          OpenJDK Java runtime (architecture independent libraries)
ii  openjdk-7-jre:amd64                   7u79-2.5.6-1~deb8u1                  amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-7-jre-headless:amd64          7u79-2.5.6-1~deb8u1                  amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
ii  openjdk-7-jre-lib                     7u91-2.6.3-1~deb8u1                  all          OpenJDK Java runtime (architecture independent libraries)

**Comment by lodici** [comment]
Please update java to version 8 (see also [getting started](https://github.com/magarena/magarena/wiki/Getting-Started) in wiki).

**Comment by dar72** [comment]
I had the same issue with 1.70 on Arch Linux, I do have Java version 8 installed, but I also have version 7 installed, turns out that version 7 is my default.

To get around this I modified the Magarena.sh file:
`#!/bin/sh
self=`readlink -en "$0"`
base=`dirname "$self"`
cd "$base"
export PATH=/usr/lib/jvm/java-8-openjdk/jre/bin/:$PATH
exec java -Xms256M -Xmx512M -noverify -jar Magarena.jar`

Based on this:
https://wiki.archlinux.org/index.php/Java#Launching_an_application_with_the_non-default_java_version

Might be useful to do something like that in the released version?

**Comment by melvinzhang** [comment]
@dar72 why not change the default to 8 system wide as shown on the archlinux wiki? 

The path '/usr/lib/jvm/java-8-openjdk/' may not be the same standard across various Linux distros, and the launcher should respect the user's default java install, eg say if Java 9 is the default it should be used instead of Java 8.
