### ISSUE TITLE
Latest Firemind json feed causes exception.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#563]
```
Exception from controller.runGame: JSONObject["description"] not a string.
org.json.JSONException: JSONObject["description"] not a string.
	at org.json.JSONObject.getString(JSONObject.java:658)
	at magic.firemind.JsonOrgParser.getDeckDescription(JsonOrgParser.java:62)
	at magic.firemind.JsonOrgParser.parse(JsonOrgParser.java:37)
	at magic.firemind.FiremindJsonReader.refreshTopDecks(FiremindJsonReader.java:80)
	at magic.ui.widget.deck.DeckPicker.getDecksListData(DeckPicker.java:175)
	at magic.ui.widget.deck.DeckPicker.refreshDecksList(DeckPicker.java:155)
	at magic.ui.widget.deck.DeckPicker.access$100(DeckPicker.java:45)
	at magic.ui.widget.deck.DeckPicker$1$1.run(DeckPicker.java:131)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by lodici** [comment]
caused by a null description -
```
...
},
"Grixis Twin": 
{
    "description": null,
    "author": "Michael",
    "link": "http://www.firemind.ch/decks/158138",
    "rating": "213",
    "releaseDate": "20151022",
    "cards": 
[
{
    "name": "Goblin Chieftain",
    "quantity": ​4
},
...
```
