### ISSUE TITLE
Rapid clicking of Generate decks causing exception.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#568]
This is related to updates associated with #566.

If you rapidly click the Generate decks button you should eventually get the following exception.
```
Exception from controller.runGame: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
	at magic.ui.screen.DuelDecksScreen$StartupWorker.getNextGame(DuelDecksScreen.java:329)
	at magic.ui.screen.DuelDecksScreen$StartupWorker.done(DuelDecksScreen.java:321)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at javax.swing.SwingWorker.get(SwingWorker.java:602)
	at magic.ui.screen.DuelDecksScreen$StartupWorker.getNextGame(DuelDecksScreen.java:327)
	... 21 more
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at magic.model.MagicPlayer.createHandAndLibrary(MagicPlayer.java:417)
	at magic.model.MagicDuel.nextGame(MagicDuel.java:131)
	at magic.ui.screen.DuelDecksScreen$StartupWorker.doInBackground(DuelDecksScreen.java:316)
	at magic.ui.screen.DuelDecksScreen$StartupWorker.doInBackground(DuelDecksScreen.java:306)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lodici** [comment]
Not sure why but replacing the For..each with a loop (see above commit) generates a more helpful exception...
```
Exception from controller.runGame: java.util.concurrent.ExecutionException: java.lang.AssertionError: Attempting to set two MagicCardEvents for Predator's Rapport
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.AssertionError: Attempting to set two MagicCardEvents for Predator's Rapport
	at magic.ui.screen.DuelDecksScreen$StartupWorker.getNextGame(DuelDecksScreen.java:329)
	at magic.ui.screen.DuelDecksScreen$StartupWorker.done(DuelDecksScreen.java:321)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.util.concurrent.ExecutionException: java.lang.AssertionError: Attempting to set two MagicCardEvents for Predator's Rapport
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at javax.swing.SwingWorker.get(SwingWorker.java:602)
	at magic.ui.screen.DuelDecksScreen$StartupWorker.getNextGame(DuelDecksScreen.java:327)
	... 21 more
Caused by: java.lang.AssertionError: Attempting to set two MagicCardEvents for Predator's Rapport
	at magic.model.MagicCardDefinition.setEvent(MagicCardDefinition.java:786)
	at magic.model.event.MagicSpellCardEvent.change(MagicSpellCardEvent.java:22)
	at magic.data.CardDefinitions.addCardSpecificGroovyCode(CardDefinitions.java:152)
	at magic.data.CardProperty$31.setProperty(CardProperty.java:207)
	at magic.model.MagicCardDefinition.loadAbilities(MagicCardDefinition.java:181)
	at magic.model.MagicCard.<init>(MagicCard.java:99)
	at magic.model.MagicCard.<init>(MagicCard.java:87)
	at magic.model.MagicPlayer.createHandAndLibrary(MagicPlayer.java:421)
	at magic.model.MagicDuel.nextGame(MagicDuel.java:131)
	at magic.ui.screen.DuelDecksScreen$StartupWorker.doInBackground(DuelDecksScreen.java:316)
	at magic.ui.screen.DuelDecksScreen$StartupWorker.doInBackground(DuelDecksScreen.java:306)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lodici** [comment]
I took an educated guess to synchonize loadAbilities() based on the above exception. I have been quite unrealistically clicking Generate decks as fast as I can and the exception is not generated so at the very least it is a convenient sticking plaster. Not sure though whether there might be side-effects?

I believe the fundamental issue to be caused by the call to [``duel.buildDeck(player)``](https://github.com/magarena/magarena/blob/master/src/magic/ui/DuelDecksPanel.java#L129) on clicking Generate clashing with the background process running [``duel.nextGame();``](https://github.com/magarena/magarena/blob/master/src/magic/ui/screen/DuelDecksScreen.java#L316) as they are both working on the same data - decks, players, etc.

**Comment by melvinzhang** [comment]
It is more likely that different copies of nextGame is running at the same time and interfering with itself. nextGame calls loadAbilities, and loadAbilities was not designed to be thread safe.

**Comment by melvinzhang** [comment]
There are two separate crashes here:

1. The concurrent modification problem is due to the buildDeck modifying the deck while createHandAndLibrary is traversing the deck. This is fixed by using the for loop, since for loop does not perform the concurrent modification check unlike using an iterator.

2. The "Attempting to set two MagicCardEvents" assertion error is loadAbilities running for the same MagicCardDefinition at the same time in two separate worker threads. This is fixed by making loadAbilities thread safe with the synchronize keyword.

**Comment by melvinzhang** [comment]
Btw the call to worker.cancel doesn't actually cancel the task because the nextGame method doesn't invoke any methods that throw an InterruptException and it doesn't check SwingWorker.isCancelled. This means each call to nextGame will always run to completion.

**Comment by melvinzhang** [comment]
There is a small chance that the for loop iteration can still crash, that is when the deck is smaller than it was previously, this doesn't occur with the deck generator which always generate 40 card decks. Since the nextGame runs fairly fast, it should be rather difficult to modify the deck to make it smaller before it runs to completion so I think we can ignore this.

**Comment by lodici** [comment]
> There are two separate crashes here:

Thanks for the explanation - it was doing my head in.

> Btw the call to worker.cancel doesn't actually cancel the task because the nextGame method doesn't invoke any methods that throw an InterruptException and it doesn't check SwingWorker.isCancelled. This means each call to nextGame will always run to completion.

The problem with SwingWorker.isCancelled() is that the code needs to be aware of the SwingWorker which would mean passing a reference to it to duel.nextGame(). Yuk! Alternatively, you can also use the SwingWorker agnostic ``Thread.isInterrupted()``. [Another option](https://blogs.oracle.com/swinger/entry/swingworker_stop_that_train) is to invoke ``Thread.sleep(1)`` for some time in your loop. By doing so you allow "SwingWorker.cancel()" to really cancel whatever you're doing.

**Comment by melvinzhang** [comment]
Good point about using Thread.isInterrupted(), I've added it to the main loop in createHandAndLibrary so that creation of MagicCard (which calls loadAbilities) is stopped when the thread is interrupted. See 6f2d24d6c4526
