### ISSUE TITLE
merge cardbuilder back into main repo

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#574]
@ShawnieBoy I'm creating a separate issue for this. Can you outline the rough plan of the merge? By merge, you mean adding the cardbuilder changes and files manually or do you literally mean a merge via git?

**Comment by melvinzhang** [comment]
Small safe changes like 8ac0887fbd3e1b1d are great, if the "merge" can be done as a series of new commits like 8ac0887fbd3e1b1d would be ideal.

**Comment by lodici** [comment]
Totally agree about not doing a single merge. @ShawnieBoy, consider starting with the CardProxyImageBuilder and gradually updating that step by step. That is was the proxy image is after all - CardBuilder lite.

**Comment by ShawnieBoy** [comment]
Well, thankfully I'm off for a week so have plenty of time to work through all this, lol.

Just trying to get cardbuilder up to recent releases will be a job on it's own - Cardbuilder itself doesn't technically really change much - it's just that image use has changed a lot with ui updates, animation etc.

I'll be more likely to go the commit route - I know what things need to be added to current CardDefinition for example to get the info cardbuilder needs.

**Comment by ShawnieBoy** [comment]
Still work to be done tidying up - a cheap redirect to Cardbuilder to show some results. But at least it's all there.

Would want to remove the ResourceManager accessing the jar as a resource and other bits and bobs.

**Comment by ShawnieBoy** [comment]
Ok, I must have broke something along the way:

```
Exception from controller.runGame: null
java.lang.NullPointerException
	at magic.ui.utility.ImageDrawingUtils.drawAbilityInfo(ImageDrawingUtils.java:94)
	at magic.ui.duel.viewer.ImagePermanentViewer.paintComponent(ImagePermanentViewer.java:299)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1300(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by melvinzhang** [comment]
Probably due to my change, I modified drawAbilityInfo to use AbilityIcon. @ShawnieBoy Please create a separate issue for this with steps to replicate, thanks!

**Comment by ShawnieBoy** [comment]
Phew - sure thing

**Comment by lodici** [comment]
Looks really good with no obvious lag. The only thing that needs looking at is transparency issues with the rounded frame corners. Like the card images proper, you might want to consider using square border frames instead which means you could also use much smaller JPGs for the frames.

**Comment by ShawnieBoy** [comment]
The transparency has had me scratching my head, I think it's actually due to image compression changing the encoding somehow.
Although I just had a brainwave - draw with rounded corners.

**Comment by ShawnieBoy** [comment]
There's something else going on with the transparency - it's not the files, but can't work out why it's only Blue, Red, Multi and Green frames - not Black, White, Artifact or Land

**Comment by lodici** [comment]
There are so many frame images! Not all are transparent - for example \double-faced\gcard2.jpg. JPG cannot be transparent hence my comment above using straight corners. I load an image into Paint.Net to tell if it an image's background is transparent or not - there might be an automated tool out there somewhere.

**Comment by ShawnieBoy** [comment]
Just did some experimenting - it is the files themselves. Just rebuilt a few - looks like compression is probably the culprit. Some components require transparency, but the base frames really don't.

**Comment by ShawnieBoy** [comment]
The double-faced cards aren't implemented yet - they're just there for future work.

And yes, lots of images :frowning:

**Comment by lodici** [comment]
> Some components require transparency, but the base frames really don't.

Yes they do if using rounded corners.

**Comment by ShawnieBoy** [comment]
They won't be there forever - just want to make sure the transparency issue gets sorted - it's effecting Loyalty overlay and the some of the blend functions.

**Comment by lodici** [comment]
> They won't be there forever

??? Not sure we are talking about the same thing - the card image background color (the bit in each corner outside the rounded corner of the card frame) needs to be transparent.

**Comment by ShawnieBoy** [comment]
Hehe, you were saying about using square corners on the images - I'm agreeing with you, so that then the base frames won't need to be transparent.

**Comment by ShawnieBoy** [comment]
Will mean doing some batch recoloring as the corners are natively white.

**Comment by ShawnieBoy** [comment]
Hmm, looks like some transparency encoding is removed by PNGGauntlet. Why this only occurs with some files is a bit of a mystery to me - Got the same results with edited images from Paint.NET and Photoshop.

Looks like the loyalty panel colouring is a separate issue. Possibly grayscale involvement.

**Comment by ShawnieBoy** [comment]
The main merge is complete so this can be closed - will open related issues
