### ISSUE TITLE
crash when showing missing image in explorer when "show missing card data" is off

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#590]
To replicate:
1. Open options, set "show missing data" to off. Only card names are loaded for missing cards
2. Open explorer, mouse over a missing card, eg the first card, "Abandon Hope"
3. Null pointer exception.

@ShawnieBoy do take a look at this when you have some time.

Detailed crash log:
```
-Xms256M
-Xmx512M
-Xverify:none
-ea
-DrndSeed=100
-DselfMode=false
-Ddebug=false
-DdevMode=false
-Dmagarena.dir=/home/melvin/Modules/magarena/release

Data folder : /home/melvin/Modules/magarena/release/Magarena
Using random seed 100
ERROR! Unable to read from /home/melvin/Modules/magarena/release/Magarena/images/cards/Abandon Hope.jpg
CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
CREATED ON 2015/12/24 16:18:20
MAGARENA VERSION 1.69, JRE 1.8.0_66-internal, OS Linux_4.0.0-2-amd64 amd64
================================
Used Memory: 198M
Free Memory: 215M
Total Memory: 414M
Max Memory: 455M
================================
-Xms256M
-Xmx512M
-Xverify:none
-ea
-DrndSeed=100
-DselfMode=false
-Ddebug=false
-DdevMode=false
-Dmagarena.dir=/home/melvin/Modules/magarena/release


Exception from controller.runGame: null
java.lang.NullPointerException
	at magic.ui.cardBuilder.renderers.ImageFrame.getCompositeImage(ImageFrame.java:150)
	at magic.ui.cardBuilder.renderers.ImageFrame.buildDefaultImage(ImageFrame.java:137)
	at magic.ui.cardBuilder.renderers.ImageFrame.getCardImage(ImageFrame.java:132)
	at magic.ui.cardBuilder.renderers.ImageFrame.drawImage(ImageFrame.java:63)
	at magic.ui.cardBuilder.renderers.CardBuilder.makeBasicCard(CardBuilder.java:90)
	at magic.ui.cardBuilder.renderers.CardBuilder.getCardBuilderImage(CardBuilder.java:32)
	at magic.ui.MagicImages.getMissingCardImage(MagicImages.java:251)
	at magic.ui.CachedImagesProvider.lambda$getOriginalImage$10(CachedImagesProvider.java:39)
	at magic.ui.ImageFileIO.toImg(ImageFileIO.java:36)
	at magic.ui.CachedImagesProvider.getOriginalImage(CachedImagesProvider.java:39)
	at magic.ui.CachedImagesProvider.getScaledImage(CachedImagesProvider.java:59)
	at magic.ui.CachedImagesProvider.getImage(CachedImagesProvider.java:27)
	at magic.ui.duel.viewer.CardViewer.setCard(CardViewer.java:141)
	at magic.ui.duel.viewer.CardViewer.setCard(CardViewer.java:157)
	at magic.ui.explorer.CardPanel.setCard(CardPanel.java:107)
	at magic.ui.explorer.ExplorerSidebarPanel.setCard(ExplorerSidebarPanel.java:42)
	at magic.ui.explorer.ExplorerPanel$1.run(ExplorerPanel.java:140)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ShawnieBoy** [comment]
I think that would be due to none of the scripts in the missing folder being read - so no cardDefinitions to read from. Will have a look.

**Comment by lodici** [comment]
The previous proxy just displayed the card name (and zero) -
![screenshot00424](https://cloud.githubusercontent.com/assets/2443519/11995265/a08b122c-aa45-11e5-84c4-a77738b930de.jpg)

**Comment by ShawnieBoy** [comment]
I'll have a more in-depth look when I get back home. 
The {0} Is due to it having no card types, the check was for non-lands. 

Cardbuilder will need to know if the show disabled is on or not and show a separate image instead. Maybe card-back

**Comment by lodici** [comment]
Or you could just draw a black border with white background, add the card name and perhaps add something along the lines of "The 'Show missing card data' setting is switched off."

**Comment by lodici** [comment]
> Cardbuilder will need to know if the show disabled is on or not

``GeneralConfig.showMissingCardData()``

**Comment by ShawnieBoy** [comment]
Excellent - Thanks. Did have a quick try this morning but missed out the getInstance() Can make a colorless empty card with card name when it's off.

Well will do in about 5hrs - grr work

**Comment by ShawnieBoy** [comment]
Found an easier solution - just show a default image if the card has no type when there are no crops or card type.

I went for the MagarenaLogo.
