### ISSUE TITLE
Knight of the Mists crash if you respond to its trigger with "no"

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#610]
1. Cast "Knight of the Mists"
2. Select "No" for its trigger
3. Crash
```
Exception from controller.runGame: java.lang.NullPointerException
magic.exception.GameException: java.lang.NullPointerException
	at magic.model.MagicGame.doAction(MagicGame.java:560)
	at magic.model.phase.MagicPhase.executePhase(MagicPhase.java:43)
	at magic.model.MagicGame.executePhase(MagicGame.java:468)
	at magic.model.MagicGame.advanceToNextEventWithChoice(MagicGame.java:788)
	at magic.ai.MCTSAI.runSimulation(MCTSAI.java:466)
	at magic.ai.MCTSAI.randomPlay(MCTSAI.java:439)
	at magic.ai.MCTSAI.access$000(MCTSAI.java:64)
	at magic.ai.MCTSAI$2.run(MCTSAI.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at magic.model.event.MagicEvent.listTargetPermanent(MagicEvent.java:633)
	at magic.model.ARG.permanents(ARG.java:181)
	at magic.model.event.MagicRuleEventAction$5$1.executeEvent(MagicRuleEventAction.java:140)
	at magic.model.event.MagicRuleEventAction$116.executeEvent(MagicRuleEventAction.java:3057)
	at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:726)
	at magic.model.MagicGame.executeEvent(MagicGame.java:769)
	at magic.model.stack.MagicItemOnStack.resolve(MagicItemOnStack.java:127)
	at magic.model.action.StackResolveAction.doAction(StackResolveAction.java:13)
	at magic.model.MagicGame.doAction(MagicGame.java:558)
	... 10 more
```

**Comment by melvinzhang** [comment]
"Don't" action should not have target as MagicMayChoice only prompts for target in "Yes" case
