### ISSUE TITLE
MagicPayManaCostChoice.getSimulationChoiceResult causes IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#649]
```
383. UntapAction (Drekavac) = -10
384. UntapAction (Swamp) = -5
385. DrawAction = -375
386. AddEventAction (EVENT: NONE  ...) = 0
387. ExecuteFirstEventAction = 0
388. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
389. ExecuteFirstEventAction = 0
390. AddEventAction (EVENT: Swamp Play <Swamp~1000070>. ) = 0
391. ExecuteFirstEventAction = 0
392. RemoveCardAction (Swamp) = 375
393. PlayCardAction = 0
394. AddEventAction (EVENT: Swamp Put <Swamp~1000070> onto the battlefield. ) = 0
395. ExecuteFirstEventAction = 0
396. PlayCardFromStackAction (Swamp) = -677
397. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
Score = -1872

Exception from controller.runGame: bound must be positive
java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Random.java:388)
    at magic.model.MagicRandom.nextRNGInt(MagicRandom.java:54)
    at magic.model.choice.MagicPayManaCostChoice.getSimulationChoiceResult(MagicPayManaCostChoice.java:88)
    at magic.model.event.MagicEvent.getSimulationChoiceResult(MagicEvent.java:437)
    at magic.ai.MCTSAI.runSimulation(MCTSAI.java:483)
    at magic.ai.MCTSAI.randomPlay(MCTSAI.java:446)
    at magic.ai.MCTSAI.access$000(MCTSAI.java:65)
    at magic.ai.MCTSAI$2.run(MCTSAI.java:188)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by melvinzhang** [comment]
```
764. ChangeStateAction = 0
765. ChangeStateAction = 0
766. UntapAction (Forest) = -5
767. UntapAction (Forest) = -5
768. UntapAction (Leaf Dancer) = -10
769. UntapAction (Rupture Spire) = -5
770. ChangeStateAction = 0
771. ChangeStateAction = 0
772. UntapAction (Thornwood Falls) = -5
773. EnqueueTriggerAction = 0
774. DrawAction = -247
775. AddEventAction (EVENT: NONE  ...) = 0
776. ExecuteFirstEventAction = 0
777. PutItemOnStackAction (MagicTriggerOnStack,Drifter il-Dal) = 1
778. AddEventAction (EVENT: Drifter il-Dal  Pay {U}? If you don't, sacrifice <Drifter il-Dal~1000060>.) = 0
779. DequeueTriggerAction = 0
780. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
781. ExecuteFirstEventAction = 0
782. ExecuteFirstEventAction = 0
783. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
784. ExecuteFirstEventAction = 0
785. StackResolveAction = 0
786. AddEventAction (EVENT: Drifter il-Dal Pay {U}$. Choose how to pay the mana cost.) = 0
Score = 1107

Exception from controller.runGame: bound must be positive
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at magic.model.MagicRandom.nextRNGInt(MagicRandom.java:54)
	at magic.model.choice.MagicPayManaCostChoice.getSimulationChoiceResult(MagicPayManaCostChoice.java:88)
	at magic.model.event.MagicEvent.getSimulationChoiceResult(MagicEvent.java:437)
	at magic.ai.MCTSAI.runSimulation(MCTSAI.java:483)
	at magic.ai.MCTSAI.randomPlay(MCTSAI.java:446)
	at magic.ai.MCTSAI.access$000(MCTSAI.java:65)
	at magic.ai.MCTSAI$2.run(MCTSAI.java:188)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by melvinzhang** [comment]
Have not occurred since.
