### ISSUE TITLE
Multiple Breathstealer Crypt crash

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#669]
Game crash due to attempting to discard the same card twice:

```
1554. EnqueueTriggerAction = 0
1555. EnqueueTriggerAction = 0
1556. DrawAction = -365
1557. AddEventAction (EVENT: Blood Artist ShawnieBoy may$ pay 3 life. If ShawnieBoy doesn't, discard this card. Pay 3 life? If not, discard Blood Artist) = 0
1558. AddEventAction (EVENT: Blood Artist ShawnieBoy may$ pay 3 life. If ShawnieBoy doesn't, discard this card. Pay 3 life? If not, discard Blood Artist) = 0
1559. ExecuteFirstEventAction = 0
1560. DiscardCardAction = 365
1561. MoveCardAction (Blood Artist,OwnersHand,Graveyard) = 0
1562. EnqueueTriggerAction = 0
1563. EnqueueTriggerAction = 0
1564. ExecuteFirstEventAction = 0
1565. DiscardCardAction = 0
Score = -6483

Exception from controller.runGame: magic.exception.GameException: java.lang.RuntimeException: Card Blood Artist not found.
magic.exception.GameException: magic.exception.GameException: java.lang.RuntimeException: Card Blood Artist not found.
        at magic.model.MagicGame.doAction(MagicGame.java:555)
        at magic.model.MagicGame.executeNextEvent(MagicGame.java:832)
        at magic.ai.MCTSAI.runSimulation(MCTSAI.java:485)
        at magic.ai.MCTSAI.randomPlay(MCTSAI.java:446)
        at magic.ai.MCTSAI.access$000(MCTSAI.java:65)
        at magic.ai.MCTSAI$2.run(MCTSAI.java:188)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: magic.exception.GameException: java.lang.RuntimeException: Card Blood Artist not found.
        at magic.model.MagicGame.doAction(MagicGame.java:555)
        at Breathstealer_s_Crypt$1.executeEvent(Breathstealer_s_Crypt.groovy:20)
        at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:738)
        at magic.model.MagicGame.executeEvent(MagicGame.java:775)
        at magic.model.action.ExecuteFirstEventAction.doAction(ExecuteFirstEventAction.java:18)
        at magic.model.MagicGame.doAction(MagicGame.java:553)
        ... 8 more
Caused by: java.lang.RuntimeException: Card Blood Artist not found.
        at magic.model.MagicCardList.removeCard(MagicCardList.java:105)
        at magic.model.MagicPlayer.removeCardFromHand(MagicPlayer.java:381)
        at magic.model.action.DiscardCardAction.doAction(DiscardCardAction.java:28)
        at magic.model.MagicGame.doAction(MagicGame.java:553)
        ... 13 more
```

**Comment by ShawnieBoy** [comment]
From AI simulations, not actual gameplay
