### ISSUE TITLE
class cast exception when highlighting card 

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#760]
Reported by jerichopumpkin @ http://www.slightlymagic.net/forum/viewtopic.php?t=18552&p=196579#p196579
```
CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
CREATED ON 2016/05/03 20:32:01
MAGARENA VERSION 1.72, JRE 1.8.0_91, OS Windows 10_10.0 x86
================================
Used Memory: 131M
Free Memory: 115M
Total Memory: 247M
Max Memory: 494M
================================
-Xms256m
-Xmx512m
-Xverify:none


Turn : 5  Phase : FirstMain  Step : ActivePlayer  Player : Torre  AI : minimax  Score : -952
0] Player : Torre  Life : 19  Delayed : Total=0
   - Hand : Lim-D�l's Paladin
   - Hand : Skeleton Key
   - Hand : Lim-D�l's Paladin
   - Hand : Tormenting Voice
   - Graveyard : Bloodstained Mire
   - Library : Tormenting Voice
   - Library : Zombie Infestation
   - Library : Dragonskull Summit
   - Library : Badlands
   - Library : Reckless Wurm
   - Library : Dragonskull Summit
   - Library : Alms of the Vein
   - Permanent : Blood Crypt  Tapped
   - Permanent : Scrubland  Tapped
   - Permanent : Zombie Infestation
1] Player : Mini Max  Life : 20  Delayed : Total=0
   - Hand : Plains
   - Hand : Plains
   - Hand : Benalish Knight
   - Hand : Serra's Embrace
   - Hand : Skyhunter Patrol
   - Hand : Condemn
   - Library : Plains
   - Library : Skyhunter Patrol
   - Library : Plains
   - Library : Wild Griffin
   - Library : Plains
   - Library : Loxodon Mystic
   - Library : Plains
   - Permanent : Ghost Warden  Power : 1  Toughness : 1  Damage : 0  Summoned
   - Permanent : Plains  Tapped
   - Permanent : Plains  Tapped  Summoned
Stack : 3
   - Name : Fiery Temper  Player : Torre
   - Name : Alms of the Vein  Player : Torre
   - Name : Zombie Infestation  Player : Torre

Exception from controller.runGame: magic.model.stack.MagicTriggerOnStack cannot be cast to magic.model.stack.MagicCardOnStack
java.lang.ClassCastException: magic.model.stack.MagicTriggerOnStack cannot be cast to magic.model.stack.MagicCardOnStack
	at magic.ui.duel.viewer.info.GameViewerInfo.searchForCardOnStack(GameViewerInfo.java:160)
	at magic.ui.duel.viewer.info.GameViewerInfo.getCardViewerInfo(GameViewerInfo.java:121)
	at magic.ui.duel.SwingGameController.highlightCard(SwingGameController.java:1064)
	at magic.ui.message.TextLabel.doMouseMoveAction(TextLabel.java:163)
	at magic.ui.message.TextLabel.access$300(TextLabel.java:28)
	at magic.ui.message.TextLabel$2.mouseMoved(TextLabel.java:116)
	at java.awt.Component.processMouseMotionEvent(Unknown Source)
	at javax.swing.JComponent.processMouseMotionEvent(Unknown Source)
        ...
```

**Comment by melvinzhang** [comment]
Madness creates a MagicTriggerOnStack not a MagicCardOnStack

**Comment by melvinzhang** [comment]
To replicate:
1. discard Fiery Temper (or any other madness card) to trigger madness
2. mouse over the word "Fiery Temper" on the stack
3. crash
