### ISSUE TITLE
OOM during javax.swing.JComponent.paint

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#761]
Reported by hong yie @ http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=18552&p=196579&sid=382caf8819ce1f2ba6aa9ba69404d4b2#p196441
```
CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
CREATED ON 2016/04/30 13:57:35
MAGARENA VERSION 1.72, JRE 1.8.0_65, OS Windows 7_6.1 amd64
================================
Used Memory: 202M
Free Memory: 287M
Total Memory: 490M
Max Memory: 490M
================================
-Xms256m
-Xmx512m
-Xverify:none


Turn : 5  Phase : FirstMain  Step : ActivePlayer  Player : Monty Carlo  AI : monte carlo tree search  Score : 1879
0] Player : user  Life : 20  Delayed : Total=0
   - Hand : Elvish Visionary
   - Hand : Rootbound Crag
   - Hand : Treefolk Harbinger
   - Hand : Wooded Foothills
   - Hand : Wall of Blossoms
   - Library : Birds of Paradise
   - Library : Winter's Grasp
   - Library : Mountain
   - Library : Mountain
   - Library : Pillage
   - Library : Abundant Growth
   - Library : Dragonmaster Outcast
   - Permanent : Abundant Growth  Summoned
   - Permanent : Birds of Paradise  Power : 0  Toughness : 1  Damage : 0  Summoned
   - Permanent : Dragonmaster Outcast  Power : 1  Toughness : 1  Damage : 0  Tapped
   - Permanent : Mountain  Tapped
   - Permanent : Rootbound Crag  Tapped  Summoned
1] Player : Monty Carlo  Life : 19  Delayed : Total=0
   - Hand : Island
   - Hand : Enclave Cryptologist
   - Hand : Enclave Cryptologist
   - Hand : Exhume
   - Hand : Reya Dawnbringer
   - Library : Polluted Delta
   - Library : Zombify
   - Library : Drowned Catacomb
   - Library : Drowned Catacomb
   - Library : Swamp
   - Library : Liliana Vess
   - Library : Island
   - Permanent : Island  Tapped  Summoned
   - Permanent : Swamp  Tapped
   - Permanent : Swamp  Tapped
Stack : 1
   - Name : Grim Haruspex  Player : Monty Carlo
1. AddEventAction (EVENT: NONE user may$ take a mulligan. ) = 0
2. AddEventAction (EVENT: NONE Monty Carlo may$ take a mulligan. ) = 0
3. ExecuteFirstEventAction = 0
4. ExecuteFirstEventAction = 0
5. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
6. ExecuteFirstEventAction = 0
7. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
8. ExecuteFirstEventAction = 0
9. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
10. ExecuteFirstEventAction = 0
11. AddEventAction (EVENT: Swamp Play <Swamp~1000114>. ) = 0
12. ExecuteFirstEventAction = 0
13. RemoveCardAction (Swamp) = 375
14. PlayCardAction = 0
15. AddEventAction (EVENT: Swamp Put <Swamp~1000114> onto the battlefield. ) = 0
16. ExecuteFirstEventAction = 0
17. PlayCardFromStackAction (Swamp) = -680
18. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
19. ExecuteFirstEventAction = 0
20. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
21. ExecuteFirstEventAction = 0
22. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
23. ExecuteFirstEventAction = 0
24. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
25. ExecuteFirstEventAction = 0
26. AddEventAction (EVENT: NONE  Declare attackers.) = 0
27. ExecuteFirstEventAction = 0
28. DeclareAttackersAction = 0
29. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
30. ExecuteFirstEventAction = 0
31. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
32. ExecuteFirstEventAction = 0
33. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
34. ExecuteFirstEventAction = 0
35. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
36. ExecuteFirstEventAction = 0
37. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
38. ExecuteFirstEventAction = 0
39. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
40. ExecuteFirstEventAction = 0
41. ReturnExiledAction = 0
42. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
43. ExecuteFirstEventAction = 0
44. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
45. ExecuteFirstEventAction = 0
46. CleanupTurnTriggersAction = 0
47. CleanupPlayerAction = 0
48. CleanupPlayerAction = 0
49. CleanupPermanentAction = 0
50. CleanupTurnStaticsAction = 0
51. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
52. ExecuteFirstEventAction = 0
53. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
54. ExecuteFirstEventAction = 0
55. DrawAction = 375
56. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
57. ExecuteFirstEventAction = 0
58. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
59. ExecuteFirstEventAction = 0
60. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
61. MarkerAction = 0
62. LogMarkerAction = 0
63. ExecuteFirstEventAction = 0
64. AddEventAction (EVENT: Mountain Play <Mountain~1000052>. ) = 0
65. ExecuteFirstEventAction = 0
66. RemoveCardAction (Mountain) = -375
67. PlayCardAction = 0
68. AddEventAction (EVENT: Mountain Put <Mountain~1000052> onto the battlefield. ) = 0
69. ExecuteFirstEventAction = 0
70. PlayCardFromStackAction (Mountain) = 679
71. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
72. MarkerAction = 0
73. LogMarkerAction = 0
74. ExecuteFirstEventAction = 0
75. AddEventAction (EVENT: Dragonmaster Outcast Pay {R}$. Choose how to pay the mana cost.) = 0
76. AddEventAction (EVENT: Dragonmaster Outcast Play <Dragonmaster Outcast~1000007>. ) = 0
77. TapAction (Mountain) = -5
78. ExecuteFirstEventAction = 0
79. ExecuteFirstEventAction = 0
80. RemoveCardAction (Dragonmaster Outcast) = -432
81. PutItemOnStackAction (MagicCardOnStack,Dragonmaster Outcast) = -1
82. AddEventAction (EVENT: Dragonmaster Outcast  ) = 0
83. ExecuteFirstEventAction = 0
84. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
85. ExecuteFirstEventAction = 0
86. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
87. ExecuteFirstEventAction = 0
88. StackResolveAction = 0
89. PlayCardFromStackAction (Dragonmaster Outcast) = 936
90. ChangeStateAction = 0
91. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
92. ExecuteFirstEventAction = 0
93. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
94. ExecuteFirstEventAction = 0
95. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
96. ExecuteFirstEventAction = 0
97. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
98. ExecuteFirstEventAction = 0
99. AddEventAction (EVENT: NONE  Declare attackers.) = 0
100. ExecuteFirstEventAction = 0
101. DeclareAttackersAction = 0
102. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
103. ExecuteFirstEventAction = 0
104. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
105. ExecuteFirstEventAction = 0
106. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
107. ExecuteFirstEventAction = 0
108. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
109. ExecuteFirstEventAction = 0
110. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
111. ExecuteFirstEventAction = 0
112. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
113. ExecuteFirstEventAction = 0
114. ReturnExiledAction = 0
115. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
116. ExecuteFirstEventAction = 0
117. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
118. ExecuteFirstEventAction = 0
119. CleanupTurnTriggersAction = 0
120. CleanupPlayerAction = 0
121. CleanupPermanentAction = 0
122. CleanupPermanentAction = 0
123. CleanupPlayerAction = 0
124. CleanupPermanentAction = 0
125. CleanupTurnStaticsAction = 0
126. ChangeStateAction = 0
127. ChangeStateAction = 0
128. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
129. ExecuteFirstEventAction = 0
130. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
131. ExecuteFirstEventAction = 0
132. DrawAction = -375
133. AddEventAction (EVENT: NONE  ...) = 0
134. ExecuteFirstEventAction = 0
135. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
136. ExecuteFirstEventAction = 0
137. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
138. ExecuteFirstEventAction = 0
139. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
140. ExecuteFirstEventAction = 0
141. AddEventAction (EVENT: Swamp Play <Swamp~1000113>. ) = 0
142. ExecuteFirstEventAction = 0
143. RemoveCardAction (Swamp) = 375
144. PlayCardAction = 0
145. AddEventAction (EVENT: Swamp Put <Swamp~1000113> onto the battlefield. ) = 0
146. ExecuteFirstEventAction = 0
147. PlayCardFromStackAction (Swamp) = -679
148. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
149. ExecuteFirstEventAction = 0
150. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
151. ExecuteFirstEventAction = 0
152. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
153. ExecuteFirstEventAction = 0
154. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
155. ExecuteFirstEventAction = 0
156. AddEventAction (EVENT: NONE  Declare attackers.) = 0
157. ExecuteFirstEventAction = 0
158. DeclareAttackersAction = 0
159. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
160. ExecuteFirstEventAction = 0
161. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
162. ExecuteFirstEventAction = 0
163. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
164. ExecuteFirstEventAction = 0
165. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
166. ExecuteFirstEventAction = 0
167. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
168. ExecuteFirstEventAction = 0
169. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
170. ExecuteFirstEventAction = 0
171. ReturnExiledAction = 0
172. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
173. ExecuteFirstEventAction = 0
174. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
175. ExecuteFirstEventAction = 0
176. CleanupTurnTriggersAction = 0
177. CleanupPlayerAction = 0
178. CleanupPermanentAction = 0
179. CleanupPermanentAction = 0
180. CleanupPlayerAction = 0
181. CleanupPermanentAction = 0
182. CleanupPermanentAction = 0
183. CleanupTurnStaticsAction = 0
184. ChangeStateAction = 0
185. ChangeStateAction = 0
186. ChangeStateAction = 0
187. ChangeStateAction = 0
188. UntapAction (Mountain) = 5
189. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
190. ExecuteFirstEventAction = 0
191. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
192. ExecuteFirstEventAction = 0
193. DrawAction = 389
194. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
195. ExecuteFirstEventAction = 0
196. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
197. ExecuteFirstEventAction = 0
198. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
199. MarkerAction = 0
200. LogMarkerAction = 0
201. ExecuteFirstEventAction = 0
202. AddEventAction (EVENT: Rootbound Crag Play <Rootbound Crag~1000058>. ) = 0
203. ExecuteFirstEventAction = 0
204. RemoveCardAction (Rootbound Crag) = -492
205. PlayCardAction = 0
206. AddEventAction (EVENT: Rootbound Crag Put <Rootbound Crag~1000058> onto the battlefield. ) = 0
207. ExecuteFirstEventAction = 0
208. PlayCardFromStackAction (Rootbound Crag) = 795
209. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
210. MarkerAction = 0
211. LogMarkerAction = 0
212. ExecuteFirstEventAction = 0
213. AddEventAction (EVENT: Abundant Growth Pay {G}$. Choose how to pay the mana cost.) = 0
214. AddEventAction (EVENT: Abundant Growth Play <Abundant Growth~1000021>. ) = 0
215. TapAction (Rootbound Crag) = -5
216. ExecuteFirstEventAction = 0
217. ExecuteFirstEventAction = 0
218. RemoveCardAction (Abundant Growth) = -389
219. PutItemOnStackAction (MagicCardOnStack,Abundant Growth) = -1
220. AddEventAction (EVENT: Abundant Growth  Choose target land.) = 0
221. AddEventAction (EVENT: Abundant Growth  ) = 0
222. ExecuteFirstEventAction = 0
223. ExecuteFirstEventAction = 0
224. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
225. ExecuteFirstEventAction = 0
226. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
227. ExecuteFirstEventAction = 0
228. StackResolveAction = 0
229. PlayCardFromStackAction (Abundant Growth,Mountain) = 692
230. ChangeStateAction = 0
231. EnqueueTriggerAction = 0
232. PutItemOnStackAction (MagicTriggerOnStack,Abundant Growth) = -1
233. DequeueTriggerAction = 0
234. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
235. ExecuteFirstEventAction = 0
236. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
237. ExecuteFirstEventAction = 0
238. StackResolveAction = 0
239. DrawAction = 429
240. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
241. MarkerAction = 0
242. LogMarkerAction = 0
243. ExecuteFirstEventAction = 0
244. AddEventAction (EVENT: Birds of Paradise Pay {G}$. Choose how to pay the mana cost.) = 0
245. AddEventAction (EVENT: Birds of Paradise Play <Birds of Paradise~1000002>. ) = 0
246. TapAction (Mountain) = -5
247. ExecuteFirstEventAction = 0
248. ExecuteFirstEventAction = 0
249. RemoveCardAction (Birds of Paradise) = -432
250. PutItemOnStackAction (MagicCardOnStack,Birds of Paradise) = -1
251. AddEventAction (EVENT: Birds of Paradise  ) = 0
252. ExecuteFirstEventAction = 0
253. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
254. ExecuteFirstEventAction = 0
255. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
256. ExecuteFirstEventAction = 0
257. StackResolveAction = 0
258. PlayCardFromStackAction (Birds of Paradise) = 735
259. ChangeStateAction = 0
260. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
261. ExecuteFirstEventAction = 0
262. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
263. ExecuteFirstEventAction = 0
264. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
265. ExecuteFirstEventAction = 0
266. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
267. ExecuteFirstEventAction = 0
268. AddEventAction (EVENT: NONE  Declare attackers.) = 0
269. MarkerAction = 0
270. LogMarkerAction = 0
271. ExecuteFirstEventAction = 0
272. DeclareAttackersAction = 0
273. TapAction (Dragonmaster Outcast) = -10
274. DeclareAttackerAction = 0
275. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
276. ExecuteFirstEventAction = 0
277. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
278. ExecuteFirstEventAction = 0
279. AddEventAction (EVENT: NONE  Declare blockers.) = 0
280. ExecuteFirstEventAction = 0
281. DeclareBlockersAction = 0
282. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
283. ExecuteFirstEventAction = 0
284. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
285. ExecuteFirstEventAction = 0
286. CombatDamageAction = 0
287. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
288. ExecuteFirstEventAction = 0
289. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
290. ExecuteFirstEventAction = 0
291. CombatDamageAction = 0
292. DealDamageAction = 0
293. ChangeLifeAction (Monty Carlo,-1) = 200
294. ChangePlayerStateAction = 0
295. AddStaticAction (MagicPermanent.NONE,magic.model.action.ChangePlayerStateAction$3@1232c463) = 0
296. ChangePlayerStateAction = 0
297. AddStaticAction (MagicPermanent.NONE,magic.model.action.ChangePlayerStateAction$3@3a5e9cbb) = 0
298. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
299. ExecuteFirstEventAction = 0
300. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
301. ExecuteFirstEventAction = 0
302. RemoveFromCombatAction (Dragonmaster Outcast) = 0
303. ChangeStateAction = 0
304. ChangeStateAction = 0
305. ChangeStateAction = 0
306. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
307. ExecuteFirstEventAction = 0
308. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
309. ExecuteFirstEventAction = 0
310. ReturnExiledAction = 0
311. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
312. ExecuteFirstEventAction = 0
313. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
314. ExecuteFirstEventAction = 0
315. CleanupTurnTriggersAction = 0
316. CleanupPlayerAction = 0
317. CleanupPermanentAction = 0
318. CleanupPermanentAction = 0
319. CleanupPermanentAction = 0
320. CleanupPermanentAction = 0
321. CleanupPermanentAction = 0
322. CleanupPlayerAction = 0
323. CleanupPermanentAction = 0
324. CleanupPermanentAction = 0
325. CleanupTurnStaticsAction = 0
326. ChangeStateAction = 0
327. ChangeStateAction = 0
328. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
329. ExecuteFirstEventAction = 0
330. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
331. ExecuteFirstEventAction = 0
332. DrawAction = -353
333. AddEventAction (EVENT: NONE  ...) = 0
334. ExecuteFirstEventAction = 0
335. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
336. ExecuteFirstEventAction = 0
337. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
338. ExecuteFirstEventAction = 0
339. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
340. ExecuteFirstEventAction = 0
341. AddEventAction (EVENT: Island Play <Island~1000104>. ) = 0
342. ExecuteFirstEventAction = 0
343. RemoveCardAction (Island) = 375
344. PlayCardAction = 0
345. AddEventAction (EVENT: Island Put <Island~1000104> onto the battlefield. ) = 0
346. ExecuteFirstEventAction = 0
347. PlayCardFromStackAction (Island) = -678
348. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
349. ExecuteFirstEventAction = 0
350. AddEventAction (EVENT: Grim Haruspex Pay {2}{B}$. Choose how to pay the mana cost.) = 0
351. AddEventAction (EVENT: Grim Haruspex Play <Grim Haruspex~1000076>. ) = 0
352. ExecuteFirstEventAction = 0
353. TapAction (Island) = 5
354. TapAction (Swamp) = 5
355. TapAction (Swamp) = 5
356. ExecuteFirstEventAction = 0
357. RemoveCardAction (Grim Haruspex) = 423
358. PutItemOnStackAction (MagicCardOnStack,Grim Haruspex) = 1
359. AddEventAction (EVENT: Grim Haruspex  ) = 0
Score = 1885

Exception from controller.runGame: Java heap space
java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
	at java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
	at magic.ui.utility.GraphicsUtils.getCompatibleBufferedImage(GraphicsUtils.java:159)
	at magic.ui.utility.GraphicsUtils.scale(GraphicsUtils.java:125)
	at magic.ui.utility.GraphicsUtils.scale(GraphicsUtils.java:55)
	at magic.ui.duel.viewer.ImagePermanentViewer.paintComponent(ImagePermanentViewer.java:272)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
```

**Comment by melvinzhang** [comment]
```

CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
CREATED ON 2016/04/30 14:11:02
MAGARENA VERSION 1.72, JRE 1.8.0_65, OS Windows 7_6.1 amd64
================================
Used Memory: 73M
Free Memory: 361M
Total Memory: 434M
Max Memory: 455M
================================
-Xms256m
-Xmx512m
-Xverify:none


Turn : 1  Phase : FirstMain  Step : ActivePlayer  Player : Monty Carlo  AI : monte carlo tree search  Score : 1701
0] Player : user  Life : 20  Delayed : Total=0
   - Hand : Birds of Paradise
   - Hand : Dragonmaster Outcast
   - Hand : Molten Rain
   - Hand : Mountain
   - Hand : Mountain
   - Hand : Mountain
   - Hand : Rootbound Crag
   - Library : Molten Rain
   - Library : Forest
   - Library : Molten Rain
   - Library : Treefolk Harbinger
   - Library : Wooded Foothills
   - Library : Abundant Growth
   - Library : Wall of Blossoms
1] Player : Monty Carlo  Life : 20  Delayed : Total=0
   - Hand : Polluted Delta
   - Hand : Polluted Delta
   - Hand : Island
   - Library : Razormane Masticore
   - Library : Swamp
   - Library : Grim Haruspex
   - Library : Swamp
   - Library : Island
   - Library : Exhume
   - Library : Swamp
Stack : 0
1. AddEventAction (EVENT: NONE user may$ take a mulligan. ) = 0
2. AddEventAction (EVENT: NONE Monty Carlo may$ take a mulligan. ) = 0
3. ExecuteFirstEventAction = 0
4. ExecuteFirstEventAction = 0
5. ShuffleCardsIntoLibraryAction = 0
6. ShiftCardAction = 0
7. RemoveCardAction (Caldera Hellion) = 304
8. MoveCardAction (Caldera Hellion,OwnersHand,TopOfOwnersLibrary) = 0
9. ShiftCardAction = 0
10. RemoveCardAction (Swamp) = 375
11. MoveCardAction (Swamp,OwnersHand,TopOfOwnersLibrary) = 0
12. ShiftCardAction = 0
13. RemoveCardAction (Island) = 375
14. MoveCardAction (Island,OwnersHand,TopOfOwnersLibrary) = 0
15. ShiftCardAction = 0
16. RemoveCardAction (Island) = 375
17. MoveCardAction (Island,OwnersHand,TopOfOwnersLibrary) = 0
18. ShiftCardAction = 0
19. RemoveCardAction (Island) = 375
20. MoveCardAction (Island,OwnersHand,TopOfOwnersLibrary) = 0
21. ShiftCardAction = 0
22. RemoveCardAction (Hell's Caretaker) = 377
23. MoveCardAction (Hell's Caretaker,OwnersHand,TopOfOwnersLibrary) = 0
24. ShiftCardAction = 0
25. RemoveCardAction (Reya Dawnbringer) = 353
26. MoveCardAction (Reya Dawnbringer,OwnersHand,TopOfOwnersLibrary) = 0
27. ShuffleLibraryAction = 0
28. DrawAction = -2345
29. AddEventAction (EVENT: NONE Monty Carlo may$ take a mulligan. ) = 0
30. ExecuteFirstEventAction = 0
31. ShuffleCardsIntoLibraryAction = 0
32. ShiftCardAction = 0
33. RemoveCardAction (Pelakka Wurm) = 375
34. MoveCardAction (Pelakka Wurm,OwnersHand,TopOfOwnersLibrary) = 0
35. ShiftCardAction = 0
36. RemoveCardAction (Harvester of Souls) = 368
37. MoveCardAction (Harvester of Souls,OwnersHand,TopOfOwnersLibrary) = 0
38. ShiftCardAction = 0
39. RemoveCardAction (Island) = 375
40. MoveCardAction (Island,OwnersHand,TopOfOwnersLibrary) = 0
41. ShiftCardAction = 0
42. RemoveCardAction (Grim Haruspex) = 423
43. MoveCardAction (Grim Haruspex,OwnersHand,TopOfOwnersLibrary) = 0
44. ShiftCardAction = 0
45. RemoveCardAction (Merfolk Looter) = 380
46. MoveCardAction (Merfolk Looter,OwnersHand,TopOfOwnersLibrary) = 0
47. ShiftCardAction = 0
48. RemoveCardAction (Liliana Vess) = 424
49. MoveCardAction (Liliana Vess,OwnersHand,TopOfOwnersLibrary) = 0
50. ShuffleLibraryAction = 0
51. DrawAction = -2120
52. AddEventAction (EVENT: NONE Monty Carlo may$ take a mulligan. ) = 0
53. ExecuteFirstEventAction = 0
54. ShuffleCardsIntoLibraryAction = 0
55. ShiftCardAction = 0
56. RemoveCardAction (Drowned Catacomb) = 490
57. MoveCardAction (Drowned Catacomb,OwnersHand,TopOfOwnersLibrary) = 0
58. ShiftCardAction = 0
59. RemoveCardAction (Elderscale Wurm) = 404
60. MoveCardAction (Elderscale Wurm,OwnersHand,TopOfOwnersLibrary) = 0
61. ShiftCardAction = 0
62. RemoveCardAction (Sun Titan) = 434
63. MoveCardAction (Sun Titan,OwnersHand,TopOfOwnersLibrary) = 0
64. ShiftCardAction = 0
65. RemoveCardAction (Rune-Scarred Demon) = 417
66. MoveCardAction (Rune-Scarred Demon,OwnersHand,TopOfOwnersLibrary) = 0
67. ShiftCardAction = 0
68. RemoveCardAction (Pelakka Wurm) = 375
69. MoveCardAction (Pelakka Wurm,OwnersHand,TopOfOwnersLibrary) = 0
70. ShuffleLibraryAction = 0
71. DrawAction = -1323
72. AddEventAction (EVENT: NONE Monty Carlo may$ take a mulligan. ) = 0
73. ExecuteFirstEventAction = 0
74. AddEventAction (EVENT: NONE  Move this card from the top of the library to the bottom?) = 0
75. ExecuteFirstEventAction = 0
76. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
77. ExecuteFirstEventAction = 0
78. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
79. ExecuteFirstEventAction = 0
80. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
81. ExecuteFirstEventAction = 0
82. AddEventAction (EVENT: Drowned Catacomb Play <Drowned Catacomb~1000099>. ) = 0
83. ExecuteFirstEventAction = 0
84. RemoveCardAction (Drowned Catacomb) = 490
85. PlayCardAction = 0
86. AddEventAction (EVENT: Drowned Catacomb Put <Drowned Catacomb~1000099> onto the battlefield. ) = 0
Score = 1701

Exception from controller.runGame: Java heap space
java.lang.OutOfMemoryError: Java heap space
	at java.awt.MultipleGradientPaintContext.calculateMultipleArrayGradient(Unknown Source)
	at java.awt.MultipleGradientPaintContext.calculateLookupData(Unknown Source)
	at java.awt.MultipleGradientPaintContext.<init>(Unknown Source)
	at java.awt.LinearGradientPaintContext.<init>(Unknown Source)
	at java.awt.LinearGradientPaint.createContext(Unknown Source)
	at sun.java2d.pipe.AlphaPaintPipe.startSequence(Unknown Source)
	at sun.java2d.pipe.AAShapePipe.renderTiles(Unknown Source)
	at sun.java2d.pipe.AAShapePipe.renderPath(Unknown Source)
	at sun.java2d.pipe.AAShapePipe.fill(Unknown Source)
	at sun.java2d.pipe.PixelToParallelogramConverter.fill(Unknown Source)
	at sun.java2d.pipe.ValidatePipe.fill(Unknown Source)
	at sun.java2d.SunGraphics2D.fill(Unknown Source)
	at javax.swing.plaf.nimbus.ToggleButtonPainter.paintBackgroundEnabled(Unknown Source)
	at javax.swing.plaf.nimbus.ToggleButtonPainter.doPaint(Unknown Source)
	at javax.swing.plaf.nimbus.AbstractRegionPainter.paint0(Unknown Source)
	at javax.swing.plaf.nimbus.AbstractRegionPainter.getImage(Unknown Source)
	at javax.swing.plaf.nimbus.AbstractRegionPainter.paintWith9SquareCaching(Unknown Source)
	at javax.swing.plaf.nimbus.AbstractRegionPainter.paint(Unknown Source)
	at javax.swing.plaf.nimbus.AbstractRegionPainter.paint(Unknown Source)
	at javax.swing.plaf.nimbus.SynthPainterImpl.paint(Unknown Source)
	at javax.swing.plaf.nimbus.SynthPainterImpl.paintBackground(Unknown Source)
	at javax.swing.plaf.nimbus.SynthPainterImpl.paintToggleButtonBackground(Unknown Source)
	at javax.swing.plaf.synth.SynthToggleButtonUI.paintBackground(Unknown Source)
	at javax.swing.plaf.synth.SynthButtonUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
```
