### ISSUE TITLE
Firemind crash with Kalitas, Traitor of Ghet

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#775]
Raised on [forums](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=18676&p=197703#p197700)

``` java
java.lang.RuntimeException: unknown count "Vampire"
   at magic.data.EnglishToInt.convert(EnglishToInt.java:35)
   at magic.model.ARG.amount(ARG.java:34)
   at magic.model.event.MagicCostEvent$2.toEvent(MagicCostEvent.java:32)
   at magic.model.event.MagicCostEvent.build(MagicCostEvent.java:280)
   at magic.model.event.MagicRegularCostEvent.<init>(MagicRegularCostEvent.java:22)
   at magic.model.event.MagicRegularCostEvent.build(MagicRegularCostEvent.java:45)
   at magic.model.event.MagicPermanentActivation.create(MagicPermanentActivation.java:114)
   at magic.model.MagicAbility$167.addAbilityImpl(MagicAbility.java:1228)
   at magic.model.MagicAbility.addAbility(MagicAbility.java:1419)
   at magic.data.CardProperty$14.setProperty(CardProperty.java:102)
   at magic.model.MagicCardDefinition.loadAbilities(MagicCardDefinition.java:188)
   at magic.model.MagicCard.<init>(MagicCard.java:100)
   at magic.model.MagicCard.<init>(MagicCard.java:88)
   at magic.model.MagicPlayer.createHandAndLibrary(MagicPlayer.java:424)
   at magic.model.MagicDuel.nextGame(MagicDuel.java:127)
   at magic.firemind.FiremindDuelRunner.runDuel(FiremindDuelRunner.java:167)
   at magic.firemind.FiremindDuelRunner.main(FiremindDuelRunner.java:76)

**Comment by melvinzhang** [comment]
Can this be replicated on Magarena?

**Comment by melvinzhang** [comment]
moved to https://github.com/firemind/ProjectFiremind-Issues/issues/39
