### ISSUE TITLE
crash at start

### ISSUE THREAD

**Issue by PSLLSP** [magarena/magarena#787]
Ubuntu 16.04, i386 (Lubuntu)

$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
OpenJDK Server VM (build 25.91-b14, mixed mode)

Crash at start:

CRASH REPORT FOR MAGARENA THREAD Thread[main,5,main]
CREATED ON 2016/06/18 15:01:44
MAGARENA VERSION 1.73, JRE 1.8.0_91, OS Linux_4.4.0-24-generic i386
================================
Used Memory: 4M
Free Memory: 243M
Total Memory: 247M
Max Memory: 494M
================================
-Xms256M
-Xmx512M
-Xverify:none

Exception from controller.runGame: no splashscreen in java.library.path
java.lang.UnsatisfiedLinkError: no splashscreen in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at java.awt.SplashScreen$1.run(SplashScreen.java:124)
	at java.awt.SplashScreen$1.run(SplashScreen.java:122)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.SplashScreen.getSplashScreen(SplashScreen.java:121)
	at magic.MagicMain.setSplashScreen(MagicMain.java:84)
	at magic.MagicMain.main(MagicMain.java:31)

**Comment by melvinzhang** [comment]
Thanks for the report. Could you check the OpenJDK package installed with the following command (run it in a terminal)
```
dpkg --get-selections | grep openjdk
```

It looks like you may have installed openjdk-8-jre-headless, please check that you have installed openjdk-8-jre (without the headless suffix).

**Comment by PSLLSP** [comment]
$ dpkg --get-selections | grep openjdk
openjdk-8-jre-headless:i386			install

------ Original Message ------
Received: Sat, 18 Jun 2016 04:54:48 PM CEST

**Comment by melvinzhang** [comment]
Thanks, that clears it up. The headless jre is not supported as we make use of the Swing UI. Please install the regular package `openjdk-8-jre` and try again. Let us know how it goes.

**Comment by PSLLSP** [comment]
I installed different JRE:

$ sudo apt-get install openjdk-8-jre

The crash is gone, game was started.

BTW, I see this error and warning in command line:

-Xms256M
-Xmx512M
-Xverify:none

Data folder : /home/psl/Downloads/Magarena-1.73/Magarena
ERROR! Unable to load from
/home/psl/Downloads/Magarena-1.73/Magarena/general.cfg,
/home/psl/Downloads/Magarena-1.73/Magarena/general.cfg (No such file or
directory)
Using random seed 9150454372680
WARNING. Unable to play clip
jar:file:/home/psl/Downloads/Magarena-1.73/Magarena.jar!/soundfx/bong.wav,
Invalid format


------ Original Message ------
Received: Sat, 18 Jun 2016 05:28:23 PM CEST
From: "Petr Slansky" <slansky@usa.net>
To: magarena/magarena
<reply@reply.github.com>
Subject: Re: [magarena/magarena] crash at start (#787)

**Comment by PSLLSP** [comment]
Different PC, older Ubuntu. Crashes at start with different error:

Ubuntu 14.04.4, i386 (LXLE)

psl@sff:~/Downloads/Magarena-1.73$ java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK Server VM (build 24.95-b01, mixed mode)

psl@sff:~/Downloads/Magarena-1.73$ dpkg -la | grep openjdk
ii  openjdk-7-jre:i386                                          7u101-2.6.6-0ubuntu0.14.04.1                 i386         OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-7-jre-headless:i386                                 7u101-2.6.6-0ubuntu0.14.04.1                 i386         OpenJDK Java runtime, using Hotspot JIT (headless)

psl@sff:~/Downloads/Magarena-1.73$ ./Magarena.sh 
Exception in thread "main" java.lang.UnsupportedClassVersionError: magic/MagicMain : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by lodici** [comment]
Wrong version of java - please see minimum requirements in wiki [Getting Started](https://github.com/magarena/magarena/wiki/Getting-Started).

**Comment by melvinzhang** [comment]
Good to hear that after installing the full version of jdk8 it now runs for you. On the older PC, you need to upgrade the package to openjdk-8-jre.
