### ISSUE TITLE
1.73 crashes at startup with unknown card property value "image_updated" 

### ISSUE THREAD

**Issue by lemonvolkswagen** [magarena/magarena#788]
crash.log:
`CRASH REPORT FOR MAGARENA THREAD Thread[pool-1-thread-1,5,main]
CREATED ON 2016/06/25 11:44:02
MAGARENA VERSION 1.73, JRE 1.8.0_91, OS Linux_3.19.0-32-generic amd64
================================
Used Memory: 22M
Free Memory: 286M
Total Memory: 309M
Max Memory: 455M
================================
-Xms256M
-Xmx512M
-Xverify:none

Exception from controller.runGame: java.lang.RuntimeException: Error loading /home/hakan/.magarena-1.73/Magarena/scripts/0_0_black_Germ_creature_token.txt
java.lang.RuntimeException: java.lang.RuntimeException: Error loading /home/hakan/.magarena-1.73/Magarena/scripts/0_0_black_Germ_creature_token.txt
	at magic.utility.MagicSystem$2.done(MagicSystem.java:55)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:251)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error loading /home/hakan/.magarena-1.73/Magarena/scripts/0_0_black_Germ_creature_token.txt
	at magic.data.CardDefinitions.loadCardDefinition(CardDefinitions.java:175)
	at magic.data.CardDefinitions.loadCardDefinitions(CardDefinitions.java:199)
	at magic.utility.MagicSystem.initializeEngine(MagicSystem.java:145)
	at magic.utility.MagicSystem.access$100(MagicSystem.java:24)
	at magic.utility.MagicSystem$1.run(MagicSystem.java:45)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: java.lang.RuntimeException: unknown card property value "image_updated" = "2015-11-12"
	at magic.data.CardDefinitions.setProperty(CardDefinitions.java:92)
	at magic.data.CardDefinitions.prop2carddef(CardDefinitions.java:119)
	at magic.data.CardDefinitions.loadCardDefinition(CardDefinitions.java:171)
	... 9 more`
game.log:

`MAGARENA GAME LOG
CREATED ON 2016/06/25 11:44:01
MAGARENA VERSION 1.73, JRE 1.8.0_91, OS Linux_3.19.0-32-generic amd64`

**Comment by melvinzhang** [comment]
@lemonvolkswagen I'm unable to replicate this on 1.73. Please try with 1.74 and let us know if this still happens.
