### ISSUE TITLE
ChangeStateAction cannot be cast MagicPermanent

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#792]
CRASH REPORT FOR MAGARENA THREAD Thread[pool-5-thread-1,5,main]
CREATED ON 2016/07/04 23:40:23
MAGARENA VERSION 1.72, JRE 1.8.0_77, OS Windows 10_10.0 amd64
================================
Used Memory: 201M
Free Memory: 232M
Total Memory: 434M
Max Memory: 1817M
================================

Turn : 3  Phase : FirstMain  Step : Resolve  Player : Player  AI : vegas  Score : -127
0] Player : Player  Life : 20  Delayed : Red=1 Generic=1 Total=2
   - Hand : Plains
   - Hand : Ronin Houndmaster
   - Hand : Mountain
   - Hand : Plains
   - Library : Battle-Mad Ronin
   - Library : Iizuka the Ruthless
   - Library : Konda's Hatamoto
   - Library : Plains
   - Library : Plains
   - Library : Araba Mothrider
   - Library : Plains
   - Permanent : Battle-Mad Ronin  Power : 1  Toughness : 1  Damage : 0  Summoned
   - Permanent : Devoted Retainer  Power : 1  Toughness : 1  Damage : 0
   - Permanent : Mountain  Summoned
   - Permanent : Plains
1] Player : Vegas  Life : 20  Delayed : Total=0
   - Hand : Mountain
   - Hand : Mountain
   - Hand : Retreat to Valakut
   - Hand : Act of Treason
   - Hand : Acolyte of the Inferno
   - Hand : Tormenting Voice
   - Hand : Ember-Eye Wolf
   - Library : Island
   - Library : Gold-Forged Sentinel
   - Library : Island
   - Library : Mountain
   - Library : Makindi Sliderunner
   - Library : Lavastep Raider
   - Library : Mountain
   - Permanent : Island  Summoned
Stack : 0
1. ExecuteFirstEventAction = 0
2. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
3. ExecuteFirstEventAction = 0
4. AddEventAction (EVENT: NONE  Declare attackers.) = 0
5. ExecuteFirstEventAction = 0
6. DeclareAttackersAction = 0
7. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
8. ExecuteFirstEventAction = 0
9. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
10. ExecuteFirstEventAction = 0
11. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
12. ExecuteFirstEventAction = 0
13. AddEventAction (EVENT: Island Play <Island~1000088>. ) = 0
14. ExecuteFirstEventAction = 0
15. RemoveCardAction (Island) = -375
16. PlayCardAction = 0
17. AddEventAction (EVENT: Island Put <Island~1000088> onto the battlefield. ) = 0
18. ExecuteFirstEventAction = 0
19. PlayCardFromStackAction (Island) = 679
20. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
21. ExecuteFirstEventAction = 0
22. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
23. ExecuteFirstEventAction = 0
24. ReturnExiledAction = 0
25. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
26. ExecuteFirstEventAction = 0
27. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
28. ExecuteFirstEventAction = 0
29. CleanupTurnTriggersAction = 0
30. CleanupPlayerAction = 0
31. CleanupPermanentAction = 0
32. CleanupPermanentAction = 0
33. CleanupPlayerAction = 0
34. CleanupPermanentAction = 0
35. CleanupTurnStaticsAction = 0
36. ChangeStateAction = 0
37. ChangeStateAction = 0
38. ChangeStateAction = 0
39. ChangeStateAction = 0
40. UntapAction (Plains) = -5
41. DrawAction = -375
42. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
43. ExecuteFirstEventAction = 0
44. AddEventAction (EVENT: Mountain Play <Mountain~1000041>. ) = 0
45. ExecuteFirstEventAction = 0
46. RemoveCardAction (Mountain) = 375
47. PlayCardAction = 0
48. AddEventAction (EVENT: Mountain Put <Mountain~1000041> onto the battlefield. ) = 0
49. ExecuteFirstEventAction = 0
50. PlayCardFromStackAction (Mountain) = -679
51. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
52. ExecuteFirstEventAction = 0
53. AddEventAction (EVENT: Battle-Mad Ronin Pay {1}{R}$. Choose how to pay the mana cost.) = 0
54. AddEventAction (EVENT: Battle-Mad Ronin Play <Battle-Mad Ronin~1000006>. ) = 0
55. ExecuteFirstEventAction = 0
56. PayDelayedCostAction = 0
57. ExecuteFirstEventAction = 0
58. RemoveCardAction (Battle-Mad Ronin) = 254
59. PutItemOnStackAction (MagicCardOnStack,Battle-Mad Ronin) = 1
60. AddEventAction (EVENT: Battle-Mad Ronin  ) = 0
61. ExecuteFirstEventAction = 0
62. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
63. ExecuteFirstEventAction = 0
64. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
65. ExecuteFirstEventAction = 0
66. StackResolveAction = 0
67. PlayCardFromStackAction (Battle-Mad Ronin) = 0
68. ChangeStateAction = 0
Score = -125

Exception from controller.runGame: magic.exception.GameException: magic.exception.GameException: java.lang.ClassCastException: magic.model.action.ChangeStateAction cannot be cast to magic.model.MagicPermanent
magic.exception.GameException: magic.exception.GameException: magic.exception.GameException: java.lang.ClassCastException: magic.model.action.ChangeStateAction cannot be cast to magic.model.MagicPermanent
	at magic.model.MagicGame.doAction(MagicGame.java:555)
	at magic.model.phase.MagicPhase.executePhase(MagicPhase.java:43)
	at magic.model.MagicGame.executePhase(MagicGame.java:469)
	at magic.model.MagicGame.advanceToNextEventWithChoice(MagicGame.java:794)
	at magic.ai.VegasWorker.runGame(VegasWorker.java:26)
	at magic.ai.VegasWorker.run(VegasWorker.java:43)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: magic.exception.GameException: magic.exception.GameException: java.lang.ClassCastException: magic.model.action.ChangeStateAction cannot be cast to magic.model.MagicPermanent
	at magic.model.MagicGame.doAction(MagicGame.java:555)
	at magic.model.event.MagicPlayCardEvent$1.executeEvent(MagicPlayCardEvent.java:27)
	at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:746)
	at magic.model.MagicGame.executeEvent(MagicGame.java:775)
	at magic.model.stack.MagicItemOnStack.resolve(MagicItemOnStack.java:129)
	at magic.model.stack.MagicCardOnStack.resolve(MagicCardOnStack.java:112)
	at magic.model.action.StackResolveAction.doAction(StackResolveAction.java:13)
	at magic.model.MagicGame.doAction(MagicGame.java:553)
	... 8 more
Caused by: magic.exception.GameException: java.lang.ClassCastException: magic.model.action.ChangeStateAction cannot be cast to magic.model.MagicPermanent
	at magic.model.MagicGame.doAction(MagicGame.java:555)
	at magic.model.action.PlayCardFromStackAction.doAction(PlayCardFromStackAction.java:61)
	at magic.model.MagicGame.doAction(MagicGame.java:553)
	... 15 more
Caused by: java.lang.ClassCastException: magic.model.action.ChangeStateAction cannot be cast to magic.model.MagicPermanent
	at magic.model.trigger.ThisBecomesBlockedTrigger.accept(ThisBecomesBlockedTrigger.java:8)
	at magic.model.MagicGame.executeTrigger(MagicGame.java:1343)
	at magic.model.MagicGame.executeTrigger(MagicGame.java:1379)
	at magic.model.action.ChangeStateAction.doAction(ChangeStateAction.java:35)
	at magic.model.MagicGame.doAction(MagicGame.java:553)
	... 17 more

**Comment by melvinzhang** [comment]
There was significant changes to ThisBecomesBlockedTrigger since 1.72. Unable to replicate on current release.
