### ISSUE TITLE
inconsistent MCTS game tree reuse

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#815]
MCTS reuses the game tree where possible by caching the tree nodes. This allows it to make use of earlier simulations.

The feature requires the game tree to contain the same nodes and options when re-encountered. When this assumption does not hold, it may lead to nodes with different number of options, causing the expansion to crash.

**Comment by melvinzhang** [comment]
Another case from CI:
```
CRASH REPORT FOR MAGARENA THREAD Thread[pool-1733-thread-26,5,main]
CREATED ON 2016/07/24 13:55:16
MAGARENA VERSION 1.75, JRE 1.8.0_40, OS Linux_3.13.0-91-generic amd64
================================
Used Memory: 308M
Free Memory: 147M
Total Memory: 456M
Max Memory: 456M
================================
-Xms256M
-Xmx512M
-Xverify:none
-Dcom.sun.management.jmxremote
-Dmagarena.dir=/home/ubuntu/magarena/release
-Ddebug=false
-DparseMissing=false
-DdevMode=false
-Dgame.log=1469366851.log
-Djava.awt.headless=true


Turn : 19  Phase : FirstMain  Step : ActivePlayer  Player : MCTS  AI : monte carlo tree search  Score : 0
0] Player : MMABC  Life : 1  Delayed : Total=0
   - Hand : Unknown
   - Hand : Unknown
   - Hand : Unknown
   - Graveyard : Hyperion Blacksmith
   - Graveyard : Goblin Skycutter
   - Graveyard : Minotaur Skullcleaver
   - Graveyard : Wall of Light
   - Library : Unknown
   - Library : Unknown
   - Library : Unknown
   - Library : Unknown
   - Library : Unknown
   - Library : Unknown
   - Library : Unknown
   - Permanent : Mountain
   - Permanent : Mountain
   - Permanent : Mountain
   - Permanent : Mountain
   - Permanent : Plains
   - Permanent : Plateau
   - Permanent : Whispersilk Cloak
1] Player : MCTS  Life : 10  Delayed : Total=0
   - Hand : Reviving Dose
   - Hand : Aura Fracture
   - Hand : Arctic Wolves
   - Hand : Thaumatog
   - Hand : Plains
   - Hand : Unknown
   - Graveyard : Forest
   - Graveyard : Nihil Spellbomb
   - Library : Unknown
   - Library : Unknown
   - Library : Unknown
   - Library : Unknown
   - Library : Unknown
   - Library : Unknown
   - Library : Unknown
   - Permanent : Apes of Rath  Power : 5  Toughness : 4  Damage : 0
   - Permanent : Endoskeleton
   - Permanent : Forest
   - Permanent : Plains
   - Permanent : Razorverge Thicket
   - Permanent : Rogue Elephant  Power : 3  Toughness : 3  Damage : 0
   - Permanent : Serpentine Basilisk  Power : 2  Toughness : 3  Damage : 0
   - Permanent : Sunpetal Grove
Stack : 0
1. ExecuteFirstEventAction = 0
2. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
3. ExecuteFirstEventAction = 0
4. ReturnExiledAction = 0
5. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
6. ExecuteFirstEventAction = 0
7. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
8. ExecuteFirstEventAction = 0
9. CleanupTurnTriggersAction = 0
10. CleanupPlayerAction = 0
11. CleanupPermanentAction = 0
12. CleanupPermanentAction = 0
13. CleanupPermanentAction = 0
14. CleanupPermanentAction = 0
15. CleanupPermanentAction = 0
16. CleanupPermanentAction = 0
17. CleanupPermanentAction = 0
18. CleanupPermanentAction = 0
19. CleanupPlayerAction = 0
20. CleanupPermanentAction = 0
21. CleanupPermanentAction = 0
22. CleanupPermanentAction = 0
23. CleanupPermanentAction = 0
24. CleanupPermanentAction = 0
25. CleanupPermanentAction = 0
26. CleanupPermanentAction = 0
27. CleanupPermanentAction = 0
28. CleanupTurnStaticsAction = 0
29. UntapAction (Mountain) = -5
30. UntapAction (Mountain) = -5
31. UntapAction (Plains) = -5
32. ChangeStateAction = 0
33. ChangeStateAction = 0
34. DrawAction = -300
35. AddEventAction (EVENT: NONE  ...) = 0
36. ExecuteFirstEventAction = 0
37. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
38. ExecuteFirstEventAction = 0
39. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
40. ExecuteFirstEventAction = 0
41. AddEventAction (EVENT: NONE  Declare attackers.) = 0
42. ExecuteFirstEventAction = 0
43. DeclareAttackersAction = 0
44. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
45. ExecuteFirstEventAction = 0
46. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
47. ExecuteFirstEventAction = 0
48. EnqueueTriggerAction = 0
49. PutItemOnStackAction (MagicTriggerOnStack,Wall of Light) = 1
50. DequeueTriggerAction = 0
51. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
52. ExecuteFirstEventAction = 0
53. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
54. ExecuteFirstEventAction = 0
55. StackResolveAction = 0
56. DestroyAction = 0
57. RemoveAllFromPlayAction = 0
58. RemoveFromPlayAction (Wall of Light,0) = 1522
59. RemoveFromCombatAction (Wall of Light) = 0
60. MoveCardAction (Wall of Light,Battlefield,Graveyard) = 0
61. RemoveTriggersStaticsAction = 0
62. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
63. ExecuteFirstEventAction = 0
64. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
65. ExecuteFirstEventAction = 0
66. ReturnExiledAction = 0
67. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
68. ExecuteFirstEventAction = 0
69. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
70. ExecuteFirstEventAction = 0
71. CleanupTurnTriggersAction = 0
72. CleanupPlayerAction = 0
73. CleanupPermanentAction = 0
74. CleanupPermanentAction = 0
75. CleanupPermanentAction = 0
76. CleanupPermanentAction = 0
77. CleanupPermanentAction = 0
78. CleanupPermanentAction = 0
79. CleanupPermanentAction = 0
80. CleanupPlayerAction = 0
81. CleanupPermanentAction = 0
82. CleanupPermanentAction = 0
83. CleanupPermanentAction = 0
84. CleanupPermanentAction = 0
85. CleanupPermanentAction = 0
86. CleanupPermanentAction = 0
87. CleanupPermanentAction = 0
88. CleanupPermanentAction = 0
89. CleanupTurnStaticsAction = 0
90. ChangeStateAction = 0
91. ChangeStateAction = 0
92. UntapAction (Forest) = 5
93. UntapAction (Plains) = 5
94. UntapAction (Razorverge Thicket) = 5
95. UntapAction (Rogue Elephant) = 10
96. UntapAction (Serpentine Basilisk) = 10
97. UntapAction (Sunpetal Grove) = 5
98. DrawAction = 300
99. AddEventAction (EVENT: NONE  ...) = 0
100. ExecuteFirstEventAction = 0
101. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
102. ExecuteFirstEventAction = 0
103. AddEventAction (EVENT: Thaumatog Pay {1}{G}{W}$. Choose how to pay the mana cost.) = 0
104. AddEventAction (EVENT: Thaumatog Play <Thaumatog~1000044>. ) = 0
Score = 1548

Exception from controller.runGame: java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
magic.exception.GameException: java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at magic.ai.MCTSAI.growTree(MCTSAI.java:421)
	at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:240)
	at magic.ai.MCTSAI$1.run(MCTSAI.java:147)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at magic.ai.MCTSAI.growTree(MCTSAI.java:417)
	... 5 more


LOG (C): MCTS attacks with <Rogue Elephant~1000064> and <Serpentine Basilisk~1000045>.
MMAB cheat=true index=0 life=1 turn=17 phase=DeclareBlockers slice=1000 time=873
* [27334/1806/-4483 at 6] (S-1342 Serpentine Basilisk=Wall of Light Rogue Elephant=Minotaur Skullcleaver)
  [27335/1965/-4589 at 7] (S-1342 Serpentine Basilisk=Minotaur Skullcleaver Rogue Elephant=Wall of Light)
  [27336/1/-99900000 at 0] (S-99955120 Rogue Elephant=Wall of Light+1)
  [27337/1/-99900000 at 0] (S-99955519 Serpentine Basilisk=Wall of Light+1)
  [27338/1/-99900000 at 0] (S-99957097 Serpentine Basilisk=Wall of Light)
  [27339/1/-99900000 at 0] (S-99957098)
  [27340/1/-99900000 at 0] (S-99957098 Rogue Elephant=Wall of Light)
  [27341/1/-99900000 at 0] (S-99958442 Serpentine Basilisk=Minotaur Skullcleaver)
  [27342/1/-99900000 at 0] (S-99958443 Rogue Elephant=Minotaur Skullcleaver)
LOG (P): MMABC blocks with <Minotaur Skullcleaver~1000012> and <Wall of Light~1000005>.
LOG (P): <Minotaur Skullcleaver~1000012> is destroyed.
LOG (C): Destroy <Wall of Light~1000005> at end of combat.
MCTS cached=33
 -> null -> null -> null -> null
PAREN: not defined
GAME : c3-w2-x0-0-0-0-0-0-1-0
GAME : c3-w2-x0-0-1-0-0-0-0-0
GAME : c3-w1-x0-0-1-0-0-0-1-0
```

**Comment by melvinzhang** [comment]
One of the causes is due to MagicGame skipping certain phases when advanced during AI thinking, as provided by the MagicGame.canSkip method. This is now turned off by default like the other options that aim to speed up MagicGame as this can cause the actual game and AI game to get out of sync leading to the inconsistent game tree.

**Comment by melvinzhang** [comment]
Remaining issue is difference score in block results, eg
```
MCTS cached=152
 -> Holy Day -> pass -> Coralhelm Commander -> c1-w0-x0-0-3-4-0-0-0-0 -> pass -> [Aphetto Grifter, Coralhelm Commander]
PAREN: S2900 Aphetto Grifter=Thalia's Lancers Coralhelm Commander=Seraph of the Sword
PAREN: S1822 Aphetto Grifter=Coiled Tinviper Coralhelm Commander=Seraph of the Sword
PAREN: S1602 Coralhelm Commander=Seraph of the Sword
PAREN: S-700 Aphetto Grifter=Thalia's Lancers
PAREN: S-700 Aphetto Grifter=Seraph of the Sword
PAREN: S-1778 Aphetto Grifter=Coiled Tinviper
PAREN: S-1998
CHILD: S2900 Aphetto Grifter=Thalia's Lancers Coralhelm Commander=Seraph of the Sword
CHILD: S1822 Aphetto Grifter=Coiled Tinviper Coralhelm Commander=Seraph of the Sword
CHILD: S1602 Coralhelm Commander=Seraph of the Sword
CHILD: S-700 Aphetto Grifter=Thalia's Lancers
CHILD: S-700 Aphetto Grifter=Seraph of the Sword
CHILD: S-1778 Aphetto Grifter=Coiled Tinviper
CHILD: S-1998
GAME : S2
GAME : S2 Coralhelm Commander=Seraph of the Sword
GAME : S2 Aphetto Grifter=Thalia's Lancers
GAME : S2 Aphetto Grifter=Thalia's Lancers Coralhelm Commander=Seraph of the Sword
GAME : S2 Aphetto Grifter=Seraph of the Sword
GAME : S2 Aphetto Grifter=Coiled Tinviper
GAME : S2 Aphetto Grifter=Coiled Tinviper Coralhelm Commander=Seraph of the Sword
```

**Comment by melvinzhang** [comment]
Fixed the blocking score problem by making scoring consistent each time.

**Comment by melvinzhang** [comment]
The last commit seems to have caught most of the remaining issues. Tested with 1000 games and did not crash due to inconsistent game tree.
