### ISSUE TITLE
Surgespanner's trigger causes unpayable mana cost

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#840]
Trigger Surgespanner with two Islands in play. Target one of the Island. The Island returns to hand before the mana cost is paid, this causes the mana cost to be unable as you only have one Island left.

**Comment by melvinzhang** [comment]
AI should not crash when encountering the unpayable mana cost. 
```
Exception from controller.runGame: java.lang.ClassCastException: magic.model.target.MagicTargetNone cannot be cast to magic.model.choice.MagicPayManaCostResult
magic.exception.GameException: java.lang.ClassCastException: magic.model.target.MagicTargetNone cannot be cast to magic.model.choice.MagicPayManaCostResult
	at magic.model.MagicGame.doAction(MagicGame.java:565)
	at magic.model.MagicGame.executeNextEvent(MagicGame.java:865)
	at magic.ai.MCTSAI.getNextChoices(MCTSAI.java:526)
	at magic.ai.MCTSAI.growTree(MCTSAI.java:352)
	at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:237)
	at magic.ai.MCTSAI$1.run(MCTSAI.java:144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: magic.model.target.MagicTargetNone cannot be cast to magic.model.choice.MagicPayManaCostResult
	at magic.model.event.MagicEvent.payManaCost(MagicEvent.java:715)
	at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:725)
	at magic.model.MagicGame.executeEvent(MagicGame.java:796)
	at magic.model.action.ExecuteFirstEventAction.doAction(ExecuteFirstEventAction.java:18)
	at magic.model.MagicGame.doAction(MagicGame.java:563)
	... 8 more
```
