### ISSUE TITLE
java.io.EOFException - MagicFileSystem.deserializeStringList

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#956]
Raised in [forum](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=19181&p=204120&sid=619e0a0988b4d9a888f9bfe6a0d850f1#p204115).
```
CRASH REPORT FOR MAGARENA THREAD Thread[pool-1-thread-1,5,main]
CREATED ON 2016/10/19 11:44:00
MAGARENA VERSION 1.77, JRE 1.8.0_91, OS Linux_3.5.0-27-generic i386
================================
Used Memory: 71M
Free Memory: 52M
Total Memory: 123M
Max Memory: 247M
================================
-Xms128M
-Xmx256M
-Xverify:all


Exception from controller.runGame: java.io.EOFException
java.lang.RuntimeException: java.io.EOFException
	at magic.utility.MagicFileSystem.deserializeStringList(MagicFileSystem.java:200)
	at magic.data.CardDefinitions.loadCardsSnapshotFile(CardDefinitions.java:478)
	at magic.data.CardDefinitions.postCardDefinitions(CardDefinitions.java:222)
	at magic.utility.MagicSystem$3.run(MagicSystem.java:177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2626)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1321)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at java.util.ArrayList.readObject(ArrayList.java:791)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at magic.utility.MagicFileSystem.deserializeStringList(MagicFileSystem.java:198)
	... 6 more
```

**Comment by lodici** [comment]
Looks like it is related to the ``snapshot.dat`` file. Maybe it was created in one version of java then at a later date, java was updated and the serialization of the file broke.

In any case, I don't think this file is that essential to the running of Magarena. IIRC it is used to determine the the set of cards shown when choosing the "new cards" filter in explorer. It should definitely fail more gracefully and should not generate an exception.
